### ISSUE TITLE
Cannot import both dotfile and non-dotfile with the same name

### ISSUE THREAD

**Issue by willemw12** [deadc0de6/dotdrop#100]
When importing file ".vimrc" and then file "vimrc", for example, the dotfile ".vimrc" disappears from the config file and "f_test_vimrc" appears twice in the same profile.

"keepdot: true" and "longkey: true".

    dotdrop --cfg="$HOME/.config/dotdrop/config.yaml" --profile=common import ~/TEST/.vimrc

config.yaml:

    config:
      backup: true
      banner: false
      create: true
      dotpath: dotfiles
      ignoreempty: false
      keepdot: true
      link_by_default: false
      longkey: true
      showdiff: false
      workdir: ~/.config/dotdrop
    dotfiles:
      f_test_vimrc:
        dst: ~/TEST/.vimrc
        src: TEST/.vimrc
    profiles:
      common:
        dotfiles:
        - f_test_vimrc

Then:

    dotdrop --cfg="$HOME/.config/dotdrop/config.yaml" --profile=common import ~/TEST/vimrc

config.yaml:

    config:
      backup: true
      banner: false
      create: true
      dotpath: dotfiles
      ignoreempty: false
      keepdot: true
      link_by_default: false
      longkey: true
      showdiff: false
      workdir: ~/.config/dotdrop
    dotfiles:
      f_test_vimrc:
        dst: ~/TEST/vimrc
        src: TEST/vimrc
    profiles:
      common:
        dotfiles:
        - f_test_vimrc
        - f_test_vimrc

**Comment by deadc0de6** [comment]
Thanks for reporting this. I fixed the bug in the master branch.
I'll release a new pypi version soon.
