### ISSUE TITLE
How to update a saved folder?

### ISSUE THREAD

**Issue by willemw12** [deadc0de6/dotdrop#101]
Is it possible to update a saved folder, without changing "dotfiles:" in the config file?

This adds a file entry in "dotfiles:":

    $ dotdrop import ~/bin/
    $ dotdrop import ~/bin/script1.sh

I tried reimporting the folder:

    $ dotdrop import ~/bin/
    [ERR] "d_bin" already present

**Comment by deadc0de6** [comment]
Yes it's possible, you should use `update` to update a dotfile.

```bash
$ dotdrop update ~/bin/
```

See the [related doc](https://github.com/deadc0de6/dotdrop#update-dotfiles)

**Comment by willemw12** [comment]
Thanks. I tried to update without a path and nothing happened.

    $ dotdrop update

I am not sure what an update without a path does. I expected it to update the whole profile.

**Comment by deadc0de6** [comment]
I updated dotdrop. Now issuing `update` without argument will update all dotfiles for the selected profile. The user is requested to confirm the update unless the `-f --force` switch is used.

**Comment by willemw12** [comment]
"dotdrop import" gives you useful messages about what is being imported. Maybe "dotdrop update ..." can output similar messages: "--> ... changed", "--> ... removed", "--> ... added"?

**Comment by deadc0de6** [comment]
Good idea, I have added a few more information when updating.

**Comment by willemw12** [comment]
Nice. 

    -> /home/willem/TEST/bin/file1 added
    -> /home/willem/.config/dotdrop/dotfiles/TEST/bin/file2 removed

From the user perspective and for consistency, I think the remove and update messages should also refer to the copied file:

    -> /home/willem/TEST/bin/file2 removed
    Overwrite "/home/willem/.config/dotdrop/dotfiles/TEST/bin/file3" with "/home/willem/TEST/bin/file3"? [y/N] ? y
    -> /home/willem/TEST/bin/file3 updated

Except now the "Overwrite ..." and "... updated" messages don't combine well.

A tiny difference between update and import messages: import paths are double-quoted, update paths are not.

**Comment by deadc0de6** [comment]
Good point, I have updated the message and quoted the paths.

**Comment by willemw12** [comment]
The paths in the update messages all refer to the saved dotfiles, not to the copied files, as I proposed. That's OK. I guess that was intentional.

There is still an issue: "dotdrop update" without a path works for folders but not for files. "dotdrop compare" does show the file differences.

**Comment by willemw12** [comment]
The paths in the update messages all refer to the saved dotfiles, not to the copied files, as I proposed. That's OK. I guess that was intentional.

There is still an issue: "dotdrop update" without a path works for folders but not for files. "dotdrop compare" does show the file differences.

Correction: file update does work, however, there is no message.

**Comment by deadc0de6** [comment]
@willemw12 I received some notifications but I cannot see the message in here ... weird.

Your point was to show the file path being updated in the filesystem instead of the ones from within dotdrop? However it made more sense for me to show the dotfile in dotdrop being updated/removed/added but I'm open to discuss this.

A message is printed when a file is updated. I wasn't able to reproduce your issue.
```bash
$ echo 'before' > ~/.test
$ ./dotdrop.sh import ~/.test
        -> "/home/user/.test" imported
$ echo 'after' > ~/.test
$ ./dotdrop.sh update
Update all dotfiles for profile test [y/N] ? y
Overwrite "/home/user/dotdrop/dotfiles/test" with "/home/user/.test"? [y/N] ? y
        -> "/home/user/dotdrop/dotfiles/test" updated
```

```

**Comment by willemw12** [comment]
I deleted the "update file" issue message, because I was testing with an older version of dotdrop. That's why it didn't work.

Displaying the saved dotfile paths in messages (as it is now) has the benefit that is also show the location of the dotfiles folder.
Displaying the copied dotfile paths in messages (what I proposed) shows the location of the files the user has edited, for example.
Both options are fine.

I am not sure it's an issue:
if "showdiff: true", then "dotdrop install" show diffs, however, "dotdrop update" does not show diffs.

**Comment by deadc0de6** [comment]
It is on purpose, `showdiff` will only apply to `install`. I don't see the point of showing a diff during update because you can always diff with `git diff` in case you want to have more details on the change(s) (and potentially adapt these).  Moreover, if one wants to see the difference, it is recommended to use the `compare` command rather than the `update` one. Does it make sense?

For the technical details, currently `update` doesn't goes through the lengthy process of *diffing* files but simply uses [filecmp](https://docs.python.org/3/library/filecmp.html).

**Comment by willemw12** [comment]
Yes, that's what I was thinking: run `dotdrop compare` to show differences when updating.
