### ISSUE TITLE
More good if ignore dotdropbak file when update and compare dotfiles?

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#102]
> `backup`: create a backup of the dotfile in case it differs from the one that will be installed by dotdrop (default true)

As `backup` default true, there will be dotdropbak files. Does it better ignore(default) dordropfiles for update and compare for directories?

**Comment by deadc0de6** [comment]
Good point! I have updated dotdrop to ignore `*.dotdropbak` for `update` and `compare`.
Thanks for suggesting this!
