### ISSUE TITLE
A dotdrop root folder path variable

### ISSUE THREAD

**Issue by Eluminae** [deadc0de6/dotdrop#105]
Hello !

Could we have a "dotfiles_root_path" similar variable ? This could be useful !

```
#~/.bash_aliases
alias dotdrop='{{@@ dotfiles_root_path @@}}/programs/dotdrop/dotdrop.sh -c ../../config.yaml'
```

and not

```
#~/.bash_aliases
alias dotdrop='$HOME/Dotfiles/programs/dotdrop/dotdrop.sh -c ../../config.yaml'
```

TY !

**Comment by deadc0de6** [comment]
Good idea, I have added the following variables:

* `{{@@ _dotdrop_dotpath @@}}` contains the [dotpath](https://github.com/deadc0de6/dotdrop/wiki/config) absolute path.
* `{{@@ _dotdrop_cfgpath @@}}` contains the absolute path to the [config file](https://github.com/deadc0de6/dotdrop/wiki/config).
* `{{@@ _dotdrop_workdir @@}}` contains the [workdir](https://github.com/deadc0de6/dotdrop/wiki/config) absolute path.

**Comment by Eluminae** [comment]
Gj !

**Comment by deadc0de6** [comment]
I have documented this [here](https://github.com/deadc0de6/dotdrop/wiki/templating#available-variables).
Are those enough or would you need some other pre-defined variables?

**Comment by Eluminae** [comment]
atm, this is enough for all my dreams

**Comment by deadc0de6** [comment]
:+1:
