### ISSUE TITLE
Preserve file timestamps when installing files

### ISSUE THREAD

**Issue by willemw12** [deadc0de6/dotdrop#107]
File (and folder) timestamps are not preserved when installing dotfiles. Git preserves timestamps, for example.

To preserve timestamps, maybe `copy2()` (https://docs.python.org/3/library/shutil.html) could be used.

Have not checked `dotdrop update` and `dotdrop import`.

**Comment by deadc0de6** [comment]
Thanks for suggesting this.

Hm to the best of my knowledge, git doesn't preserve timestamp unless you use a third party tool, do you? Which timestamp are we talking about: mtime or ctime (or atime)?

**Comment by willemw12** [comment]
Indeed. I just assumed git preserves timestamps.

About mtime, ctime: I was thinking of the `cp -p` copy option. And `cp -a` for maybe other file properties.

The whole point of this request is to keep file timestamps and permissions between hosts in sync (similar to `rsync -t` or `rsync -a`). But if git does not preserve timestamps, then this request is more or less pointless.

**Comment by deadc0de6** [comment]
In the end a file installed by dotdrop is changed and accessed and thus its mtime and ctime need to be somehow changed unless there are specific needs to keep those. An updated dotfile versioned in git won't preserve its timestamp anyway. I don't know your specific use-case so it's difficult for me to say. 

Anyway if you version your files using git, the timestamps won't be preserved. If you don't and really need this feature, I might consider it. Or you could try to do a PR for that.

**Comment by willemw12** [comment]
I don't think I will need it.

Before using dotdrop, I only used `rsync -a` to sync between hosts, keeping file properties in sync.
Now with dotdrop, only git has the original timestamp(s), etc.
