### ISSUE TITLE
Error installing dotfiles from home subfolder

### ISSUE THREAD

**Issue by ricpacca** [deadc0de6/dotdrop#11]
Hi, when I try to import in my dotfiles these two config files:
```
~/.zprezto/runcoms/zshrc
~/.zprezto/runcoms/zpreztorc
```

dotdrop creates the entries in config.yaml as well as the subfolders in the dotfiles subfolder. However it seems not to be copying the files themselves, which I had to do manually.

**Comment by deadc0de6** [comment]
Hello,

I tried reproducing the issue with no success. This is what I've done:
```bash
$ cd /tmp/
$ mkdir dotfiles && cd dotfiles
$ git init
$ git submodule add https://github.com/deadc0de6/dotdrop.git
$ ./dotdrop/bootstrap.sh
$ ./dotdrop.sh import ~/.zprezto/runcoms/zshrc
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.5
                               |_|

	-> "/home/some-user/.zprezto/runcoms/zshrc" imported

1 file(s) imported.
$ cat config.yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_zshrc:
    dst: ~/.zprezto/runcoms/zshrc
    src: zprezto/runcoms/zshrc
profiles:
  some-hostname:
  - f_zshrc
$ tree dotfiles
dotfiles
└── zprezto
    └── runcoms
        └── zshrc

2 directories, 1 file
```

What version are you using ?

Can you try to import on a fresh setup (like the above) using the `--dry` ?

**Comment by ricpacca** [comment]
Hello,
I tried both on an Ubuntu linux server and on my computer running macOS Sierra 10.12.6.
This issue only happens on the macOS computer.

Here is what happens:
`sh
$ cd /tmp/
$ mkdir dotfiles && cd dotfiles
$ git init
$ git submodule add https://github.com/deadc0de6/dotdrop.git
$ ./dotdrop/bootstrap.sh
$ ./dotdrop.sh import ~/.zprezto/runcoms/zshrc
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.5
                               |_|

	-> "/Users/<me>/.zprezto/runcoms/zshrc" imported

1 file(s) imported.
$ tree dotfiles
dotfiles
└── zprezto
    └── runcoms

2 directories, 0 files
`

I solved the issue copying the file manually.
Besides that, dotdrop still works fine for installing the config files.

**Comment by deadc0de6** [comment]
hmm ok, I found out that macOS doesn't honor `-L` in cp unless `-R` is specified (it doesn't seem like the `-r`).

I have push a fix on the dev branch, can you test this is working on macOS.
