### ISSUE TITLE
config.link_by_default not only for importing

### ISSUE THREAD

**Issue by weilbith** [deadc0de6/dotdrop#110]
My primary approach is to use the XDG-Directory Standard where ever possible. Due to this I end up with many folders which take place within `$XDG_CONFIG_HOME`. To avoid the need of manuall updating the dotfile repository, I exclusively link these folders. Unfortunately this means by the current configuration options, that I have to set `link: true` for every single application, which kinda bloat up my configuration with no additional value.
The global option `link_by_default` does also only set this option per dotfile when using the inbuilt `import` function. I would favor a behavior like `ignoreempty` provides, which allows to define a global default and can be overwritten per dotfile entry.
Is this possible to achieve or do I miss something that breaks this, since I don't use this feature so far?

**Comment by deadc0de6** [comment]
Thanks for the suggestion.
I realize the name choice for `link_by_default` wasn't really wise :-s Unfortunately I cannot change it now without impacting existing users. Anyway, I get your point and will add a new option for that.

I'm thinking something like this:

`link_install_default`: dotfiles' link default value when installing (default: *nolink*)

```
link_install_default: (link|link_children|nolink)
```

**Comment by weilbith** [comment]
Nice. Sounds like a mature option definition. :+1:

**Comment by deadc0de6** [comment]
I implemented this feature in branch `defaultlink`, could you give it a try?

`link_install_default`: dotfiles' link default value when installing (default: nolink)
```
link_install_default: (link|link_children|nolink)
```

BTW this also transparently update the entry `link_by_default` to `link_import_default`. Thus still being backward compatible and providing a better distinction between the two options.

**Comment by weilbith** [comment]
I'm just about to test it. But first some feedback for the options. Hopefully I'm allowed to do so. I have respect for your work!
Right now we have (excluding the legacy comptibiliy) the following options:

| option | scope | type |
|:---:|:---:|:---:|
| link_install_default | global | choice |
| link | local | Boolean |
| link_children | local | Boolean |

This is possibly not intuitive, since many other tools work in a different way. So what many tools are using is the hierarchy of `default` -> `global` -> `local` (I don't know how you handle default values [e.g. just injecting not defined global definitions], but this doesn't matter here], but reuse the same option name and type.
So this offers two ways of implementation by either without touching the current local options: 

| option | scope | type |
|:---:|:---:|:---:|
| link | global/local | Boolean |
| link_children | global/local | Boolean |

Or since `link` and `link_children` are exclusively (correct me if I'm wrong):


| option | scope | type |
|:---:|:---:|:---:|
| link | global/local | choice |

What are your thoughts for this?
Of cause old options must be still supported. Nethertheless I think this could lead to a clean configuration set again.

**Comment by deadc0de6** [comment]
Sure you're allowed and you are perfectly right!

For the little story dotdrop didn't start with all these options from the start and these were added little by little based on needs from different users (and PRs). I know it needs some refactoring but always postponed it ;-) 

I guess now is the time to work on that and try to refactor a bit. Would you be ok to give it a try once I've worked on refactoring some of the options? Also if you have any other recommendations or suggestions, feel free to let me know.

To answer your question, currently the defaults are indeed injected when the option is undefined.

**Comment by weilbith** [comment]
Great. I think this could be make this tool becoming even more mature. Already now I don't know a tool which is comparable to the feature Dotdrop is providing.
Since I ask you a lot for new features I'm thinking about to dig into your code to help you for implementing stuff an open PRs for you. So far I've no clue how large the actual code base is. Would you welcome such help? Even if I can't promise anything. But its also not right to just ask for stuff and don't give something back.

**Comment by deadc0de6** [comment]
@weilbith Sure I'm always happy with PR and help :-). BTW I was about to create some kind of `CONTRIBUTIONS.md` file explaining a bit how the code works and how to test it. I'll try to do that ASAP then.

**Comment by deadc0de6** [comment]
First draft is up: [CONTRIBUTING.md](https://github.com/deadc0de6/dotdrop/blob/master/CONTRIBUTING.md)

**Comment by deadc0de6** [comment]
I have made quite some change in the `defaultlink` branch. 
There are now two global options:

* `link_import_default` (sets the default link value when importing). Valid values are *nolink* and *link*
* `link_dotfile_default` (sets the default link value for dotfile when not set). Valid values are *nolink*, *link* and *link_children*

(`link_install_default` and `link_by_default` are gone)

The `link_children` entry in the dotfile was removed and the `link` entry can now have one of the following three values: *nolink*, *link* and *link_children* (it defaults to `link_dotfile_default` if undefined).

Of course old options are still supported but will be automagically substituted when dotdrop is run on a config file containing old options.

Would you be willing to give it a little try? Any testing help is always welcome!

**Comment by weilbith** [comment]
It took me 5min to realize, that the `dotdrop.sh` script when using the git submodule version (to test the feature branch), does always revert my branch checkout to master. ^^
But now I can confirm, that both options are working.

My input to the naming:
I'm not sure why `link_import_default` has the postfix `default`, since I don't see how it could be overwritten. Or do you refer to the `--inv-link` option for the CLI? Even then I would argue that both could be called the same and that it is a typical behavior, that command line options have precedence over configured options. Referring again to over tools I don't set an option to invert another option. I just want to overwrite an option. When I execute a command I know what I want to use as option if this is important for the current situation. But I don't want to check first the configured value and then think if I have to revert it or of it is already as I want to. Does this make sense?
Second point is that the first option refers to the behavior on the `import` command. The second is meant for the `install` command. But the second options does not say this. So you follow two different naming concepts here. 

Since you are about to introduce "breaking" changes, I guess taking the time two think the hard naming problem twice is the effort worth.
I see that my single-option-name is not working here. Both options affect the same option `link` from the `dotfiles` section.
I think names can be so good, that they don't need much explanation. This mustn't be the coolest and shortest names, but after all they are shorter than a useless nice name plus the description.
What do you think about `set_link_on_import`. This makes clear that the value will be set for a dotfile which gets imported. And I would argue that `link_children` can be a valid value here as well. Or why not? I mean this option makes the `import` command setting the `link` option for the dotfile. This option does support the value `link_children`. So why do we forbid it to be the default? I mean in case it is a file, I would expect this option to do nothing different than `link`. If it is a directory, this option should do the extra stuff. Right?
As second name, I would propose `default_link_on_install`. Slightly different than the previous one, it refers again on what it is doing. It says that is will become relevant during the `install` command execution. Furthermore it states, that it is the default value for the `link` option which will be used if the dotfile itself does not do so. Thought the last part is a bit interpretation, but common pattern.

**Comment by deadc0de6** [comment]
Thanks for the feedback. I understand your point and value your input! 

### Regarding `link_import_default`

The `-l --inv-link` allowed originally to invert a default linking option when importing from `False` to `True` and vice-versa. However this was there before the `link_children` feature came to be. And I then changed it to be able to switch between `nolink` and `link` (not `link_children`). I do understand now that it doesn't really make sense anymore and maybe it should be entirely removed. 

Reading your point, I would suggest changing to something like this
* refactor the cli option: `-l --link=(nolink,link,link_children)` for the `import` command where instead of inverting a value (now that we have three) would simply explicitly overwrite it.
* a new config entry: `link_on_import` (with `nolink`, `link` or `link_children` as argument)

### Regarding `link_dotfile_default`

This doesn't only apply to `install` but to other commands like `compare` and `listfiles` for example and any command that displays or uses a dotfile with no `link` defined in the config. This is the reason I named it `link_dotfile_default`. Does that make sense?


Thanks a lot for taking the time!

**Comment by weilbith** [comment]
`link_import_default`
Taken!

`link_dotfile_default`
I'm a bit confused. How is this option be used for the other commands? But of cause, this is a valid argument then.

**Comment by deadc0de6** [comment]
Awesome, I'll implement the `link_import_default` like that then.

For `link_dotfile_default`, each dotfile when parsed from the config file should have an attribute `link`. This attribute is either explicitly set in the config file (for example `link: nolink`) or implicitly through the `link_dotfile_default`. 

Beside being used for `install`, it is also used for the commands that display dotfiles (like `listfiles` and `detail`) and for other information (like debug).

In a way `link_dotfile_default` doesn't apply only to the operation (`install` command) but instead is an attribute of each dotfile entity within dotdrop.

**Comment by weilbith** [comment]
Okay, I see your argumentation. :+1:

**Comment by deadc0de6** [comment]
Ok, here's the current status:

Both `link_install_default` and `link_by_default` have been removed.

These are the new config keys:
* **link_on_import** with possible values `nolink`, `link` or `link_children`. It replaces the deprecated `link_by_default`and controls the `link` value of a new imported dotfile (`import` command). It defaults to `nolink`.
* **link_dotfile_default** with possible values `nolink`, `link` or `link_children`. It adds the ability to define the value of dotfile's `link` key when it is not defined. Since it defines the `link` attribute of dotfiles, it impacts the following commands: `install`, `listfiles` and `detail` (and some debug information that show a dotfile and its attributes). It defaults to `nolink`.

Beside the above, the cli switch `-l --inv-link` has been deprecated and is being replaced by `-l --link=<link>` for the `import` command. The valid argument for `<link>` are `nolink`, `link` or `link_children`. It overwrites the value of `link_on_import` and allows to have a fine-grained control when importing dotfiles.

The transition will be done automatically as dotdrop will live-patch the config file with the new config entries on its first run. So it shouldn't impact any user and make the transition smoother.

I'm planning on merging this into master unless your are willing to give it a try/test run.
Thanks!

**Comment by weilbith** [comment]
This looks like some great work.
One question just because I'm curious: You stated that `nolink` is the default value for `link_on_import`. But this does not mean, that if I haven't set `link_on_import`, that each time I import a new dotfile (without define `--link=<link>`) that the `config.yaml` entry has set the `link` property. Right or wrong?

**Comment by deadc0de6** [comment]
If you haven't set `link_on_import`, dotdrop will patch your config transparently and set it to the default value (this goes for `link_dotfile_default` too). In the same manner as it does for `keepdot` or other config entries in `config`.

That being said the `link` attribute of dotfiles in the config is set when importing only if it is different than the value of `link_dotfile_default`.

**Comment by weilbith** [comment]
Well, great work! :tada:

**Comment by deadc0de6** [comment]
@weilbith this was merged into master.
I'll release a new pypi version soon.
Thanks again for your help on this!

**Comment by weilbith** [comment]
Great work. Thank you for making this tool even better.
