### ISSUE TITLE
Make action status code available

### ISSUE THREAD

**Issue by weilbith** [deadc0de6/dotdrop#111]
Hey, I hope you can help me with the following problem.
Since I'm about to use a lot of actions to install packages etc (I guess you remember some of my issues :see_no_evil: ), I wanted to have a test environment to make sure my configuration is actually working. Therefore I'm now using the below `Dockerfile`. This works quite well, even if I have some DNS problems right now, which should is not related to this here.
My problem is now, that _Dotdrop_ ignores failing actions, so I have to check each build manually with my eyes. Furthermore a parsing of the output is cumbersome and even with `--verbose` I don't see an obvious always working pattern I could grep for.
How could I achieve what I plan to do? Some ideas or things I don't know?

`Dockerfile`:
```dockerfile
FROM archlinux/base

ENV USER="test"
ENV HOME="/home/$USER"
ENV DOTDROP_DIR="$HOME/dotfiles"
ENV DOTDROP_CONFIG="$DOTDROP_DIR/config.yaml"
ENV DOTDROP_PROFILE="kautz"

RUN \
  pacman -Sy --noconfirm base-devel sudo python-pip \
  pip install dotdrop \
  groupadd sudo \
  useradd --groups sudo --home-dir "$HOME" --create-home "$USER" \
  echo "$USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers \
  chown -R "$USER:$USER" "$HOME" \

USER $USER
WORKDIR $HOME
COPY . $DOTDROP_DIR

RUN dotdrop install
```

**Comment by deadc0de6** [comment]
Interesting approach!

I will add warnings and some more debugs on actions. That should allow you to grep on that to better identify what failed.

But actions execution results don't affect the return code of `install`. But we can always discuss this if you have the feeling it should be different.

**Comment by weilbith** [comment]
The problematic part is, that it is not re-executable. So if I install a single dropfile with an action to create its cache directory (cause some tools are fu***** stupid and can't do that on their own). But for any reason this action failed, then I can't replay `dotdrop install` in hope it works now, cause I adopted something, cause the dotfile itself hasn't changed. So have to manually delete all installed files for each dotfile entry which has a failed action.
Unfortunately I have no good approach how to handle this, but I guess you see the problem.

**Comment by deadc0de6** [comment]
I see your point. Actually I could make sure that if any pre-action fails, the dotfile is not installed and thus the installation will fail, what do you think?

It actually make sense since pre-action are usually about downloading stuff or pre-configuring the filesystem and if these fails, the installation shouldn't succeed for that dotfile.

**Comment by weilbith** [comment]
Yes, I think this is a very good approach. 
I'm not using so far transformation (no use-case), but I guess one of both should fail es well, right? :thinking:

**Comment by deadc0de6** [comment]
Transformation already fail (for `update` and `install`) but thanks for pointing that out.

Are you now able to run your tests successfully?

**Comment by weilbith** [comment]
Jop, I can confirm that it works. When do you upload new versions to PyPi? Any CI hook for `master` merges or so? 

Yeah, I mean the build fails now if something is wrong. :D
The only thing I'm not 100% happy about is the association. I see what failed by the flow and also the link path, but I would say it would be even more nice when having the key of the dotfile within the message of the fail. E.g.:
`[ERR] pre-action fail failed for 'f_test' with exit code 1`

But this are only my personal preferences. Single line with "all" information. :man_shrugging:

**Comment by deadc0de6** [comment]
I was planning to release a new version on Pypi once I have fixed all existing issues. You could use the [aur package](https://aur.archlinux.org/packages/dotdrop-git/) in the mean time within your docker.

**Comment by weilbith** [comment]
I'm using it for my local usage. I will just switch to it as well for my Docker image. :+1:
Depending on if you like to adjust the fail message, I would just close the issue?

**Comment by deadc0de6** [comment]
Let's keep it open, I'll see how I can bundle the error message to have a more clearer output on what went wrong.

**Comment by deadc0de6** [comment]
I have changed the way the errors are reported when installing dotfiles. It now should provide you with a oneliner error output containing the concerned dotfile and the error. In case of pre-action, you get the pre-action concerned.

installing a dotfile `f_fail` containing an action `failpre: false` would result in
```
	-> executing "false"
[WARN] action returned code 1 
[ERR] installing "f_fail" failed: pre-action "failpre" failed
```
