### ISSUE TITLE
Initial config file missing when not installing as a submodule

### ISSUE THREAD

**Issue by willemw12** [deadc0de6/dotdrop#114]
When "getting started" with dotdrop and not following the "as a submodule" section in the documentation, you get an import error:

- Install dotdrop
- Follow the "Getting started" section in the README file:

    $ dotdrop import ~/.vimrc
    [ERR] Config format error: config file path undefined

Dotdrop does not create an initial config file. The documentation does not explain, in this case, how to create an initial config file or generate one with bootstrap.sh, for example.

There is a typo in the Table of Contents: gettins-started  -->  getting-started

**Comment by deadc0de6** [comment]
Thanks a lot for reporting this!
I have updated the doc. In particular I added a new section to setup your repository: <https://github.com/deadc0de6/dotdrop/wiki/installation#setup-your-repository>. That section contains information on how to have a minimal config file to start.

Let me know if you think there's any information missing, thanks for your help!

**Comment by willemw12** [comment]
Is there a reason why dotdrop does not generate an initial config file if the file does not exists? That would make getting started a bit simpler.

I think for a local git repo, it has to be a bare repo (so not `git init` as it is in the docs):

    git init --bare ~/.config/dotdrop-repo.git
    git clone ~/.config/dotdrop-repo.git ~/.config/dotdrop
    cd ~/.config/dotdrop || exit 1
    dotdrop init
    git add ~/.config/dotdrop/config.yaml
    git commit
    git push

`dotdrop init` is just an example: it would generate an initial config file.

**Comment by deadc0de6** [comment]
Dotdrop's recommended installation is [as a submodule](https://github.com/deadc0de6/dotdrop/wiki/installation#as-a-submodule). This setup automatically provides a default config file.

If one wants to go with an alternative installation, I think getting the minimal config file with `wget` is simpler enough don't you think? Not sure adding a new command to generate that file is adding much.

I will update the doc but I wanted to avoid to go too deep into git setup as most people with use either an online platform (gitlab, github, etc) or some self-hosted solution (gitea, gitolite, etc).

**Comment by willemw12** [comment]
The git commands in my previous comment was meant for making a case for `dotdrop init`, not for adding to the docs (except for `git init --bare ...`).
