### ISSUE TITLE
ZSH completion doesn't work

### ISSUE THREAD

**Issue by laggardkernel** [deadc0de6/dotdrop#115]
I installed dotdrop as a submodule and use the `dotdrop.sh` command with an alias

```bash
alias dotdrop=<absolute-path-to-dotdrop.sh> --cfg=<path-to-your-config.yaml>'
```

The problem is completion doesn't work with the `--cfg=<path-to-your-config>` option provided. 

```bash
<absolute-path-to-dotdrop.sh> <Tab> # completion works with Tab pressed
<absolute-path-to-dotdrop.sh> --cfg=<path-to-your-config.yaml> <Tab> # doesn't work
```

**Comment by deadc0de6** [comment]
Not sure to understand, are you using the alias or `<absolute-path-to-dotdrop.sh>`?

If you use dotdrop with `<absolute-path-to-dotdrop.sh>` then you should use the completion script for *dotdrop.sh* (https://github.com/deadc0de6/dotdrop/blob/master/completion/_dotdrop.sh-completion.zsh) and if you use the alias you should use the *dotdrop* completion file: https://github.com/deadc0de6/dotdrop/blob/master/completion/_dotdrop-completion.zsh

**Comment by deadc0de6** [comment]
Well actually I'm not an expert at zsh completion and it seems you are right, it doesn't work the way it does. Any idea what I'm doing wrong?

**Comment by deadc0de6** [comment]
This is actually due to the way dotdrop's usage is made. You need to provide the command before the option
```bash
<absolute-path-to-dotdrop.sh> compare -<TAB>
-- option --
--cfg        --file       --no-banner  --verbose    -V           -c           -o                                            
--dopts      --ignore     --profile    -C           -b           -i           -p 
```

**Comment by deadc0de6** [comment]
@laggardkernel works for you?

**Comment by laggardkernel** [comment]
Yes, adding options after subcommands does work. Sorry, I'm not familiar with ZSH completion either. And thx for your help.

**Comment by laggardkernel** [comment]
I got an idea. We could use environment variable to replace `--cfg` option in the command line.

```bash
alias dotdrop="DOTDROP_CONFIG=<path-to-config> /path/to/dotdrop.sh"
```

Then, the completion would work as expected.
