### ISSUE TITLE
Automatic import of environment file

### ISSUE THREAD

**Issue by weilbith** [deadc0de6/dotdrop#116]
In [this section](https://github.com/deadc0de6/dotdrop/wiki/templating#environment-variables) of the wiki you suggest to use a `.env` file. I think this is not only useful for handling secrets but also many other stuff. For example do I like to use the XDG-directory standard. So I have a lot of `dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/'` in my `config.yaml` to link whole folders into there. (I don't know how to optimize this..?) Anyway I'm using a `env` file to define some environment variables like `XDG_CONFIG_HOME`. Right know I have to remember having this sourced always before running (any) dotdrop command (just to make sure not getting errors of `/` access defined by empty variables). Your suggestion is setting an alias. This works. But I also think it could be better. Why not taking an example by Docker, where building with a `Dockerfile` always imports a `.env` file. Or like in docker compose where you can define it manually with `env_file: <array>`.
One point: the `env` should be exported for all subprocesses so that also an executed action is aware of it and not only dotrop internally to parse the configuration file.
What do you think about this?

**Comment by deadc0de6** [comment]
I could add more pre-defined template variables for *XDG_CONFIG-HOME* along with [the existing ones](https://github.com/deadc0de6/dotdrop/wiki/templating#available-variables):
* `{{@@ _home @@}}`: points to `$HOME`
* `{{@@ _xdg @@}}`: points to `$XDG_CONFIG_HOME`

Would that help? Any other you would need?

Another way of doing this is simply by integrating those variables in the config itself through variables, for your example you could do something like this:
```yaml
dynvariables:
  xdg: "[ -z ${XDG_CONFIG_HOME} ] && echo "/home/user/.config" || echo ${XDG_CONFIG_HOME}"
```

This ensures that if `XDG_CONFIG_HOME` is undefined, it will fallback to `/home/user/.config`

**Comment by weilbith** [comment]
> Would that help? Any other you would need?

I would argue this is not a valid solution for this just do extend a fixed list. I'm fine to stay with the current syntax.

> This ensures that if XDG_CONFIG_HOME is undefined, it will fallback to /home/user/.config

Since we have the `import_variables` feature, this is quite nice. But correct me if I'm wrong, this will not export the variables for subprocesses of actions? E.g. I install the `notmuch` package as pre-action, then the configs get linked and as post action I would like to initially index my mails. Special scenario, cause notmuch watch out for `NOTMUCH_CONFIG` before looking at the default location (which is not xdg compatible). Having this variable defined as `dynvariables` would let this post-action fail, cause `notmuch` isn't able to find its configuration, since it is located anywhere else than the default directory.

**Comment by deadc0de6** [comment]
No it will not export the variables for the subprocesses however you could simply specify the env variables in the action itself, for example something similar to this (not tested)
```yaml
dynvariables:
  notmuch_config: "[ -z ${XDG_CONFIG_HOME} ] && echo "/home/user/.config/notmuch.conf" || echo ${XDG_CONFIG_HOME}/notmuch.conf"
actions:
  post:
    notmuch_index: "NOTMUCH_CONFIG={{@@ notmuch_config @@}} notmuch new"
```

**Comment by deadc0de6** [comment]
@weilbith does the above solution work for you?

**Comment by weilbith** [comment]
Sure does it work. I'll prefer to source an `.env` file before. It was more an idea to support this. Of cause there are variant alternative solutions. All fine. :upside_down_face:
