### ISSUE TITLE
Feature: join multiple files into one file.

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#117]
I've split my zshrc and vimrc to multiple parts into .zshrc.d and .vimrc.d to easy find where to setting zsh and vim.

For now, I use `source` all file at directory zshrc.d in the end of zshrc to add all settings, same with vim.

The feature is `dotdrop` auto join the setting in to `zshrc`, then zsh just need to load zshrc, no need find other setting files, same with vim.

**Comment by deadc0de6** [comment]
You can already do that with dotdrop using jinja2's `include` directive, below is a little example:

Create the different sub-files directly in the `dotpath` without importing them with dotdrop:
```bash
## file1
$ cat dotfiles/zshrc.d/file1
file1

## file 2
$ cat dotfiles/zshrc.d/file2
file2
```

import/modify your final destination file in the `dotpath` to include the other files
```bash
## edit zshrc
$ cat dotfiles/zshrc
start
{%@@ include 'zshrc.d/file1' @@%}
{%@@ include 'zshrc.d/file2' @@%}
end
```

When installing zshrc, the templating feature of dotdrop will automagically include the two files into the files.
```bash
$ cat ~/.zshrc
start
file1
file2
end
```

BTW The `include` directive argument path is relative to the `dotpath`.

**Comment by deadc0de6** [comment]
I added a wiki page for that with an example: <https://github.com/deadc0de6/dotdrop/wiki/merge-files-when-installing>

**Comment by roachsinai** [comment]
Thanks a lot! Worked also use variables.

**Comment by roachsinai** [comment]
Hi, Is there a way to include all files in a directory?

Seems have to make a list at first form [How to I include all files from inside a directory in jinja2?](https://stackoverflow.com/questions/18426944/how-to-i-include-all-files-from-inside-a-directory-in-jinja2)

**Comment by roachsinai** [comment]
And `file_list = ['dropins/file1.html', 'dropins/file2.html']` in above link should be define in `config.yaml` right?

**Comment by deadc0de6** [comment]
It is doable with a combination of dynvariables and jinja2 loop/include, I updated the documentation with an example: <https://github.com/deadc0de6/dotdrop/wiki/merge-files-when-installing#merge-all-files-in-a-directory>

**Comment by roachsinai** [comment]
```
variables:
  vim_: vimrc.d
dynvariables:
  zsh_files: "cd {{@@  @@}}; find zshrc.d/ -type f | xargs"
```

Hi, thanks for your reply! but for the set between `@@ @@` in dynvariables section, I'm confused!

Don't know how to fill it. It should be work if I use a absolute path instead of `cd {{@@ @@｝｝`. Why how to use a relative path?

> BTW The include directive argument path is relative to the dotpath.

You've said the include argument path is relative path,  and the `zshrc.d/` in `find zshrc.d/ -type f | xargs` is also a relative path. But if I use

```
dynvariables:
  zsh_files: "find zshrc.d/ -type f | xargs"
```

It only works when I located at path `~/code/Git/dotfiles/dotfiles`, `~/code/Git/dotfiles` is repo path.

**Comment by deadc0de6** [comment]
As explained in the doc you should use the built-in variable `_dotdrop_dotpath` which contains the path to your dotpath (see [available variables](https://github.com/deadc0de6/dotdrop/wiki/templating#available-variables)).

```yaml
dynvariables:
  zsh_files: "cd {{@@ _dotdrop_dotpath @@}}; find zshrc.d/ -type f | xargs"
```

Yes the include parameter is to be relative to your `dotpath` and this is what `cd {{@@ _dotdrop_dotpath @@}}` helps you to achieve by pivoting in the dotpath.

**Comment by roachsinai** [comment]
I'm so sorry, I thought I should fill the `{}` consider my situation.  Thanks!

**Comment by deadc0de6** [comment]
No worries, I updated the doc to make it more clear that this is an existing variable.

**Comment by roachsinai** [comment]
Yeah, saw it! Thanks for your help.
