### ISSUE TITLE
Avoid interaction on installing dotfiles

### ISSUE THREAD

**Issue by weilbith** [deadc0de6/dotdrop#119]
When I install my dotfiles I get the following question:
```
Remove "." for link creation? [y/N] ?
```
I have no clue which dotfile is meant (can't even find a file with a leading dot). Also I would prefer to not answer this question manually, but define default one. Is this possible and I just don't see it in the wiki (can't specify such in the code as well)? 
Thanks!

**Comment by deadc0de6** [comment]
By running dotdrop with `--verbose` you are able to see more information, it is useful to identify what part of your config file and what dotfile is generating that question.

You can ask dotdrop to be non-interactive by using `-f --force` when installing.

These information are all described in the usage: `dotdrop --help`.

**Comment by deadc0de6** [comment]
BTW by using `-d --dry` you can simulate the installation process. This option is also described in the usage: `dotdrop --help`

**Comment by weilbith** [comment]
Thanks for the information. I give it a try soon. I guess the `--force` options will be what I'm searching for. I just need to check what all it force. ;)
