### ISSUE TITLE
Feature: Ignoring certain paths when installing

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#121]
I wonder is it possible to ignore specific paths when installing dotfile
For example
d_ssh dotfiles with set
link: link_children 
Before install I concat some files to create ssh config file in ~/.ssh
so there is additional config.d directory in dotfiles source.
Then i want push those intermedieate files in config.d to repository but
dont want to symlink them when installing d_ssh dotfiles
to not create
~/.ssh/config.d

Is it possible to ignore (or add feature)
ignore:
    - 'config.d'
same as upignore

**Comment by deadc0de6** [comment]
You want to install a directory managed by dotdrop but want to ignore some files/directories inside that directory?
I'm not sure to understand what you want to do, can you be more explicit or show me an example?

**Comment by niksfirefly** [comment]
yes ignore some files or path

```
 d_ssh:
    dst: ~/.ssh
    src: .ssh
    link: link_children
    ignore:
     - '*.d'
     - 'config.d'
```

then if i got config.d in dotfiles source .ssh
will be ignored
I use files in config.d to generate config file
and want config.d to go to repo but not
to .ssh/config.d

**Comment by deadc0de6** [comment]
Ignoring files/directories when installing can be quite a headache considering linking directories, link_children and such. Wouldn't be possible for you to simply store the files to merge outside the synced directory?

Something like that:
```
dotpath
├── ssh
│   └── config
└── ssh_config.d
    ├── file1
    └── file2
```

**Comment by niksfirefly** [comment]
yes
of course it is - messy - but good solution
if it hard to implement dont bother
I thought that it would be complementary to upignore in dotdrop config

regards and keep up good work

**Comment by deadc0de6** [comment]
@niksfirefly FYI dotdrop now has a `instignore` config entry that allows to ignore files when installing, for more see [this page of the wiki](https://github.com/deadc0de6/dotdrop/wiki/ignore-pattern)
