### ISSUE TITLE
[Feature Request] Global ignore pattern for compare and update

### ISSUE THREAD

**Issue by laggardkernel** [deadc0de6/dotdrop#122]
`.DS_Store` occurs in the compare list and is copied during update. Is there a way to define `cmpignore`, `upignore` patterns globally for all `dotfiles`.

Or maybe we could let the actions comply repo's `.gitignore`.

**Comment by deadc0de6** [comment]
I implemented global `upignore` and `cmpignore`, can you give it a try and let me know how that works for you?

**Comment by laggardkernel** [comment]
Yes. It works as expected. The `.DS_Store` is not displayed during `dotdrop compare` anymore, not is it imported after `dotdrop update`. Thanks so much.

**Comment by laggardkernel** [comment]
I just found a side effect of this implementation. Every time I import a new dotfile, global `cmpignore` and `upignore` items are added into existing local `cmpignore` and `upignore`. The number of duplicate items added by this side effect keeps growing.

**Comment by deadc0de6** [comment]
Thanks for reporting this, I fixed the issue and duplicates shouldn't get added anymore. I'm sorry but you'll have to delete the duplicated entries by hand in your config file, sorry for that :-s

**Comment by laggardkernel** [comment]
Thanks again. The side effect disappeared.
