### ISSUE TITLE
[Feature Request] better template include method

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#127]
Is there a way to add(replace) include method to simplify a bit including in templates
For now due to jinja errors 
I must check if file exist and if not include default file

```
{%@@ set dir_tmpl = _dotdrop_dotpath + 'path_to_dotfile_dir' @@%}

{%@@ if exists(dir_tmpl + file) @@%}
{%@@ include(dir_tmpl + file) @@%}
{%@@ else @@%}
{%@@ include(dir_tmpl + default_file) @@%}
{%@@ endif @@%}
```
I dream of something simple like that
`{%@@ include(dir_tmpl + file, dir_tmpl + default_file) @@%}`
where we include file if exists and include optional default_file when missed

Include variations:

`{%@@ include_relative(file, default_file) @@%}`
where file/default_file are included from the same dir

`{%@@ include_absolute(file, default_file) @@%}`
where file/default_file are included with full file path (variable _dotfile_src)

regards

**Comment by deadc0de6** [comment]
It seems you can already do that with jinja2 `include`, check out the doc: <http://jinja.pocoo.org/docs/2.10/templates/#include>

That'd be something like the following (untested) where jinja2 will try to include the first existing file in the list and does nothing if none exists.
```
{%@@ include [dir_tmpl + file, dir_tmpl + default_file] ignore missing @@%}
```

**Comment by niksfirefly** [comment]
wow It works! 
even jinja2 macros!
u make my day! thanks :)
