### ISSUE TITLE
How to GPG encrypt system-wide config files?

### ISSUE THREAD

**Issue by kevinkjt2000** [deadc0de6/dotdrop#129]
I perused the documentation for [system-wide config files](https://github.com/deadc0de6/dotdrop/wiki/global-config-files), but I am unsure how to combine that with [storing sensitive files](https://github.com/deadc0de6/dotdrop/wiki/sensitive-dotfiles).

The problem mostly stems from the root account not having a copy of my gpg key, or any key for that matter.  I tried using `sudo --preserve-env` when experimenting with encrypting the file, but continued to hit walls on how to use gpg in the sudo environment.  Any ideas?

**Comment by deadc0de6** [comment]
Your command (the transformation `gpg: gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}` or anything similar you are using) is probably not provided with the environment variables needed by gpg2 as it is called through a subshell by dotdrop.

Can you try by either providing the `HOME` environment variable to it or using gpg's switch `--homedir`, one of the following:

prepending the `HOME` env variable to the transformation command
```yaml
trans:
  gpg: HOME=/home/myuserwithgpg gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}
```

use gpg2 `--homedir` cli switch
```yaml
trans:
  gpg: gpg2 -q --for-your-eyes-only --homedir=/home/myuserwithgpg/.gnupg --no-tty -d {0} > {1}
```

**Comment by kevinkjt2000** [comment]
I also suspected the home variable, but those options did not fix the issue when I tried them.  I don't believe that the HOME variable is to blame here.  I'm surprised I didn't think to do this earlier, but here is a diff of the environments:

```
$ diff <(env) <(sudo --preserve-env env)
24c24
< LOGNAME=kevin
---
> LOGNAME=root
43c43
< USER=kevin
---
> USER=root
72,74c72,76
< BASH_FUNC_add_to_path%%=() {  export PATH="$1":"$PATH"
< }
< _=/usr/bin/env
---
> _=/usr/bin/sudo
> SUDO_COMMAND=/usr/bin/env
> SUDO_USER=kevin
> SUDO_UID=1000
> SUDO_GID=1000
```

Perhaps `USER` is making the difference?  I'm about to try with `USER=kevin`, and I'll post what happens.

**Comment by deadc0de6** [comment]
Actually the issue comes from the fact you are trying to use gpg's keys of some user with root and this won't work. You probably get an error like this: 
```
gpg: WARNING: unsafe ownership on homedir '/home/someuser/.gnupg'
gpg: decryption failed: No secret key
```

A workaround is to switch user for that specific command:
```yaml
trans:
  gpg: sudo -u someuser gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}
```

**Comment by kevinkjt2000** [comment]
Manually running my trans_write command seemed to work fine:

```yaml
trans_write:
  gpg: USER=kevin gpg2 -q --encrypt --armor --recipient 0x... --output - {0} > {1}
```

```
$ sudo --preserve-env USER=kevin gpg2 -q --encrypt --armor --recipient 0x... --output - /etc/cups/printers.conf > encrypted
gpg: WARNING: unsafe ownership on homedir '/home/kevin/.gnupg'
```

Decrypting does not seem to find my default key for some reason:

```yaml
trans:
  gpg: USER=kevin gpg2 -q --for-your-eyes-only --no-tty --decrypt {0} > {1}
```

```
$ sudo --preserve-env USER=kevin gpg2 -q --for-your-eyes-only --no-tty --decrypt encrypted > decrypted
gpg: WARNING: unsafe ownership on homedir '/home/kevin/.gnupg'
gpg: decryption failed: No secret key
```

The encryption command definitely worked though, because I am able to decrypt the file:

```
$ gpg2 -q --for-your-eyes-only --no-tty --decrypt encrypted > decrypted
$ cat decrypted
Stuff I expected
```

There must be some option to specify the secret key?  Could have something to do with how the keys are usually imported from the keyring?

**Comment by kevinkjt2000** [comment]
That's a clever idea, switching users.

**Comment by kevinkjt2000** [comment]
My question is answered :+1: 
Not sure why I decided forwarding environment variables and pretending to be a user, was better than being a user.  :laughing:
