### ISSUE TITLE
Access environment variables inside templates

### ISSUE THREAD

**Issue by open-dynaMIX** [deadc0de6/dotdrop#13]
First of all: Thank you very much for dotdrop!

To make it really usable for me, I need access to environment variables inside the templates.

That way - instead af having `{%@@ if profile == "PROFILENAME" @@%}` all over the place - I can just say `{{@@ env['MY_VAR'] @@}}` to set host-specific properties. I have an `.env`-file in my directory, that is not tracked by git and I invoke dotdrop with the following alias:

```
alias dotdrop='eval $(cat ~/dotfiles/.env | egrep -v "^#") ~/dotfiles/dotdrop.sh'
```

This also gives me the possibility to use dotdrop for files that need plain-text credentials or other information I don't want to share with the public.

You can see how I use it in my [dotfiles](https://github.com/open-dynaMIX/dotfiles) (beware: I should spend some time to clean it up a bit :wink:).

Since it's just two lines, that needs to be changed, for the time being, I've just edited them locally. If there is an interest in this, I can make a PR, when I find the time.

**Comment by deadc0de6** [comment]
thanks :blush:

Sure, that looks cool, I really like the idea !
If you do a PR, I'll be happy to merge it. Feel free also to add some doc in the README so that people know about this feature.

Thanks :+1:
