### ISSUE TITLE
import_configs NoneType exception

### ISSUE THREAD

**Issue by weilbith** [deadc0de6/dotdrop#130]
I have this minimal setup of relevant files for the `import_config` split:

`config.yaml`
```yaml
config:
  dotpath: ../dotfiles
  showdiff: true
  link_on_import: 'link'
  link_dotfile_default: 'link'
  import_variables:
    - variables.d/installation_utils.yaml
  import_actions:
    - actions.d/common.yaml
    - actions.d/installation.yaml
  import_configs:
    - configs.d/organization.yaml

dotfiles:

profiles:
  kautz:
    include:
      - organization
```

`configs.d/organization.yaml`
```yaml
config:

dotfiles:
  mutt:
    actions:
      - "install_by_package_manager \"neomutt ripmime lynx\""
      - "make_directory \"{{@@ env['MAIL_DIR'] @@}} {{@@ env['MUTT_CACHE'] @@}}\""
    dst: '{{@@ env["XDG_CONFIG_HOME"] @@}}/mutt'
    src: config/mutt

profiles:
  organization:
    dotfiles:
      - mutt
```

First things first. It's not a problem and I'm not sure if easily solvable, but if I don't add these empty `config` or `dotfiles` section, _dotdrop_ complains about them as missing. Makes sense when having a single file, but with the imports not necessarily anymore.
But the actual problem is the following exception with occur when I run `dotdrop install`:
```sh
Traceback (most recent call last):
  File "/usr/sbin/dotdrop", line 11, in <module>
    load_entry_point('dotdrop==0.27.0', 'console_scripts', 'dotdrop')()
  File "/usr/lib/python3.7/site-packages/dotdrop/__init__.py", line 11, in main
    if dotdrop.dotdrop.main():
  File "/usr/lib/python3.7/site-packages/dotdrop/dotdrop.py", line 447, in main
    o = Options()
  File "/usr/lib/python3.7/site-packages/dotdrop/options.py", line 120, in __init__
    self._read_config(self.profile)
  File "/usr/lib/python3.7/site-packages/dotdrop/options.py", line 184, in _read_config
    self.conf = Cfg(self.confpath, profile=profile, debug=self.debug)
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 168, in __init__
    if not self._load_config(profile=profile):
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 202, in _load_config
    return self._parse(profile=profile)
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 331, in _parse
    self._merge_cfg(config)
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 588, in _merge_cfg
    ext_config = Cfg(config_path)
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 168, in __init__
    if not self._load_config(profile=profile):
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 202, in _load_config
    return self._parse(profile=profile)
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 247, in _parse
    if not self._complete_settings():
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 805, in _complete_settings
    self._fix_deprecated()
  File "/usr/lib/python3.7/site-packages/dotdrop/config.py", line 851, in _fix_deprecated
    if key in self.lnk_settings:
TypeError: argument of type 'NoneType' is not iterable
```

I guess this related to the stuff that the `config` of the imported file is empty. Probably @davla has an idea here?

**Comment by deadc0de6** [comment]
Yes currently all config files need to have the base entries (`config`, `dotfiles` and `profiles`). The imported config files need to be valid config files even if they are not the *main* config and thus need to contain those three entries.

If the entry `config` is empty, its entries will get the default values.

I fix the error you reported.

**Comment by weilbith** [comment]
Well the error has changed. Now it reports two errors, but more shorten. xD

```sh
[ERR] while parsing a block collection
  in "/home/test/dotfiles/config/configs.d/organization.yaml", line 7, column 7
expected <block end>, but found '<scalar>'
  in "/home/test/dotfiles/config/configs.d/organization.yaml", line 7, column 36
[ERR] missing "profiles" in config
[ERR] Config error: external config file not found: /home/test/dotfiles/config/configs.d/organization.yaml
```

Bot should be actually satisfied. There is the `profiles` section in both files and also does the external file exist...

**Comment by weilbith** [comment]
It seems like I get this `missing "profiles" in config always, no matter if I import an external config or not. :thinking:

**Comment by deadc0de6** [comment]
With the above two config files, I'm unable to reproduce your issue, can you provide me with more information:
* the command you run 
* dotdrop's output with the debug logs (`--verbose`)
* dotdrop's version
* the structure of your repository (where is your main config, where are the imported ones, etc)
* the config files you use if different from the two above
* any other information that would help me reproduce the issue

**Comment by weilbith** [comment]
While I was building a minimal example which planned to send to you as archive, I found my bug: using _Prettier_ to auto-format `.yaml` files destroy the parenthesis with all the template stuff. So I must disable it here.
Anyway I have now an example. Problem: I can't use actions sourced in the "main" configuration file. To test it, I imported it in the "sub" config file as well (which I would never prefer to do!). Now I get a duplicate reported. :see_no_evil:

**Comment by deadc0de6** [comment]
Alright. Not sure to understand, you found another issue?

**Comment by weilbith** [comment]
Yep. I solved my origin bug. Was about false parenthesis in the end, so the rest of the file was considered to be part of a single string. As result the `profile` property was missing.
I should open a new issue for this I guess?

**Comment by deadc0de6** [comment]
yes please, thanks!

**Comment by davla** [comment]
> Anyway I have now an example. Problem: I can't use actions sourced in the "main" configuration file. To test it, I imported it in the "sub" config file as well (which I would never prefer to do!). Now I get a duplicate reported. see_no_evil

Let me see if I understand this: you want to use actions defined in `actions.yaml` in `sub-config.yaml`, but by importing `actions.yaml` only in `main-config.yaml`.

This is not currently possible. `sub-config.yaml` is meant to be a standalone config file, it cannot depend on `main,yaml`

**Comment by weilbith** [comment]
@davla
You got it yes.
This is actually bad. This means I have to define linking options etc as well in every imported config?

**Comment by davla** [comment]
Yes. We were discussing something a bit more down your alley somewhere in another issue. It's just a bit to much for now, we need to do some refactoring first. And I've been a bit busy lately, plan to work on that these days ASAP.

**Comment by weilbith** [comment]
Okay. So I have to wait. Because my major use-case is to have a shorter "main" file and categorize dotfiles into topics where each one get its own profile exported to another config file. Therefore actions should be available everywhere. And the `import_profiles` files are not mighty enough by allow only the `profiles` section, which is kinda useless, when I have to define all dotfiles again in the "main" file. But this is special for my use-case. I see the advantage for other scenarios.
Looking forward to the further development. So I'll go with the basic functionality for now.
