### ISSUE TITLE
Access to dotfile filename?

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#131]
Is there a way to access processed filename as variable when installing dotfile?
proposing something like _dotfile_abs_src_filename

for example .ssh dotfile dir with link: link_children
```
.ssh
 - authorized_keys2
 - config
```
and when I run 

`dotfile install -f`

I can access _dotfile_abs_src_filename on some actions/dynvariables?

**Comment by deadc0de6** [comment]
So instead of using the full path in your template (like `/home/user/.ssh/config`) you'd like to be able to access only the basename, that is `config`?

If that's what you need, I could easily create a new [method](https://github.com/deadc0de6/dotdrop/wiki/templating#available-methods) for it. It would allow you to do something like this in your template:
```
{{%@@ set dotfile_filename = basename( _dotfile_abs_src ) @@%}}
```

and then use the variable `{{@@ dotfile_filename @@}}`.

Is that what you need?

**Comment by deadc0de6** [comment]
I have added two methods to the templates: [basename](https://github.com/deadc0de6/dotdrop/wiki/templating#available-methods) and [dirname](https://github.com/deadc0de6/dotdrop/wiki/templating#available-methods)

Here are example on how to use the filename (basename):
```
{%@@ set dotfile_filename = basename( _dotfile_abs_dst ) @@%}
dotfile dst filename: {{@@ dotfile_filename @@}}
```

**Comment by deadc0de6** [comment]
For actions, use them like that
```yaml
actions:
  post:
    loginstall: "echo {%@@ basename( _dotfile_abs_src ) @@%} installed to {{@@ _dotfile_abs_dst @@}} >> {0}"
```

**Comment by niksfirefly** [comment]
sure those are nice addons :)
but I wonder if I can access *each* filename when I install dotfile .ssh with links
so my hypothetical 
_dotfile_abs_src_filename
will contain value
'authorized_keys2' when link authorized_keys2 is installed
then
'config' when link config is installed

**Comment by deadc0de6** [comment]
Well it seems you are actually installing a single dotfile, that is this `.ssh` directory that probably look something like this:
```
d_ssh:
  src: ssh
  dst: ~/.ssh
  link: link_children
```
And you want, when it is installed, to be able to access the filename of each children it is installing.

Could you provide me an example on how you expect to use this hypothetical `_dotfile_abs_src_filename`?

From my understanding this is a single dotfile and thus variables will reference it and not to any sub-files/directories that will be linked or copied during its installation.

**Comment by niksfirefly** [comment]
Well I am testing right now your modified solution with .ssh dotfile scenario
```
dynvariables:
  allfiles: "cd {{@@ _dotdrop_dotpath @@}}; find toinclude/ -type f | xargs"
```
where I want to change 
toinclude/ 
to 
_dotfile_abs_src_filename/
```
dynvariables:
  allfiles: "cd {{@@ _dotdrop_dotpath @@}}; find _dotfile_abs_src_filename.d/ -type f | xargs"
```
and Merge all files in a directory 
.ssh/config.d to file .ssh/config
.ssh/authorized_keys.d to file .ssh/authorized_keys
on dotfile install

**Comment by deadc0de6** [comment]
I have added more variables (see [dotfile variables](https://github.com/deadc0de6/dotdrop/wiki/templating#dotfile-variables)) but it won't help for your problem.

What about delegating the inclusion to the templates themselves, similar to #127:

`<dotpath>/.ssh/config`
```
{%@@ include 'ssh_config_d/config1' @@%}
{%@@ include 'ssh_config_d/config2' @@%}
```
with your configs to include in `<dotpath>/ssh_config_d/config1` and `<dotpath>/ssh_config_d/config2`

Wouldn't that work for you?

**Comment by niksfirefly** [comment]
I found your solution superior and less error prone but
it is faster to put multiple files in dir (like .ssh) and install with links.
So I stick to my preprocessing third party script to generate files from multiple include subdirs.
Thanks anyway :)
