### ISSUE TITLE
Support nested variables

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#132]
`{%@@ if exists('{{@@ env['hman_git_folder'] @@}}/cpython') @@%}
`
this not work got error when run `dotdrop compare`:

```
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/roach/code/Git/dotfiles/dotfiles/zshrc.d/rc/exists.zsh", line 60, in template
    # {%@@ if exists('{{@@ env['hman_git_folder'] @@}}/cpython') @@%}
```

And found an upstream jinja [issue](https://github.com/pallets/jinja/issues/623) seems will not support. Make this issue just to make sure that as I can change it to not use external `jinja exists`.

By the way will get same error even I uncomment that line use `#`(which should not appear).

**Comment by deadc0de6** [comment]
It looks like it's an issue with the quotes/double-quotes, can you try with the following:
```
{%@@ if exists("{{@@ env['hman_git_folder'] @@}}/cpython") @@%}
```

**Comment by deadc0de6** [comment]
btw adding `#` in front of jinja's directive won't comment it. See [jinja2 delimiters in dotdrop](https://github.com/deadc0de6/dotdrop/wiki/templating#delimiters) and [jinja2's comment official doc](http://jinja.pocoo.org/docs/2.10/templates/#comments).

**Comment by roachsinai** [comment]
> It looks like it's an issue with the quotes/double-quotes, can you try with the following:
> 
> ```
> {%@@ if exists("{{@@ env['hman_git_folder'] @@}}/cpython") @@%}
> ```

No, it not work, seems this statement return false.

**Comment by deadc0de6** [comment]
Found two issues in your jinja2 directives:

* since you are inside jinja2 already (within the `{%@@` and `@@%}` you don't need to again enclose the variable you try to use, replace `{{@@ env['hman_git_folder'] @@}}` by `env['hman_git_folder']`
* you are trying to concate two strings and thus the argument to `exists` should be `env['hman_git_folder'] + "/cpython"`

Try with this:
```
{%@@ if exists(env['hman_git_folder'] + "/cpython") @@%}
```

**Comment by roachsinai** [comment]
@deadc0de6  worked! Thank you so much!
