### ISSUE TITLE
Should linked dotfile be skipped during comparing?

### ISSUE THREAD

**Issue by laggardkernel** [deadc0de6/dotdrop#133]
In fact, I'm reporting two problems. 

First, the linked dotfiles are still be compared. I'm not sure whether it's a bug, but at least this behavior goes against my intuition. I find out it because my `~/.config/git/ignore` file contains special characters and `diff` have trouble considering the source and target identical. A diff result is display during the comparing.

One line in the dotfile `ignore` contains double `\r` on purpose. More detail is [here](https://github.com/dvcs/gitignore/blob/master/templates/macOS.gitignore#L6-L7), check the content on a web browser.

Secondly, with `copy` installation method, the double `\r` from the source file is removed after installing into the target location. After some digging in the debug log, it seems the installation problem is related to `_handle_text_file` from `dotdrop/templategen`.  The `ignore` file is processed as text and the special linefeed is removed?

To avoid the second problem, maybe we could let users declare the file type as binary, or non-template explicitly.

**Comment by deadc0de6** [comment]
Thanks for reporting this, have you had a look at the [page dedicated to special chars](https://github.com/deadc0de6/dotdrop/wiki/special-chars)?

**Comment by deadc0de6** [comment]
I made a fix to avoid comparing symlinks (that is files that point to themselves).

**Comment by laggardkernel** [comment]
Commit 323e317 breaks comparing 😢

```bash
~
❯ dotdrop compare

~
❯ dotdrop compare -C ~/.config/nvim
=> compare d_nvim: diffing with "~/.config/nvim"
=> diff "init.vim":
280c280
< Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --bin' }
---
> Plug 'junegunn/fzf', { 'dir': '~/.local/fzf', 'do': './install --bin' }

```

And dotfile `d_nvim`, `~/.config/nvim` is not linked.

**Comment by deadc0de6** [comment]
I'm unable to reproduce the issue, can you give me more information:
* dotdrop version/commit used
* the debug logs (`--verbose`)
* the relevant config entries
* the command line used
* any additional information that would help me reproduce your issue

**Comment by laggardkernel** [comment]
It's a single slip in the loop. The loop doesn't complete during comparison. GH-134

**Comment by deadc0de6** [comment]
good catch, thanks, I merged your PR!

**Comment by laggardkernel** [comment]
Now, skipping symlink comparison solves my problem. Thanks.
