### ISSUE TITLE
[dev] Pipfile

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#135]
I prefer to use pipenv rather than bare pip, so I have Pipfile and Pipfile.lock on my hard drive, untracked by git. And this is getting a bit annoying.

I know that in order for dotdrop to be packaged on Pypi, you need a `requirements.txt`, so moving to pipenv only is not an option. So, what should I do? Should I add `Pipfile` and `Pipfile.lock` to `.gitignore` or should I rather commit them? Pypi would ignore them, but still, it's duplication.

**Comment by deadc0de6** [comment]
I'm not a pipenv user (although it looks pretty nice I must say) but if making dotdrop pipenv compatible requires only to add a `Pipfile` and a `Pipfile.lock` in the repository, I wouldn't mind. 

What would this mean in term of support in the future? Should those files be somehow updated in the future or they should only be updated when dependencies change?

Also should the `tests-requirements.txt` be integrated somehow or will it be ignored by pipenv?

**Comment by davla** [comment]
So, pipenv is meant for _applications_, not _libraries_. Stuff you don't distribute via Pypi, if it's more clear this way. For libraries, pipenv is useful to have a stable and reproducible development environment, and for no reasons whatsoever should we care about whether the _users_ would be able to use it. 

`Pipfile` and `Pipfile.lock` need to be updated only when dependencies change. They are like `requirements.txt`, but with superpowers. One of these is the `dev-packages` section, which serves the same purpose of  `tests-requirements.txt` :smile:

**Comment by deadc0de6** [comment]
Travis now runs with python 3.7.

**Comment by davla** [comment]
I added `Pipfile` and `Pipfile.lock` in davla/dotdrop@1428ffd
