### ISSUE TITLE
[Feature request] profile actions

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#141]
So, here it comes my use case.

I use zsh, and set `$ZDOTDIR=$HOME/.zsh` in my `$HOME/.zshenv` file. So I have two dotfiles in my `zsh` profiles, `f_zshenv` and `d_zsh`. I need to execute some post installation actions, so I have a `zsh` post action.

Now, the actions needs to be executed after _both_ the dotfiles have been installed, and in general after the _whole profile_ has been installed. This is currently not possible, as far as I understand, and I had to figure out which dotfile is installed last, that is not exactly nice :smile: 

So, an `action` key for profiles as well would be ideal. Should I start off by including it in the parse refactoring?

**Comment by deadc0de6** [comment]
Absolutely, go ahead and push a PR directly on the refactoring branch. That looks like a nice feature to have :+1:

So the idea would be to run the profile action if any dotfile is installed. No profile action would be run if no dotfile is installed for that specific profile (that is when no change is detected)?

**Comment by davla** [comment]
I didn't think of the change detection, but it's probably what you suggest. It should be the same as dotfiles, like _principle of least surprise_. You run the action when _any_ of the dotfiles in the profile would run the action (pretending it is listed in the dotfile own actions). You just run it once, before or after the whole profile installation.

If this is confusing, I'm pretty sure it's exactly what you suggested :smiley:

**Comment by deadc0de6** [comment]
:smile: :+1:

**Comment by deadc0de6** [comment]
this works in the new implementation in [the parsing-refactoring branch](https://github.com/deadc0de6/dotdrop/tree/parsing-refactoring).
