### ISSUE TITLE
[dev] Refactoring talk

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#144]
I'd like to use #136 just for what's strictly pertinent to what's in the pull request, that is mostly `Profile`, `Dotfile` and `CfgYaml:new_dotfile()`. Anything beyond that should be here, as it's easier to reach.

**Comment by davla** [comment]
Continuing from [#136](https://github.com/deadc0de6/dotdrop/pull/136#issuecomment-494505230).

> I'll work on that but just wanted to know if you plan on coding #141 before I start or you want to wait for it (just to avoid conflicts and such).

I worked on #141 in #143. It's not much, though, but it's all we can do at this point.

> * Creation of multiple serialization/deserialization classes:
> 
>   * new class `Profiles` that would handle the creation of a list of `Profile` object from a dictionary
>   * new class `Dotfiles` that would handle the creation of a list of `Dotfile` object from a dictionary
>   * new class `Actions` that would handle the creation of a list of `Action` object from a dictionary
>   * new class `Transformations` that would handle the creation of a list of `Transformation` object from a dictionary
>   * new class Variables/DynVariables to handle the variables

I don't understand why we need _serialization_: nothing can be changed in the YAML file by dotdrop itself (the Python program) other than profiles and dotfiles, and only when importing dotfiles. Knowing how to serialize an `Action` is not necessary, as it will every only be _deserialized_. As for `Dotfile` and `Profile`, an approach like `CfgAggregator:new_dotfile()` delegating on `CfgYaml:new_dotfile()` should do the trick.

Overall, I think your idea of serializing/deserializing is very nice (it's actially what I suggested in #128), but we need to set a smaller goal for the first refactoring milestone. Once we get this going, we can think of making it fancy.

**Comment by deadc0de6** [comment]
you're right, no need to serialize everything, was just being too verbose in my todo list.

**Comment by davla** [comment]
It took me a while, but I found time to look at what you've done. And I have a couple of questions. I's rather keep the discussion here rather than scattering it around commits:

### c00854c (fix mandatory profile argument to new dotfile)
What's the point in returning `True` and the dotfile in `new_dotfile` if you never return `False`? It should be decided whether to only return the dotfile and report any error via exceptions, or whether catching exception in `new_dotfile` and returning `False` instead. But even in that case, the returned dotfile could be `None`. In other words, that boolean is not necessary.

### 7827d88 (add optional blocks (actions, transformations))
My idea with `with_yaml_parser` decorator is that the resulting methods are able to parse the same dictionary structure from an object or from a file. This way, `Action.parse_dict` could be used to parse the files listed in `config.import_actions` for free. Probably I should have said this earlier...

**Comment by deadc0de6** [comment]
Thanks for helping but you're going too fast here.
I started to implement the higher layer config parser on top of your excellent `cfg_yaml` and quickly came into some issues in the design. I thus started an off-the-record refactoring with your `cfg_yaml` shifted to the higher layer (at least parts of it). The lower layer only caring about basic types.

I agree the `with_yaml_parser` is an excellent idea and didn't want to frustrate you by removing it. Just that the current branch is not up to date with what I have done lately.
What I would suggest is that I finish coding that refactoring in two layers and once I'll have it pushed in a branch on dotdrop we can discuss any improvements, works for you?

**Comment by davla** [comment]
Oh, you're not done yet...

My idea was that you could focus on the `import` command (as I did), while I was working on the rest of the parsing stuff. But you did it before me. That's fine I'll be waiting your next move, then.

Just one thing: I'm pretty sure Action parsing doesn't work right now. On line [85 in `action.py`](https://github.com/deadc0de6/dotdrop/blob/config-refactoring/dotdrop/action.py#L85) you have `next(iter(value))`, which won't work for multuple post/pre actions. In a case like this:
```yaml
actions:
  pre:
    action0: echo 0
    action1: echo 1
```
only `àction0` would be parsed, as `value` is the whole dict `{'action0': 'echo 0', 'action1': 'echo 1'}`, and that way you get only the first key.  
It looks to me like this is a hindering bug, thus I'm reporting it already now. I have a couple of ideas to solve it (it was supposed to be my job after all), should I proceed with a PR?

Anyway, I _was_ frustrated by the `with_yaml_parsing` deletion, but in the end it was the right thing to do. It took me quite a while to figure that out, since the decorator modifies the method/function signature in a non-intuitive way. That should've been a sign that it was not a good idea.

Finally, good job with moving Action args in the execute method. I had the same idea, started to implement something, but I apparently lost that part.

**Comment by deadc0de6** [comment]
Ok, I have completely re-think the way the parsing is being done in the [parsing-refactoring branch](https://github.com/deadc0de6/dotdrop/tree/parsing-refactoring). It now has two clear layers (lower with `cfg_yaml` and higher with `cfg_aggregator`). I made a minimal description of the design and how it globally works in [CONTRIBUTING](https://github.com/deadc0de6/dotdrop/blob/parsing-refactoring/CONTRIBUTING.md#config-parsing). Feel free to let me know if anything is unclear.

Your contribution was really helpful to me and I warmly thank you for that! :+1:

This refactoring is however not yet completely done and it still needs some love from me (testing, corner cases, etc) but globally I plan on merging that into master as the refactoring of the config parsing at some point.

If you want to play with it, feel free but as mentioned above, I still plan on updating it a bit before I'm completely happy with the changes.

I will thus unfortunately not merge your PR (#148). I'm sorry for that and should have been clearer that I wasn't done yet.

**Comment by davla** [comment]
I checked it out, and it makes sense. Normalizing dictionaries and then parsing via `XX.parse`. I see some of my code/approach is still lying around, and that's enough. I feel somehow a little part of this project, and I'm happy about it.

**Comment by deadc0de6** [comment]
@davla oh you're more than a little part of this project, your help was awesome :+1:
Yes there's a lot of your code in the refactoring and it helped me get everything straight.
Thanks again for being such a good help!
