### ISSUE TITLE
template macro caching?

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#146]
I use some macros with templates
and I found strange behaviour with defined variables.
For example
with link_children and two files to install 
- authorized_keys
- config
{{@@ _dotfile_abs_src @@}} in macro definition for 
- authorized_keys shows authorized_keys 
but for 
- config shows also authorized_keys
Is there some cache involved? or I must invalidate/clear variables in macro
when called from multiple template files?

**Comment by deadc0de6** [comment]
No there should be no cache involved. 
Can you show me the two templates (anonymized them if needed) and the command you run with the verbose outputs (`--verbose`)?

**Comment by niksfirefly** [comment]
with link_children please run two template files with same content
```
{%@@ import 'macros' as macros @@%}
{{@@ macros.test(_dotfile_sub_abs_src) @@}}
```
and macros file
```
{%@@ macro test(var) @@%}
 {{@@ "var: " + var @@}}
 {{@@ "_dotfile_abs_src: " + _dotfile_abs_src @@}}
 {{@@ "_dotfile_key: " + _dotfile_key @@}}
 {{@@ "_dotfile_link: " + _dotfile_link @@}}
 {{@@ "_dotfile_sub_abs_src: " + _dotfile_sub_abs_src @@}}
 {{@@ "_dotfile_sub_abs_dst: " + _dotfile_sub_abs_dst @@}}
{%@@ endmacro @@%}
```
You will see for second file
that var is not equal _dotfile_sub_abs_src from macro but value from previous macro use

**Comment by deadc0de6** [comment]
I was able to reproduce the issue. I didn't know at first but reading jinja2's doc on [macro](http://jinja.pocoo.org/docs/2.10/templates/#macros) redirects to the [import doc](http://jinja.pocoo.org/docs/2.10/templates/#import) which points to the [import/include context behavior page](http://jinja.pocoo.org/docs/2.10/templates/#import-visibility) that explicitely state:

```
By default, included templates are passed the current context and imported templates are not. The 
reason for this is that imports, unlike includes, are cached; as imports are often used just as a module 
that holds macros.

This behavior can be changed explicitly: by adding with context or without context to the import/include 
directive, the current context can be passed to the template and caching is disabled automatically.
```

You can thus simply import your macro with the `with context` directive to avoid caching:
```
{%@@ import 'macros' as macros with context @@%}
{{@@ macros.test(_dotfile_sub_abs_src) @@}}
```

**Comment by niksfirefly** [comment]
yeah now works as expected thanks :)
