### ISSUE TITLE
when dynamic variables are evaluated?

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#147]
When dynamic variables are evaluated?
for example with link_children for d_ssh
- every installed file? config
- with dotfile d_ssh?
- when used with dotdrop install once for all dotfiles?
I found
_dotfile_abs_src
not working at all in dynvariables
regards

**Comment by deadc0de6** [comment]
`_dotfile_abs_src`is a template variable set for each dotfile installed as explained in the doc [here](https://github.com/deadc0de6/dotdrop/wiki/templating#dotfile-variables).

For example:

`config.yaml`
```
dotfiles:
  d_testdir:
    dst: ~/.testdir
    src: testdir
    linK: link_children
```

in dotpath
```bash
for f in dotfiles/testdir/*; do echo ${f}; cat ${f}; done
dotfiles/testdir/authorized_keys
{{@@ _dotfile_abs_src @@}}
{{@@ _dotfile_sub_abs_src @@}}

dotfiles/testdir/config
{{@@ _dotfile_abs_src @@}}
{{@@ _dotfile_sub_abs_src @@}}
```

after install
```bash
for f in ~/.testdir/*; do echo ${f}; cat ${f}; done
/home/user/.testdir/authorized_keys
/home/user/dotdrop/dotfiles/testdir
/home/user/dotdrop/dotfiles/testdir/authorized_keys

/home/user/.testdir/config
/home/user/dotdrop/dotfiles/testdir
/home/user/dotdrop/dotfiles/testdir/config
```

I'm unable to reproduce your issue, please provide:
* your config file
* the relevant part of the template that doesn't work
* the install execution with the logs (`--verbose`)

**Comment by niksfirefly** [comment]
Is it working in config dynvariables for you?
```
dynvariables:
  dvar: "cd {{@@ _dotfile_abs_src @@}}"
```

**Comment by deadc0de6** [comment]
`_dotfile_abs_src` is a template variable, it is not available in the config file but only in templates. `dynvariables` are not re-evaluated for each dotfile but only when parsing the config file.

**Comment by niksfirefly** [comment]
thanks for clarification :)

**Comment by deadc0de6** [comment]
sure, I refactored a bit the doc to make it clearer:

* config variables: <https://github.com/deadc0de6/dotdrop/wiki/config-variables>
* template variables: <https://github.com/deadc0de6/dotdrop/wiki/templating#template-variables>
