### ISSUE TITLE
[feature] Misc features

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#149]
As you noticed, I stopped working on dotdrop as a developer for roughly a week, and started working on it as a _user_. This is going to be a list of tiny improvements that we could implement on top of the refactoring we are currently carrying out.

## Force action execution
It would be nice to have a flag to force action execution, regardless of whether any file changed.

### Use case
I needed to debug some actions, and I realized that they worked when launching the manually from the terminal, but not in dotdrop. This is due to dotdrop launching them from a non-interactive shell, while my terminal is clearly interactive. This means that the environment is different when executing actions in dotdrop, due to `~/.bashrc` and the like not being sourced. Hence, the convenience of replicating the actual actions execution environment as closely as possible.

## Profile inclusion order
If a profile includes other profile in a certain order, install the dotfiles and execute the actions in *that* order.

### Use case
I have a `sh` profile that contains dotfiles used by both `bash` and `zsh` profiles, which therefore include `sh`. `sh`, `bash` and `shell` are grouped in the `shell` profile, which includes them in this order.
Therefore, I need `sh` profile to be handled first, as `bash` and `zsh` depend on its dotfiles and actions.

## `cmpignore`/`upignore` path relative to dotfile path
**Disclaimer**: I still don't understand if `cmpignore` and `upignore` make sense if the dotfile is not a directory.
Currently, `cmpignore`/`upignore` paths are absolute, but can be globbed. It would make sense to me to make them also relative to the dotfile's own path.

### Use case
I have a dotfile `d_zsh`, with dst `~/.zsh`. `~/.zsh` is also my `$ZDOTDIR`, so stuff like `.zsh_history` and `.zcompdump` ends up there. Fine, but I don't want them to be part of my `d_zsh` dotfile, so I add those files to `upignore`, ending up in something like this:
```yaml
d_zsh:
  src: zsh
  dst: ~/.zsh
  upignore:
    - .zcompdump
    - .zsh_history
```
Where `.zcompdump` and `.zsh_history` are assumed to be relative to the dotfile's `dst`. While this is readable and makes a lot of sense, it doesn't work. The `upignore` paths are matched against absolute paths, and I had to do it this way:
```yaml
d_zsh:
  src: zsh
  dst: ~/.zsh
  upignore:
    - '*/.zcompdump'
    - '*/.zsh_history'
```
It would be nice to avoid this unnecessary glob. [`os.path.relpath`](https://docs.python.org/3/library/os.path.html#os.path.relpath) and a couple of ifs should do the trick.

**Comment by deadc0de6** [comment]
good ideas!!

* **force action execution**: sounds good, I'll implement it.
* **profile inclusion order**: might be more problematic (due to the fact yaml loads dict which are un-ordered) but I'll see what I can do (I want to avoid getting into OrderedDict tbh).
* **cmpignore/upignore path relative to dotfile path**: `cmpignore` and `upignore` currently contain patterns applied to both sides (dotfile paths on the filesystem and paths in the *dotpath*). This simplifies a lot the matching. I'll have a look but what I could potentially do is *patch* those if they don't contain any star (for example from `.zcompdump` in the config to `*/.zcompdump` in dotdrop).

**Comment by davla** [comment]
- **profile inclusion order**: The `include` key in profiles, is a list. That's ordered.

**Comment by deadc0de6** [comment]
I have added both `--force-actions` to force the execution of post/pre actions even if no dotfile is installed.

And made sure included profile's dotfiles/actions are executed in the correct order.

**Comment by davla** [comment]
Ok, then the last one is **cmpignore/upignore path relative to dotfile path**.

I don't understand the problem. All I meant is to prefix the paths in `cmpignore`/`upignore` with `src` and `dst` from the dotfile entry.

So, again the previous example:
```yaml
d_zsh:
  src: zsh
  dst: ~/.zsh
  upignore:
    - .zcompdump
    - .zsh_history
```
When updating, the paths in `upignore` should be prefixed with `dst`, so that `~/.zsh/.zcompdump` and `~/.zsh/.zsh_history` are ignored.

As for comparing, the approach would be the same: prefix with `src` for the file in the *dotpath* and with `dst` for the one on the filesystem.

All of this, of course if the path is not absolute, nor it starts with a glob.

**Comment by deadc0de6** [comment]
It makes sense, I'll implement it and keep you posted.
Thanks for the precision!

**Comment by deadc0de6** [comment]
I implemented relative ignores (`cmpignore`, `upignore` or `-i --ignore`).
If you test it, let me know, thanks!

**Comment by davla** [comment]
So, `upignore` works like a charm. I don't know if it's intended, but it even does not display the annoying message about ignored paths. I like it better this way: if it's ignored, I don't wanna see it at all :laughing:

**Comment by deadc0de6** [comment]
I fixed `cmpignore`, should work now hopefully :wink:

**Comment by davla** [comment]
Ok, `cmpignore` now works, but there has been a side effect. This is my use case (yes, `upignore` and `cmpignore` are exactly the same):
```yaml
  d_zsh:
    dst: ~/.zsh
    src: zsh
    upignore:
    - .zcompdump
    - .zsh_history
    - .antibody
    - cache
    - 'plugins/plugins-*.zsh'
    cmpignore:
    - .zcompdump
    - .zsh_history
    - .antibody
    - cache
    - 'plugins/plugins-*.zsh'
```
Before `469a827` the last glob (`plugins/plugins-*.zsh`) worked fine, and detected my two files `~/.zsh/plugins/plugins-before-compinit.zsh` and `~/.zsh/plugins/plugins-after-compinit.zsh`, but after that commit, it no longer matches those two files.

As you can see, the problem is that the path is *both* relative to `dst` *and* it contains a glob. I don't know whether this is meant to be supported in the first place, but it could be fixed pretty easily by changing [line 149 utils.py](https://github.com/deadc0de6/dotdrop/blob/parsing-refactoring/dotdrop/utils.py#L149) this way:
```python
< if STAR in ignore:
> if ignore.startswith(PATH + os.path.sep)
```
This means that globs are *not* prefixed with `dst` only if the glob occurs at the beginning and it's not part of the file name, but the directory name.

**Comment by deadc0de6** [comment]
I fixed it, thanks for pointing that out!

**Comment by davla** [comment]
Everything works fine now.
