### ISSUE TITLE
Pass options to diff

### ISSUE THREAD

**Issue by hoclun-rigsep** [deadc0de6/dotdrop#15]
Would be nice to be able to pass options to `diff` when using the compare command.

**Comment by deadc0de6** [comment]
I added an option to dotdrop to pass arguments to `diff` in the branch [diffopts](https://github.com/deadc0de6/dotdrop/tree/diffopts). This should allow to pass any arguments to `diff` through the switch `-o`. Note that the option `-r, --recursive` is always activated when comparing.

for example:
```
dotdrop compare -o "-c5 -a"
```

will execute `diff -r -c5 -a` on the dotfiles to compare.

Can you test it out and let me know if that matches what you needed ?

**Comment by hoclun-rigsep** [comment]
I will test it out tonight; thanks.

**Comment by deadc0de6** [comment]
I thought of adding this option in the config file as a new entry like `diffoptions` and remove it from the cli switches, what do you think ? This would make it more permanent. The options you are using are to be applied every time you compare or only on specific occasions ?

**Comment by hoclun-rigsep** [comment]
Looks good to me. My main motivation so far was to help with initial generation of template files; i.e. if before dotdrop came into my life I had similar versions of files on different hosts, it's pretty easy to change a unified diff with "-U999" or "-D" into the template I want. I therefore wouldn't be using this every time I use compare.

**Comment by deadc0de6** [comment]
Ok, I get it. I'll keep it as a CLI switch then.
I have merged the branch with master and have released a new version with these changes. Thanks for your input!

**Comment by hoclun-rigsep** [comment]
Neat! I would have offered to do up a patch but you anticipated me!
