### ISSUE TITLE
[bug] update deletes files with no transformation

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#157]
Dotdrop version: v0.28.0 (commit 9d0c30e, branch parsing-refactornig)
Using dotdrop: as a submodule, (actually subtree, but from your point of view it's the same)

`bash dotdrop.sh update` deletes the updated file if it has no transformation. For example,
```sh
bash dotdrop.sh update $HOME/.abc
```
would delete `$HOME/.abc`.

The culprit seems to be https://github.com/deadc0de6/dotdrop/blob/9d0c30e63319a47672e45830c2e111de028bf99d/dotdrop/updater.py#L102-L103

in fact, `new_path` is the same as `path` if the dotfile has no transformation
https://github.com/deadc0de6/dotdrop/blob/9d0c30e63319a47672e45830c2e111de028bf99d/dotdrop/updater.py#L106-L110

As far as I understand, you want to clear out the transformation output after updating. A possible solution would then be to change the condition to
```python
if new_path != path and os.path.exists(new_path):
```
And removing the assignment on line 95.

I started drafting a pull request, but then I look at the test cases, starting with the Python one, and I see this:
https://github.com/deadc0de6/dotdrop/blob/9d0c30e63319a47672e45830c2e111de028bf99d/tests/test_update.py#L135
I tried to understand what's going on there, but I cannot get my head around the test case. I don't understand why that directory should not exist anymore if it's not a transformation output (Plus, the test case creates a few unused directories here and there).

**Comment by deadc0de6** [comment]
Thanks for reporting this!
Indeed you were right, it was a bug, I fixed it thanks to your help!

Here's the little explanation for `test-update.py` (I must admit it took me some time to work my head around those tests too ;-)):

Here's the directory that is being imported (from line 68): 
```
dir1 (<tmp>/${dir1string}):
- sub1 (<tmp>/${dir1string}/${dir1sub1str})
  - f1s1 (<tmp>/${dir1string}/${dir1sub1str}/<somefile>)
- sub2 (<tmp>/${dir1string}/${dir1sub2str})
  - f1s2 (<tmp>/${dir1string}/${dir1sub2str}/<somefile>)
```

where `<tmp>` is a temporary directory to which also points `dirsubs` (line 66).

The path of this directory (`dir1`) in the `dotpath` is retrieved in line 117 and the variable `d1indotpath` is set to point to it.

The variable `gone` is constructed to point to `sub1` in the `dotpath` and then `sub1` is deleted (line 131). The test then checks on line 135 that `gone` doesn't exist anymore in the dotpath that is that `dir1` in the `dotpath` was in fact updated and that `sub1` in the `dotpath` doesn't exist anymore.

**Comment by davla** [comment]
Ok, makes sense now.
