### ISSUE TITLE
[bug] `dotfiles` key in profile

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#165]
Dotdrop version (and git commit if run from source): v0.29.1 5c6db63
Using dotdrop: as a subtree

When importing to a profile with no `dotfiles` key, dotdrop crashes with 
```bash
 File ".../dotdrop/dotdrop/cfg_yaml.py", line 638, in add_dotfile_to_profile
    if dotfile_key not in profile[self.key_profile_dotfiles]:
...
KeyError: 'dotfiles'
```

So, why having a profile with no `dotfiles`? Because I use it as a "hub" to group other profiles via `include`. If this use case makes sense, then the `dotfile` key should be made optional.

Of course I can PR for this.

**Comment by deadc0de6** [comment]
Please PR if you feel like, also add a test if you have the motivation.
If you need help, feel free to ask!

**Comment by deadc0de6** [comment]
This is now fixed in the master branch, thanks for reporting!

**Comment by raember** [comment]
I can reproduce the issue on the current git version [86783ca](https://github.com/deadc0de6/dotdrop/tree/86783ca554584594511674ab6d6c161c6f420ef4) (0.29.5). It happens when I import dotfiles and the profile has no empty `dotfiles: []` in the profile. Just adding it manually isn't a viable solution, as dotdrop itself deletes the `dotfiles` entry itself, if it's empty.

**Comment by deadc0de6** [comment]
The `dotfiles` entry (as well as the `config` and the `profiles` entries) is mandatory (see the [config format](https://github.com/deadc0de6/dotdrop/wiki/config#format)).

You can provide a config file with an empy `dotfiles` entry like this for example:
```yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
profiles:
```

**Comment by raember** [comment]
There might be a misunderstanding: I'm not talking about the root level `dotfiles` entry, but the ones under individual profiles. I have a `common` profile and a profile for each of my machines, which inherit from `common` and have an empty list as their `dotfiles`.

This is the traceback I get when I import something while not having a `dotfiles` entry in my profile.:
```
Traceback (most recent call last):
  File "/usr/bin/dotdrop", line 11, in <module>
    load_entry_point('dotdrop==0.29.5', 'console_scripts', 'dotdrop')()
  File "/usr/lib/python3.8/site-packages/dotdrop/__init__.py", line 11, in main
    if dotdrop.dotdrop.main():
  File "/usr/lib/python3.8/site-packages/dotdrop/dotdrop.py", line 596, in main
    o = Options()
  File "/usr/lib/python3.8/site-packages/dotdrop/options.py", line 125, in __init__
    self._read_config()
  File "/usr/lib/python3.8/site-packages/dotdrop/options.py", line 182, in _read_config
    self.conf = Cfg(self.confpath, self.profile, debug=self.debug)
  File "/usr/lib/python3.8/site-packages/dotdrop/cfg_aggregator.py", line 42, in __init__
    self._load()
  File "/usr/lib/python3.8/site-packages/dotdrop/cfg_aggregator.py", line 46, in _load
    self.cfgyaml = CfgYaml(self.path,
  File "/usr/lib/python3.8/site-packages/dotdrop/cfg_yaml.py", line 120, in __init__
    self._resolve_profile_includes()
  File "/usr/lib/python3.8/site-packages/dotdrop/cfg_yaml.py", line 474, in _resolve_profile_includes
    self._rec_resolve_profile_include(k)
  File "/usr/lib/python3.8/site-packages/dotdrop/cfg_yaml.py", line 511, in _rec_resolve_profile_include
    dotfiles.extend(o_dfs)
AttributeError: 'NoneType' object has no attribute 'extend'
```
The config looks something like this (simplified):
```yaml
profiles:
  common:
    dotfiles:
    - ...
  pc:
    dotfiles: []
    include:
    - common
  laptop:
    dotfiles: []
    include:
    - common
```
Running `dotdrop import <path>` once removes the *empty* `dotfiles` entries of all my profiles (except the current profile ofc, as it gets the imported dotfile added to the empty list) and on the next run it fails with the exception I posted above.

**Comment by deadc0de6** [comment]
oh I see, sorry I misread.

I identified a few bugs and fixed them, can you give it a try?

If you still have issues, can you provide me with the exact steps you take to trigger the bug (with what profiles you import, what you mean by *next run*, the config files on different stages, etc) and the debug logs if possible as this can greatly help me to reproduce the issue. Thanks!

**Comment by raember** [comment]
I pulled the latest commit and t works now.

Thank you very much again for your fast responses and the quick fix!
