### ISSUE TITLE
[bug] link_dotfile_default and link_on_import seem to be broken

### ISSUE THREAD

**Issue by Marteon** [deadc0de6/dotdrop#166]
Dotdrop version: v0.29.1 (4a96d79)
Using dotdrop: installed `dotdrop-git` from aur.

**Describe the bug**
In my config I set `link_on_import: link` and `link_dotfile_default: link` 
But when using `dotdrop import ~/test` the `link: link` attribute is missing in the config.

**Steps to Reproduce**

1. Use described config
2. `touch ~/test`
3. `dotdrop import ~/test`

**Expected behavior**
It would be expected that `link: link` is written in the config for in the section for `test`.

**Additional information**
It seems that none of the link configs is applied.
I`ll have a look into it if I find time next week.

The relevant part of the config file
```yaml
link_dotfile_default: link
link_on_import: link

```

**Comment by deadc0de6** [comment]
This is intended. The `link_dotfile_default` config option defines what is the link behavior when the `link` entry is not present in the dotfile entry. Since you use `link_on_import`, when importing a file, its `link` value would be `link` but considering this is the default, dotdrop doesn't add it.

What was not intended however is that it wasn't reflected during install, this is now fixed. Thanks for reporting this!

**Comment by Marteon** [comment]
Now as I read it more carefully I saw that it is intended.
Thank you for the quick fix!

But isn't it counterintuitive that, we don't add `link: link` when `link_dotfile_default: link` is set.
Couldn't you change your mind about `link_dotfile_default` but still want imported files to be symlinked?

My suggestion would be to change the behavior of `link_on_import: link/unlink` to always write the `link` config.
To still make the current behavior I suggest adding another option to `link_on_import` which might be called something like `inherit` and inherits the link setting from `link_dotfile_default` and thus write nothing in the config.

**Comment by deadc0de6** [comment]
It is actually the whole point of having a *global* defined default: be able to change all your dotfiles behavior without having to script it and change every entry in the config. Note that the `link` entry is optional on dotfiles.

I'm not sure to understand your use-case:
> Couldn't you change your mind about link_dotfile_default but still want imported files to be symlinked?

My point is that most people either are symlinking their dotfiles or copying them and have usually only a few exceptions where you can always use the cli switch `-l --link` to specify the `link` behavior. If on the other hand you want to change the behavior of all the dotfiles, you just change `link_dotfile_default`.

But maybe I'm missing the point and you have some specific needs ...

**Comment by laggardkernel** [comment]
>But isn't it counterintuitive that, we don't add link: link when link_dotfile_default: link is set.
Couldn't you change your mind about link_dotfile_default but still want imported files to be symlinked?

@Marteon  That's not counter-intuitive at all. Why do you need add a value for a dotfile specific option if the the very value is the **same as the global option**? It doesn't make sense.

@deadc0de6 BTW, is it the fix related to my problem? 

#170 Incorrect detection of global link value

**Comment by deadc0de6** [comment]
@laggardkernel nope that's unrelated

**Comment by Marteon** [comment]
Yeah I guess it's good as it is.
Closing because the bug was fixed.
