### ISSUE TITLE
Automatic update of modified dotfile

### ISSUE THREAD

**Issue by r4nd0m6uy** [deadc0de6/dotdrop#17]
Because I'm a boring and lazy user ...

Related to #4, it seems I'm not the only one looking for this feature that would be great to have.

Templated files sound tricky, but as first step, what about updating "flat" files automatically and requesting the user to manually update files containing Jinja syntax?

**Comment by deadc0de6** [comment]
I created a branch with the ability to *update* dotfiles: https://github.com/deadc0de6/dotdrop/tree/update

it can be used like this:
```
./dotdrop.sh update <some-dotfile>
```

It asks the user for overwritting a *flat* dotfile and will simply warn and ignore the update when it uses templating.

Can you test it and let me know what you think ?

**Comment by deadc0de6** [comment]
here's some doc I've added regarding this feature: https://github.com/deadc0de6/dotdrop/tree/update#update-dotfiles

**Comment by r4nd0m6uy** [comment]
So I did my homework and I would use this feature. I appreciate the `-f` option, thanks!

**Comment by deadc0de6** [comment]
done, new version is up!
