### ISSUE TITLE
[bug] TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by TitusLabienus** [deadc0de6/dotdrop#171]
Dotdrop version: v0.29.3-1

**Describe the bug**
`dotdrop install` or `dotdrop import` results in the following error message:

> TypeError: expected str, bytes or os.PathLike object, not NoneType

**Steps to reproduce**
```
yay -S dotdrop
mkdir ~/dotdrop && cd ~/dotdrop
dotdrop install
```

> Traceback (most recent call last):
>   File "/usr/bin/dotdrop", line 11, in <module>
>     load_entry_point('dotdrop==0.29.3', 'console_scripts', 'dotdrop')()
>   File "/usr/lib/python3.7/site-packages/dotdrop/__init__.py", line 11, in main
>     if dotdrop.dotdrop.main():
>   File "/usr/lib/python3.7/site-packages/dotdrop/dotdrop.py", line 577, in main
>     o = Options()
>   File "/usr/lib/python3.7/site-packages/dotdrop/options.py", line 125, in __init__
>     self._read_config()
>   File "/usr/lib/python3.7/site-packages/dotdrop/options.py", line 182, in _read_config
>     self.conf = Cfg(self.confpath, self.profile, debug=self.debug)
>   File "/usr/lib/python3.7/site-packages/dotdrop/cfg_aggregator.py", line 42, in __init__
>     self._load()
>   File "/usr/lib/python3.7/site-packages/dotdrop/cfg_aggregator.py", line 48, in _load
>     debug=self.debug)
>   File "/usr/lib/python3.7/site-packages/dotdrop/cfg_yaml.py", line 79, in __init__
>     self.path = os.path.abspath(path)
>   File "/usr/lib/python3.7/posixpath.py", line 378, in abspath
>     path = os.fspath(path)
> TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by deadc0de6** [comment]
Thanks for reporting this. It happens when dotdrop doesn't find a valid config file in the [common locations](https://github.com/deadc0de6/dotdrop/wiki/config#location).

A more explicit output should be printed with above commit.
