### ISSUE TITLE
[bug] Installing a dotfile via symlinking reports it being installed every time

### ISSUE THREAD

**Issue by aeubanks** [deadc0de6/dotdrop#172]
Dotdrop version (and git commit if run from source): v0.29.3
Using dotdrop from AUR

Normally if you install a dotfile (overwrite target file, not symlink) and it's identical, dotdrop won't report it as "installed", i.e. the output is `0 dotfile(s) installed.`

However, if symlinking and the target has already been installed to, dotdrop will report
`1 dotfile(s) installed.` even if dotdrop has successfully installed it in the past.

This is confusing because I'm not sure how many dotfiles have changed after running `dotdrop install` when I symlink a lot of dotfiles.

With `config.yaml`
```
config:
  dotpath: .

dotfiles:
  aliases:
    dst: /tmp/blah
    link: nolink

profiles:
  user:
    - aliases
```

Run `dotdrop install -p user` to see `1 dotfile(s) installed.` as expected.
Run it again to see `0 dotfile(s) installed.` as expected.

Now remove /tmp/blah and replace `link: nolink` with `link: link`

Run `dotdrop install -p user` to see `1 dotfile(s) installed.` as expected.
Run it again to see `1 dotfile(s) installed.` which is wrong. It should be `0 dotfile(s) installed.`
With `-V`:
```
[DEBUG][dotdrop.dotdrop.main] running cmd: install
[DEBUG][dotdrop.templategen.__init__] template additional variables: {'profile': 'user', '_dotdrop_dotpath': '/tmp', '_dotdrop_cfgpath': '/tmp/config.yaml', '_dotdrop_workdir': '/home/aeubanks/.config/dotdrop'}
[DEBUG][dotdrop.dotdrop.cmd_install] execute profile pre actions
[DEBUG][dotdrop.dotdrop.cmd_install] installing key:"aliases", src:"/tmp/aliases", dst:"/tmp/blah", link:"link"
[DEBUG][dotdrop.installer.link] link /tmp/aliases to /tmp/blah
[DEBUG][dotdrop.installer._link] ignoring "/tmp/blah", link already exists
[DEBUG][dotdrop.dotdrop.cmd_install] execute profile post actions
```

Maybe this should be `return False, None`?
https://github.com/deadc0de6/dotdrop/blob/8902cd3cf43f717e794a920cafd4bcc7e213c831/dotdrop/installer.py#L217

**Comment by deadc0de6** [comment]
You're absolutely right, thanks for reporting this!
It is fixed on master.
:+1:

**Comment by aeubanks** [comment]
Awesome, thanks!
