### ISSUE TITLE
Update functionality stopped working

### ISSUE THREAD

**Issue by nostdm** [deadc0de6/dotdrop#175]
In the past I've been able to do `dotdrop update <dir/file>` on a managed directory or file and `dotdrop` would update that file/dir from the file on disk -> managed repo if there were any changes to those files.

I recently updated to the latest version of `dotdrop` (0.29.3) and when I do `dotdrop update <dir/file>` it takes a bit of time, shows no errors but doesn't update anything (i.e. the local and managed files are still different).

P.S. The verbose output is quite noisy and it's hard to make out if there's been any warnings or errors in the process of updating.

**Comment by nostdm** [comment]
It seems that I can now use `dotdrop import <dir/file>` and it will prompt whether I want to override the existing files (also shows diff) - that makes it very similar to how `update` used to work, is that the indended behaviour?

**Comment by deadc0de6** [comment]
What version are you using (as submodule, pypi, other ...)?

I'm unable to reproduce:
```bash
$ cat ~/.test
original
$ ./dotdrop.sh import ~/.test
	-> "/home/user/.test" imported

1 file(s) imported.
$ echo 'modified' > ~/.test
$ ./dotdrop.sh update ~/.test
Overwrite "/home/user/dotdrop/dotfiles/test" with "/home/user/.test"? [y/N] ? y
	-> "/home/user/dotdrop/dotfiles/test" updated
```

Does the above work for you? Can you provide me with a more precise description of your use-case so I can try to reproduce?

The debug logs are indeed noisy but can be quite helpful to identify the issue. If you feel like it, you can always attach those.

**Comment by deadc0de6** [comment]
`import` could create a new entry in the config if it is not able to match the path while `update` won't (and this is only one of the *side-effects* of using `import` in place of `update`. I'd suggest to keep using `update`.

**Comment by nostdm** [comment]
You're right, doing `dotdrop import` creates a new entry in the config file.
I think I've figured out the issue. The update command now expects a full path to the file/directory.
For example, doing `dotdrop update ./.test` or `dotdrop update .test` no longer work while doing `dotdrop update ~/.test` or `dotdrop update /home/user/.test` both work.

**Comment by deadc0de6** [comment]
Relative path should be working but I'm guessing you are using the pypi version, are you?
I'll soon release a new version on pypi. Can you however test with the git version?

**Comment by nostdm** [comment]
I'm using the AUR version which pulls from git.
Has the following dependencies: `python` `python-setuptools` `python-jinja` `python-docopt` `python-ruamel-yaml`

**Comment by deadc0de6** [comment]
I'm unfortunately unable to reproduce the issue with relative path:
```bash
$ echo 'test' > .test
$ ./dotdrop.sh import .test
	-> ".test" imported
$ echo 'new' > .test
$ ./dotdrop.sh update .test
Overwrite "/home/user/dotdrop/dotfiles/dotdrop/.test" with ".test"? [y/N] ? y
	-> "/home/user/dotdrop/dotfiles/dotdrop/.test" updated
```

Does the above test work for you? What is the specific setup when relative update doesn't work?

**Comment by davla** [comment]
I don't know if this is related, but I also had a similar issue which was due to *my* setup.

I can see that @nostdm uses something like `dotdrop update ~/.test`, which is what I do. In my case `dotdrop` is a wrapper script ([available here](https://github.com/davla/custom-commands/blob/d9a8f10/user/dotdrop)) that `cd`s into the dotfiles directory and executes the bash script. You can see here https://github.com/davla/custom-commands/blob/d9a8f10/user/dotdrop#L53-L56 that I explicitly turn paths to absolute, as relative paths won't work after `cd`ing.

I know it's a peculiar situation, but maybe it's a pointer in the right direction :smile:

**Comment by nostdm** [comment]
@deadc0de6 The above test doesn't work for me. It doesn't update anything as I pointed out in the debug log above. For now I'm using absolute paths with `dotdrop update $PWD/.test` and everything seems to work. I don't have the time to debug things further so feel free to close the issue.

**Comment by deadc0de6** [comment]
Ok, well if you provide me with more info (debug logs, a minimal setup, etc) I can try to help but without it, it's difficult for me.
Happy to re-open if you can provide more info.
