### ISSUE TITLE
[bug] `IsADirectoryError` when installing a directory with showdiff

### ISSUE THREAD

**Issue by Maelan** [deadc0de6/dotdrop#179]
Dotdrop version: v0.29.4 commit 709cde1
Using dotdrop: as a submodule, with Python 3.7

**Describe the bug**

When installing a dotfile with the option `showdiff` set to `true` and the destination path is a directory, then Python fails with `IsADirectoryError`. This happens for example when trying to overwrite a pre-existing directory with one from dotdrop’s dotfiles.

**Steps to Reproduce**

1. Create a dotfile `d_test` in the config file (see below).
2. Mkdir the source of the dotfile.
2. Touch (or mkdir) the destination of the dotfile.
3. Run `./dotdrop.sh install d_test`.
4. See error.

**Expected behavior**

Do not fail. Print the same thing as `./dotdrop.sh compare d_test`, ie. compare source and destination recursively if both are directories (or symlinks to it), or say that one is a directory and the other is not. Then go on with subsequent operations.

**Additional information**

The relevant part of the config file:
```yaml
config:
  showdiff: true
dotfiles:
  d_test:
    dst: ~/test
    src: test
    link: link
…
```

Dotdrop's error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/me/dotfiles/dotdrop/dotdrop/dotdrop.py", line 666, in <module>
    if main():
  File "/home/me/dotfiles/dotdrop/dotdrop/dotdrop.py", line 620, in main
    ret = cmd_install(o)
  File "/home/me/dotfiles/dotdrop/dotdrop/dotdrop.py", line 127, in cmd_install
    actionexec=pre_actions_exec)
  File "/home/me/dotfiles/dotdrop/dotdrop/installer.py", line 126, in link
    return self._link(src, dst, actionexec=actionexec)
  File "/home/me/dotfiles/dotdrop/dotdrop/installer.py", line 222, in _link
    with open(src, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/home/me/dotfiles/dotfiles/test'
```

By the way, the behaviour is also buggy when the source is a regular file and the target is a directory. In that case:

```
$ ./dotdrop.sh compare d_test

=> compare d_test: diffing with "/home/me/test"
diff: /home/me/test/test: No such file or directory


$ ./dotdrop.sh install d_test

diff "/home/me/dotfiles/dotfiles/test" VS "/home/glen/test"
diff: /home/me/test/dotdrop-g1m3jh2f: No such file or directory
Remove "/home/me/test" for link creation? [y/N] ? 
```

**Comment by deadc0de6** [comment]
Thanks for reporting this. It should be fixed with above commit, please let me know if you have any other issues.

**Comment by Maelan** [comment]
This fixed the bug indeed, thanks!
