### ISSUE TITLE
Running an action before a dotfile is installed

### ISSUE THREAD

**Issue by TLATER** [deadc0de6/dotdrop#18]
Hi, I'm struggling to use dotdrop for my emacs setup, I use the following configuration helper, which is required for my setup: https://github.com/bbatsov/prelude.

The installer for that helper does the following:

1. Move `~/.emacs.d/` (the relevant dotfile dir) to `~/.emacs.d.bak/`
2. Install a whole bunch of new files in `~/.emacs.d/`

Obviously this means that any dotfiles dotdrop attempts to install are overwritten immediately when it runs an install action for this.

Copying files into this directory immediately after the installer ran would solve this issue, is this possible, or would you accept a PR for this?

**Comment by deadc0de6** [comment]
Hello,
I don't know prelude but what about something like the following action ?

```
actions:
  prelude: <whatever-prelude-command-you-use> && mv ~/.emacs.d.bak/* ~/.emacs.d/
```

**Comment by TLATER** [comment]
Hrm, yeah, that works. Unfortunately the full command starts to look something like this:

```yaml
action:
    prelude: wget <install_script> && chmod +x <install_script> && bash <install_script> && mkdir -p /tmp/extr && tar -C /tmp/extr -xf ~/.emacs.d.tar.gz && mv /tmp/* ~/.emacs.d && rm -r /tmp/extr
```

I'm sure the tar command could be shortened a bit and I could pipe to bash if I *really* wanted to, but this is still pretty long... Is there any way to split that up a bit?

**Comment by deadc0de6** [comment]
well one way would be to store all that in a separate bash script and call that script in the action.

One note though, is running all that really needed everytime you change one dotfile ? This oneliner looks like you are fully reinstalling prelude or whatever `<install_script>` is .. I don't know much about prelude though so discard this remark if not applicable.
