### ISSUE TITLE
[feature] remove all dotdrop backups

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#180]
As the description from [options.py](https://github.com/deadc0de6/dotdrop/blob/9181405207d956e58cf152feb091733cf3fe85b3/dotdrop/options.py#L68), there is no way to not make a copy when install a dot file when I wanna cover the old one.

So, how about add a operation to remove all dotdropbacks? So, if I want remove a dotdropback no need to find it then remove, all I need to do is just do that operation.

**Comment by deadc0de6** [comment]
Not sure to understand exactly what you want but you can easily remove dotdrop backup files with basic unix tools, for example:
```bash
find ${HOME} -iname '*.dotdropbak' -exec rm {} \;
```

**Comment by roachsinai** [comment]
Yes, the command do what I need.

But, as there is `dotdrop listfiles` could all dotfiles managed by dotdrop, maybe follow the output of `dotdrop listfiles` to check whether having a corresponding backup file then delete it will be more quick.

**Comment by deadc0de6** [comment]
The command `listfiles` doesn't actually browse the filesystem, it simply parse the config file and *pretty-print* the different dotfiles registered for a specific profile.

If you don't want the backup files anymore, you can simply disable the `backup` entry in the config (`backup: false`) and remove the existing ones with the above `find` command. I don't understand why adding a dotdrop dedicated command for that would be faster. But maybe I'm not understanding correctly your problem.

**Comment by roachsinai** [comment]
Hi, I'm back here. I have config `backup: true`. And there will be some `*.dotdropbak` on my filesystem.

What I expected is a dotdrop command delete all these `*.dotdropbak`. As `listfiles` can parse all location where could have a corresponding `dotdropbak`(like I use dotdrop import ~/.vimrc, there maybe a ~/.vimrc.dotdropbak file). And if I didn't import ~/.zshrc, there must no file ~/.zshrc.dotdropbak.

So I think if I want to remove all dotdrop backups, no need to traverse all filesystem.

And why I use backup cause use `mv ~/.vimrc.dotdropbak ~/.vimrc` can undo quickly.

**Comment by deadc0de6** [comment]
you can simply delete all `*.dotdropbak` with the find command
```bash
find ${HOME} -iname '*.dotdropbak' -exec rm {} \;
```

I don't think a dedicated command to do just that would add much to dotdrop. Why is the above command not working for you?

**Comment by roachsinai** [comment]
Yeah, `find ${HOME} -iname '*.dotdropbak' -exec rm {} \;` shoud work!

But like I have a global-config.yaml, contains file located at `/etc`, `/usr`, `/opt`, just simple do `find / -iname '*.dotdropbak' -exec rm {} \;` will traverse the whole disk. As `listfiles` know their location, I think no need to traverse it.

**Comment by deadc0de6** [comment]
well as you said you have them all through the `files` command (btw `listfiles` got replaced with `files`) so you could potentially do something like this
```bash
## this gives you the list of dotfiles in the filesystem
dotdrop files -G 2>/dev/null | cut -f2 -d',' | sed 's/^.*://g'
```
you could then easily loop through that list and remove the `.dotdropbak` if it exists.

**Comment by roachsinai** [comment]
Thanks for that! :)
