### ISSUE TITLE
[bug] `install` always report 1 dotfile installed when using `link_children`

### ISSUE THREAD

**Issue by Maelan** [deadc0de6/dotdrop#183]
Dotdrop version: v0.29.4 (commit 9181405)

**Describe the bug**

`install`ing a dotdir with the option `link_children` always report that exactly 1 dotfile has been installed, regardless of what has been actually done. 

**Steps to Reproduce**

 1. Create a dotdir with (say) three files a, b, c.
 1. Set up this dotdir with the option `link: link_children`.
 1. Run `./dotdrop.sh install` several times to see what happens in several scenarios (initial installation, no change, some children need to be created).
 1. Observe that dotdrop always report “1 dotfile(s) installed”, regardless of what has been done (or if anything has been done at all).

**Expected behavior**

Two possible behaviors:

  * regard the dotdir as a single file: report 1 when the target directory is created or when one of its children is changed;
  * regard the dotdir as a bunch of files: report the number of changed children (plus 1 for the creation of the target directory, optionally).

**Additional information**

Relevant config:
```yaml
dotfiles:
  test:
    dst: ~/test
    src: test
    link: link_children
```

Example run:

```console
$ ./dotdrop.sh install
	-> creating directory "/home/me/test"
	-> linked /home/me/test/a to /home/me/dotfiles/dotfiles/test/a
	-> linked /home/me/test/b to /home/me/dotfiles/dotfiles/test/b
	-> linked /home/me/test/c to /home/me/dotfiles/dotfiles/test/c
1 dotfile(s) installed.

$ ./dotdrop.sh install
1 dotfile(s) installed.

$ rm ~/test/{b,c}

$ ./dotdrop.sh install
	-> linked /home/me/test/b to /home/me/dotfiles/dotfiles/test/b
	-> linked /home/me/test/c to /home/me/dotfiles/dotfiles/test/c
1 dotfile(s) installed.
```

**Comment by deadc0de6** [comment]
Thanks for reporting this bug. It should be fixed with above commit.

**Comment by Maelan** [comment]
I can confirm.
