### ISSUE TITLE
[help] Manage config files from /etc

### ISSUE THREAD

**Issue by dhruvinsh** [deadc0de6/dotdrop#185]
**What I am trying to achieve**
I understand the meaning of the dotfiles, but if i want to manager config files from /etc folder like lightdm.conf, pacman.conf is it possible to do with dotdrop?

**What I have tried so far**
sorry i haven't tried dotdrop yet, i am using dotbot for long time, which i recently pushed to my repo.

**Comment by deadc0de6** [comment]
Of course you can use dotdrop to manage system *dotfiles*. There's a small documentation on the wiki [here](https://github.com/deadc0de6/dotdrop/wiki/global-config-files). However as mentioned in the wiki page, the user and system dotfiles should be kept separately to avoid any rights/ownership issues.

You can also have a look on how @davla did it, which is pretty neat: https://github.com/davla/dotfiles

If anything is unclear, please let me know

**Comment by dhruvinsh** [comment]
Thanks for your support!
