### ISSUE TITLE
Prevent a file from being installed in a directory dotfile

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#188]
This is not really a request for help, as I found a solution, but it's mostly curiosity :smile: 

### The problem
I have a directory dotfile, namely `~/.config/gtk-3.0`. In this directory, I have these files:
```
.config/gtk-3.0
├── settings.ini.lodpi
├── settings.ini.hidpi
└── settings.ini
```
`settings.ini.lodpi` and `settings.ini.hidpi` just define some variables and then include `settings.ini` which uses those variables:
```
# settings.ini.hidpi
{%@@ set cursor_size = 48 @@%}
{%@@ include 'settings.ini' @@%}
```
```
# settings.ini
[Settings]
gtk-cursor-theme-size = {{@@ cursor_size @@}}
```
I would like `settings.ini` not to be installed when I install the `~/.config/gtk-3.0` directory dotfile, as it is used only to avoid code repetition

### The solution
Just turn the whole content of `settings.ini` into a macro,
```
{%@@ macro settings_ini(cursor_size) @@%}
# settings.ini
[Settings]
gtk-cursor-theme-size = {{@@ cursor_size @@}}
{%@@ endmacro @@%}
```
which I import and call in `settings.ini.lodpi` and `settings.ini.hidpi`

### The question
Is there a config YAML key that I miss, or is there really no way to prevent a dotfile from being *installed* as content of a directory dotfile? Like `cmpignore` and `upignore`, for example.

In any case, the macro solution seems cleaner. No "global" variables and clearer code.

**Comment by deadc0de6** [comment]
I like the `macro` idea. It could however become difficult to support if the *shared* part is becoming bigger. Another solution would be to store those *helper* files outside of a managed directory, for example somewhere like `<dotpath>/_helpers/gtk-3.0-settings.ini`. That way they are still tracked within your dotfiles but are not installed and you could use them from within other dotfiles.

No there are currently no config which allows to ignore some file when installing a directory.

**Comment by davla** [comment]
Should we add something in the wiki about this?

**Comment by deadc0de6** [comment]
For the macro part, sure, would you be so kind provide a more complete walkthrough I could use (with examples) to add to the doc? Or directly do a PR on the wiki.

**Comment by davla** [comment]
Sure, I'll PR the wiki ASAP

**Comment by davla** [comment]
Update: I'm working on it. Don't have so much time, and it's ending up being more general, longer (and hopefully more helpful) than expected :smile:

**Comment by davla** [comment]
Here we are:

https://github.com/davla/dotdrop/wiki/sharing-content

I also updated the home page to include a link to this

**Comment by deadc0de6** [comment]
oh nice, thanks a lot for your help. I have copied content in the wiki.
Thanks again, much appreciated :+1:

**Comment by davla** [comment]
You're welcome

**Comment by deadc0de6** [comment]
@davla FYI dotdrop now has a `instignore` config entry that allows to ignore files when installing, for more see [this page of the wiki](https://github.com/deadc0de6/dotdrop/wiki/ignore-pattern).

**Comment by davla** [comment]
Oh, yeah, I saw it :) I check issues and commits here periodically
