### ISSUE TITLE
Installing to a non-existing directory throws a stacktrace

### ISSUE THREAD

**Issue by TLATER** [deadc0de6/dotdrop#19]
While installing a dotfile as a symlink from `~/.config` on a fresh machine without that directory, I got a stacktrace with a `FileNotFoundError`. The cause seems to have been the missing `~/.config` directory.

I think a user would expect either of:

1. A nice error message telling me that I should create the parent directories of any dotfiles I'm installing.
2. Dotdrop creates the relevant directory for me, automagically.

**Comment by deadc0de6** [comment]
Do have the option `create` under the `config` entry in your config file ? 

As mentioned [here](https://github.com/deadc0de6/dotdrop#config-file-details) by setting `create` to `true`, that's exactly what dotdrop should do, create the directory.

**Comment by TLATER** [comment]
Ah, right, sorry, I overlooked that. It might be useful to catch that exception and tell the user about that config option anyway.

**Comment by deadc0de6** [comment]
Which version are you using ? 

Dotdrop should actually output a message when the directory does not exist and `create` is set to `False` like the following:
```
[ERR] creating directory for "/tmp/a/b/c" 
[ERR] installing "dotfiles/tmp/a/b/c" to "/tmp/a/b/c"
```

This is weird as no exception should actually be triggered. Could you give me a minimal walkthrough such that I would be able to reproduce this behavior ?
