### ISSUE TITLE
[feature] default actions for dotfile

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#193]
For now to run actions for every dotdrop install run  - regardless we add new files or not
we had only one option - set pre action in dotfile definition right?
But this action is running multiple times for every dotfile

One ugly solution is to create temporary file for dotfile - then post action will run only once for that file.
Can we add 
default actions but for dotfile definition - that will always run with dotdrop install - once?
even when no new single file is deployed?
regards

**Comment by deadc0de6** [comment]
Doesn't the existing switch `-a` does what you need?

```
-a --force-actions      Execute all actions even if no dotfile is installed.
```

**Comment by deadc0de6** [comment]
@niksfirefly there is already a config option for `default_actions`, allows you to run an action if any dotfiles is being installed for a specific profile.

see https://github.com/deadc0de6/dotdrop/wiki/usage-actions#default-actions

**Comment by niksfirefly** [comment]
Yeah I saw that - very nice addition.
It is running for every dotfiles - my suggestion was to add optional default-actions to every dotfiles.

I am using dotdrop for all defined dotfiles with autodeploy via webhooks from git repo for multiple users.
Assume we got 30 dotfiles with 2 actions each and for 3 different users on every node and 
I must use --force-actions
See my point? :)

regards
