### ISSUE TITLE
[feature] Ignore non-existing external config files (actions, variables)

### ISSUE THREAD

**Issue by Sighery** [deadc0de6/dotdrop#198]
When setting up external config files to import things from, if the file doesn't exist, dotdrop will fail:

```
[DEBUG][dotdrop.cfg_yaml._import_variables] import variables from /home/sighery/Programming/dotfiles/secrets.yaml
[DEBUG][dotdrop.cfg_yaml._import_sub] import "variables" from "/home/sighery/Programming/dotfiles/secrets.yaml"
[ERR] config file error: config path not found: /home/sighery/Programming/dotfiles/secrets.yaml 
```

To explain my current usecase: I have some secret info I need to template in some files. I _could_ use an `.env` file, but that would require modifying how I invoke my commands, and even the wiki recommends using variables. I'd like to keep a git-ignored `secrets.yaml` file, that, if available, will parse variables from, else will do nothing.

Sure, if you reference variables/actions that don't exist because the file doesn't exist, it might fail. But if you try to use an action that you haven't declared in your main config file it will fail regardless, so the behaviour stays the same, whether it's because you didn't import a file, or because the action simply doesn't exist in your main config.

---

I don't know how much sense this would make for other config files, like the importing profiles/dotfiles/configs from other files, but I do see it making sense for the actions/variables imports.

I believe it would require changing the [`_import_variables()`](https://github.com/deadc0de6/dotdrop/blob/v0.30.0/dotdrop/cfg_yaml.py#L535) and [`_import_actions()`](https://github.com/deadc0de6/dotdrop/blob/v0.30.0/dotdrop/cfg_yaml.py#L562) methods, or maybe the underneath methods it calls. I'd change them so that instead of exiting with an exception, it maybe logs a warning and continues importing nothing/empty dict.

If you're okay with this, I could start working on a PR. I just figured I would open an issue to discuss it first rather than doing work and then getting it denied for some reason.

**Comment by deadc0de6** [comment]
Thanks for reporting this. 

I see your point and it makes sense. From my point of view, there are multiple ways of solving this however changing the default is not optimal. For example an non-existing variable used in a template won't be directly noticed but could still trigger some problems.

What about simply adding a global variable in the config to handle that use-case (non-existent imported file). For example an `import_ignore_missing` variable or similar. If set to `true`, any import path that doesn't exist won't be fatal (while still printing a warning).

Another way of doing it would be to specify along each of the import path if it should be ignored in case of error. This could give more control. Something like the below:
```yaml
config:
  import_variables:
  - some_existing_path.yaml
  - some_potentially_non_existing_not_ignored.yaml
  - some_potentially_non_existing_ignored.yaml:ignore
```

I'm open to discuss it. I could also implement that, that's not a problem.

**Comment by Sighery** [comment]
Both solutions look good and would solve my usecase. Now, I don't know how popular this feature might be, but the second option does give you some more options when specifying external files. There might be some that you might want to always be there and fail if not available, while also having other optional external files that aren't critical. 

So, personally I'd go for the second option, but you're the creator so whatever you pick is fine by me.

**Comment by deadc0de6** [comment]
Ok, I'll look into it and will let you know when I have something. I'm also in favor of the second option.

**Comment by deadc0de6** [comment]
I implemented solution 2 in branch [ignore_not_existing](https://github.com/deadc0de6/dotdrop/tree/ignore_not_existing). Can you give it a try?

It allows to append `:ignore` at the end of an imported paths (for `import_variables`, `import_configs` and `import_actions`) to make it non fatal in case the path doesn't exist.

```yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
  import_variables:
  - /variables/does/not/exist:ignore
  import_actions:
  - /actions/does/not/exist:ignore
  import_configs:
  - /configs/does/not/exist:ignore
...
```

TBH I'm not convinced of the keyword `:ignore` so if you have any suggestion on a better way of doing this, let me know.

**Comment by Sighery** [comment]
`:optional` and `:necessary`/`:needed` might be better terms in this case. Although looking at the code doesn't seem like there's an explicit necessary keyword. Not that it's needed.

However, give me a second, there's some code that can potentially be buggy. I believe I can leave a commend directly on the code for the commit.

**Comment by Sighery** [comment]
> `:optional` and `:necessary`/`:needed` might be better terms in this case. Although looking at the code doesn't seem like there's an explicit necessary keyword. Not that it's needed.
> 
> However, give me a second, there's some code that can potentially be buggy. I believe I can leave a comment directly on the code for the commit.

Comment added: https://github.com/deadc0de6/dotdrop/commit/35ebd2b43a745a7f2c5a04ad413bf53f335cd5fe#r36594194

**Comment by deadc0de6** [comment]
Good point, I'll fix this, thanks!

**Comment by Sighery** [comment]
I'll keep an eye on it to give it a try once it's updated :+1:

**Comment by deadc0de6** [comment]
I updated the code and renamed *ignore* to *optional*. Thanks for your help!

**Comment by Sighery** [comment]
Just tried it and it works great. But now the wiki requires updating: https://github.com/deadc0de6/dotdrop/wiki/config#import-variables-from-file

I don't believe I can send a PR for the wiki, however.

**Comment by deadc0de6** [comment]
Sure I'll update the wiki when I merge the branch.
Ok sounds good, I'll merge that in the coming days in master and will release a new version.
Thanks again for your help!

**Comment by deadc0de6** [comment]
These changes have been merged into the master branch and the doc was updated.
Thanks!
