### ISSUE TITLE
/bin/bash does not work on NixOS

### ISSUE THREAD

**Issue by ashyon** [deadc0de6/dotdrop#2]

**Comment by deadc0de6** [comment]
Hello,
Thanks for reporting this.
I made it more generic and moved to `/bin/sh` (2c052f8b9767a64878f52b408a360fb772e4e792)
Does that work for you ?

**Comment by ashyon** [comment]
`/bin/sh` is a symlink on NixOS. not sure if it's the preferred method or not but it will definitely work.

**Comment by deadc0de6** [comment]
I think it's a symlink on most major distribs. Thanks
