### ISSUE TITLE
Transformation and dotfiles with templates

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#200]
My use case here is very simple: I'd like to apply a transformation on a dotfile _after_ the jinja template has been expanded, but dotdrop just does it _before_.

Even though it should not be difficult to implement, I'm not sure that implementing it is the best solution in the first place. You definitely don't want to break the existing functionality, so there will likely be a configuration option somewhere for _when_ the transformation should be applied, and it will quickly become a mess (given that transformation can be pretty complex beasts already).

So the best solution might be just not to support this _when_ option, given that no one has complained before except for me. In this case, it should be stated clearly in the documentation (unless it already is and I'm blind)

**Comment by deadc0de6** [comment]
The main reason `trans_read` is executed before the templating process is that dotfiles that use `trans_read` are usually somehow stored scrambled and need to be processed before being readable. Think about the use of compression and encryption for example.

```yaml
trans_read:
  gpg: gpg2 -q --for-your-eyes-only --no-tty -d {0} > {1}
  uncompress: "mkdir -p {1} && tar -xf {0} -C {1}"
```

Applying the templating process before the transformation in the above two examples would not work as the files are not templates yet.

I agree this should be documented in the wiki, I'll add that.

However we can probably find a solution for your use-case. We could add a new *transformation* that would happen after the templating, we could also potentially add *pre* and *post* to transformations to control when these happen (similar to your *when*). But before going this way I'd like to better understand what you are trying to achieve. Can you provide me with more info on your use-case?

**Comment by davla** [comment]
_pre_ and _post_ keys that mirror actions is a very good idea!

So, my use-case is the following:

In [this dotfile](https://github.com/davla/dotfiles/blob/master/dotfiles/etc/profile.d/env-vars.sh) I have a path starting with `$HOME` on the last line. I want to turn this path to absolute when I use the dotfile for root, as `$HOME` would expand to something else. I use [this transformation](https://github.com/davla/dotfiles/blob/master/transformations/fix-home.sh) that somehow replaces those `$HOME` with the absolute path.

Now, I'd like to store that path on the last line in a variable, so that it can have different values on different hosts. However, this doesn't work, as the transformation operates on the file that still has the jinja markup unexpanded, that contains no `$HOME`.

**Comment by deadc0de6** [comment]
I'm not sure I understand the issue here. I see at least two ways of solving this:
* (1) not using any transformation and directly inserting a jinja directive to replace the path with templating
* (2) replacing `$HOME` with its final value (an absolute path for root and `$HOME` otherwise) directly with the transformation script

But maybe i haven't correctly understand the problem.

# for (1)

untested ...

config.yaml
```yaml
variables:
  root_path: "/some/abs/path"
  user_path: "/home/{{@@ env['USER'] @@}}/other/path"
dynvariables:
  the_path: test "{{@@ env['USER'] @@}}"  = "root" && echo "{{@@ root_path @@}}" || echo "{{@@ user_path @@}}"
```

env-vars.sh
```bash
...
export DOTFILES_HOME="{{@@ the_path @@}}"
```

# for (2)

untested ...

```yaml
trans_read:
  replace_var: "replace_var.sh {0} {{@@ env['USER'] @@}} > {1}"
```

`replace_var.sh`
```bash
#!/bin/bash
if [ "$2" = "root" ]; then
  sed -i "s/\$HOME/somepath/g" $1
fi
```

env-vars.sh
```bash
...
export DOTFILES_HOME="$HOME/Files/Programming/sys/dotfiles"
```

**Comment by davla** [comment]
I do the second, it a bit of a convoluted way :smile:

I think the best option would actually be to use a jinja filter for this directly in the dotfile. Something along the lines of:

```bash
export DOTFILES_HOME="{{@@ '$HOME/Files/Programming/sys/dotfiles' | patch_home @@}}"
```
This would require the addition of a custom filter though. Is it already possible? If not. does it sound like a good idea?

**Comment by deadc0de6** [comment]
Currently [custom filter](https://jinja.palletsprojects.com/en/2.10.x/api/#writing-filters) are not directly supported. But It would not be difficult to add some as I did for [methods](https://github.com/deadc0de6/dotdrop/wiki/templating#available-methods).
However the issue here is your `patch_home` is very specific. What I could do is add a way to *load* through a command line switch a python file containing filters to load in the templating engine. 

But before considering that, why not use something like this:
```bash
{%@@ if env['USER'] == "root" @@%}
export DOTFILES_HOME="/some/path/dotfiles"
{%@@ else @@%}
export DOTFILES_HOME="$HOME/Files/Programming/sys/dotfiles"
{%@@ endif @@%}
```

**Comment by davla** [comment]
> Currently [custom filter](https://jinja.palletsprojects.com/en/2.10.x/api/#writing-filters) are not directly supported. But It would not be difficult to add some as I did for [methods](https://github.com/deadc0de6/dotdrop/wiki/templating#available-methods).
> However the issue here is your `patch_home` is very specific. What I could do is add a way to _load_ through a command line switch a python file containing filters to load in the templating engine.

Yes, this is what I meant with "custom filter". "User-defined filters" would be a better name, actually.
 
> But before considering that, why not use something like this:
> 
> ```shell
> {%@@ if env['USER'] == "root" @@%}
> export DOTFILES_HOME="/some/path/dotfiles"
> {%@@ else @@%}
> export DOTFILES_HOME="$HOME/Files/Programming/sys/dotfiles"
> {%@@ endif @@%}
> ```
What the transformation achieves is not to have a _different_ path for the root user. What the transformation does is to have the _same_ path for the root user, but with `$HOME`replaced by `/home/myuser`. Indeed, it uses `find /` to locate the path on the whole filesystem.

This is necessary as `$HOME` expands to `/root` for root, rather than `/home/myuser`. Providing a different path manually every time is a bit cumbersome (even thoufh I should probably refactor my dotfiles to avoid this kind of atrocities :nauseated_face:)

**Comment by deadc0de6** [comment]
I just added the ability to add a list of files to load templating functions and filters from.
See the config entry `func_file` and `filter_file` in the [config doc](https://github.com/deadc0de6/dotdrop/wiki/config#format) as well as the [available methods doc](https://github.com/deadc0de6/dotdrop/wiki/templating#available-methods) and [available filters doc](https://github.com/deadc0de6/dotdrop/wiki/templating#available-filters).

This should allow you to use custom filters:

```yaml
config:
  filter_file:
  - /tmp/myfilter_file.py
```

`/tmp/myfilter_file.py`
```python
def patch_home(arg1):
  return "something clever
```

dotfile content
```bash
export DOTFILES_HOME="{{@@ '$HOME/Files/Programming/sys/dotfiles' | patch_home @@}}"
```

**Comment by davla** [comment]
Great! Thanks :+1:

**Comment by davla** [comment]
I confirm that this works. Thanks, this one was truly amazing!
