### ISSUE TITLE
[bug] user-defined filters not working in imported config files

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#204]
Dotdrop version (and git commit if run from source): d242742 (current master)
Using dotdrop: as subtree (source)

---

User-defined jinja filters (`filter_file` key) are not part of the jinja environment when listed in imported config files. Dotdrop crashes with the following exception:
```shell
jinja2.exceptions.TemplateAssertionError: no filter named XXX
```

The user-defined filters are only used in dotfiles belonging to the sub-config, whereas those listed in the top-level config-file don't need the filters. Hence, the problem is not that the filter definitions don't propagate upwards to the top level, but rather that they are not loaded in the jinja environment.

---

I hotfixed the issue locally by patching `CfgYaml._import_config` with these lines, that augment the settings dictionary with the sub-config filter files:
```python
self.settings[Settings.key_func_file] += [
    self._norm_path(func_file)
    for func_file in sub.settings[Settings.key_func_file]
]
self.settings[Settings.key_filter_file] += [
    self._norm_path(func_file)
    for func_file in sub.settings[Settings.key_filter_file]
]
```
These makes the sub-config filter files available in `Options._read_config`, so that they are passed on correctly to `Templategen`. 

Nonetheless, I'm quite sure this is not the most appropriate solution. Maybe a dedicated field in `CfgYaml` would be better, or something in `CfgAggregator`. Depending on how big the best solution is, I might be able to do something this weekend.

**Comment by deadc0de6** [comment]
Thanks a lot for your help, that was helpful. I added your code to the `CfgYaml._import_config` and implemented two more tests for the `func_file` and `filter_file` from external config file.

Should be fixed now. Thanks again!

**Comment by davla** [comment]
Works as intended. Closing this, then.
