### ISSUE TITLE
[feature] xdg shorthand in paths

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#207]
## Short description

XDG paths available as environment variables (eg. `$XDG_CONFIG_HOME` and `$XDG_DATA_HOME`) would have shorthands in paths around dotdrop (like `src` and `dst` in dotfiles entries in YAML files). Something like `{xdg_config}/git/config`.

## Rationale

Well, dotdrop is a configuration files management tool. Many of them end up in `$XDG_CONFIG_HOME` (`~/.config` by default). One could use dynamic variables and dynamic dotfile paths, but this leads to:

- Defining the dynamic variables in every configuration file
- Or alternatively, a complex variables files setup with convoluted imports
- Plus, the syntax `{{@@ xdg_config @@}}/git/config` is a little cumbersome :stuck_out_tongue_closed_eyes: 

Given that the use of XDG paths is so common, it makes sense to treat this case in a special, user-friendly way. 

## Implementation

With the suggested syntax, the implementation could be as easy as
```python
path = '{xdg_config}/git/config'
path = path.format(xdg_config=os.environ.get('XDG_CONFIG_HOME'))
```
I don't know, however, in how many different places the code should be updated to achieve this, so it might end up being a pretty big task.

As usual, I'm willing to PR if you give me some hints about where to look in the code :smiley:

**Comment by deadc0de6** [comment]
Doesn't the existing environment variable syntax work for you:
```yaml
dst: "{{@@ env['XDG_CONFIG_HOME'] @@}}/git/config"
```

see <https://github.com/deadc0de6/dotdrop/wiki/config-variables>

As you mentioned, you could always use dynamic variables and such.

Or even define your own functions/filters (see [templating methods](https://github.com/deadc0de6/dotdrop/wiki/templating#available-methods) and [templating filters](https://github.com/deadc0de6/dotdrop/wiki/templating#available-filters))

**Comment by davla** [comment]
Oh, I didn't know that the full template syntax is allowed in dotfiles `src` and `dst` entries. I thought only dotdrop variables were expanded :sweat_smile: 

Well, then I guess the current syntax is friendly enough to make any fancy improvement not worth. If I want something more concise, l'll hack it myself in.
