### ISSUE TITLE
[bug] `diff-cmd.sh` test fails

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#213]
During my work for #212 I noticed that the test `diff-cmd.sh` fails. It fails as early as line 104, "comparing with unified diff". It's very likely something on my system, but it's still worth reporting. This is the content of the two diff files:

${tmpd}/unified
```
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.32.0
                               |_|

1c1
< modified
> original
```
${tmpd}/real
```
1c1
< modified
> original
1,6d0
<      _       _      _
<   __| | ___ | |_ __| |_ __ ___  _ __
<  / _` |/ _ \| __/ _` | '__/ _ \| '_ |
<  \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.32.0
<                                |_|
< 
```

**Comment by deadc0de6** [comment]
Line 104 is a simple `diff` so I would suppose you have an alias on `diff`, can you try `alias diff`?

**Comment by davla** [comment]
No, I have no alias. If it works on your machine, then I'll just ignore it.

**Comment by deadc0de6** [comment]
Yes it works on my machine and it also works on travis.
what is weird is I have quite a different content from what you have in the files:

unified/real
```
1c1
< modified
> original
```

I'm wondering why you have the banner in these files? I could admit for the `unified` one since it's generated by dotdrop but the `real` is created using `diff` on a file created with `echo "modified" > ${tmpd}/singlefile` so it doesn't really make sense.

**Comment by deadc0de6** [comment]
can you try the following:
```
export DOTDROP_NOBANNER=yes
test-ng/diff-cmd.sh
```

**Comment by davla** [comment]
So, it was the banner.

It's not grepped out in `unified` so it's there, but it's not there in `real`, as it's generated by the standard UNIX tool. Then. `diff` on line 104 displays it.

I'm working with figuring out why the banner is not grepped out

**Comment by davla** [comment]
Well, it turns out that in the second `diff`, on line 104, is lacking the process substitution with `tail -2`, which strips the header out.

Also, unified and normal diffs are swapped

**Comment by deadc0de6** [comment]
Right, it's because the default `diff` in dotdrop change from *normal* to *unified*. However I still wonder why this pass the tests on travis, anyway, thanks again for your help!

**Comment by davla** [comment]
It might be because of the environment. If the `DOTDROP_NOBANNER` variable is set, then it skips the banner.

But I cannot check this. Feel free to keep this open, if you want to investigate, otherwise you can close, as far as I'm concerned
