### ISSUE TITLE
[wiki update] wiki for link_children.

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#216]
The wiki for `link_childre` not worked right now: https://github.com/deadc0de6/dotdrop/wiki/symlinked-dotfiles#link-children

In that page it shows :

```
config:
  dotpath: dotfiles
vim:
  dst: ~/.vim/
  src: vim
  link: link_children
```

but it should be:

```
config:
  dotpath: dotfiles
dotfiles:
  d_vim:
    src: vim
    dst: ~/.vim
    link: link_children
```

Didn't find way to update the wiki, so make an new issue.

**Comment by roachsinai** [comment]
Same with `link`, need update.

**Comment by deadc0de6** [comment]
thanks for pointing that out, fixed!

**Comment by roachsinai** [comment]
Hi, but I get some info says not all subdirectories are imported to directory vim when use dotdrop compare:

```
=> compare d_vim: diffing with "/home/roach/.vim"
=> "autoload" does not exist in dotdrop
=> "black" does not exist in dotdrop
=> "pack" does not exist in dotdrop
=> "plugged" does not exist in dotdrop
=> "tasks.ini" does not exist in dotdrop
```

**Comment by deadc0de6** [comment]
Can you please give me more info:

* what command doesn't work and what was its output (with debug symbols with `--verbose`)
* a `tree` view of `/home/roach/.vim`
* a `tree` view of the imported vim directory in your *dotpath*

**Comment by roachsinai** [comment]
Yeah, here you are.

```
hmank ~ » dotdrop compare                
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.32.0
                               |_|

=> compare d_vim: diffing with "/home/roach/.vim"
=> "autoload" does not exist in dotdrop
=> "black" does not exist in dotdrop
=> "pack" does not exist in dotdrop
=> "plugged" does not exist in dotdrop
=> "tasks.ini" does not exist in dotdrop
hmank ~ » tree ~/.vim -L 1          
/home/roach/.vim
├── autoload
├── black
├── pack
├── plugged
├── snips -> /home/roach/code/Git/dotfiles/dotfiles/vim/snips
└── tasks.ini

5 directories, 1 file
hmank ~ » z /home/roach/code/Git/dotfiles/dotfiles 
hmank ~/c/G/d/dotfiles master » tree vim -L 1  
vim
└── snips

1 directory, 0 files
hmank ~/c/G/d/dotfiles master » 
```

**Comment by deadc0de6** [comment]
Thanks but I meant the `import` command output for the `~/.vim` directory since this is were the initial problem occurs as those directories weren't imported.

You should first remove the `/home/roach/code/Git/dotfiles/dotfiles/vim` from dotdrop and remove the `d_vim` entry (and any reference to it) in your config file.

Then run
```
dotdrop import ~/.vim --verbose
```

**Comment by roachsinai** [comment]
Oh, that not same with what I did. Maybe I did it in a wrong way, I move all directories out of `~/.vim` except `snips`, then I import `~/.vim`. I'll try what you said.

**Comment by roachsinai** [comment]
I follow your instructions I got some no file errors when copy files:

```
[DEBUG][dotdrop.dotdrop.main] running cmd: import
[DEBUG][dotdrop.dotdrop.cmd_importer] trying to import /home/roach/.vim
[DEBUG][dotdrop.dotdrop.cmd_importer] new dotfile: src:vim dst:/home/roach/.vim
[DEBUG][dotdrop.dotdrop.cmd_importer] will overwrite: True
[DEBUG][dotdrop.utils.run] exec: mkdir -p /home/roach/code/Git/dotfiles/dotfiles
[DEBUG][dotdrop.utils.run] exec: cp -R -L /home/roach/.vim /home/roach/code/Git/dotfiles/dotfiles/vim
[ERR] "cp -R -L /home/roach/.vim /home/roach/code/Git/dotfiles/dotfiles/vim" returned non zero (1): cp: 无法获取'/home/roach/.vim/plugged/black/docs/authors.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/blackd.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/change_log.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/contributing_to_black.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/editor_integration.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/ignoring_unmodified_files.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/installation_and_usage.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/license.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/pyproject_toml.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/show_your_style.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/testimonials.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/the_black_code_style.md' 的文件状态(stat): 没有那个文件或目录
cp: 无法获取'/home/roach/.vim/plugged/black/docs/version_control_integration.md' 的文件状态(stat): 没有那个文件或目录 
[ERR] importing "/home/roach/.vim" failed! 
```
Those files are belong to project https://github.com/psf/black. The reason is they are soft link files.

```
hmank ~ » cd  /home/roach/.vim/plugged/black/docs/
hmank ~/./p/b/docs master » ls
authors.md     contributing.md           ignoring_unmodified_files.md  make.bat           requirements.txt    the_black_code_style.md
blackd.md      contributing_to_black.md  index.rst                     Makefile           show_your_style.md  version_control_integration.md
change_log.md  editor_integration.md     installation_and_usage.md     pyproject_toml.md  _static
conf.py        environment.yml           license.md                    reference          testimonials.md
hmank ~/./p/b/docs master » la
总用量 36K
lrwxrwxrwx 1 roach roach   27  4月 23  2019 authors.md -> _build/generated/authors.md
lrwxrwxrwx 1 roach roach   26  4月 23  2019 blackd.md -> _build/generated/blackd.md
lrwxrwxrwx 1 roach roach   30  4月 23  2019 change_log.md -> _build/generated/change_log.md
-rw-r--r-- 1 roach roach 8.0K 10月 15 08:12 conf.py
lrwxrwxrwx 1 roach roach   18  4月 23  2019 contributing.md -> ../CONTRIBUTING.md
lrwxrwxrwx 1 roach roach   41  4月 23  2019 contributing_to_black.md -> _build/generated/contributing_to_black.md
lrwxrwxrwx 1 roach roach   38  4月 23  2019 editor_integration.md -> _build/generated/editor_integration.md
-rw-r--r-- 1 roach roach  207 10月 22 21:16 environment.yml
lrwxrwxrwx 1 roach roach   45  4月 23  2019 ignoring_unmodified_files.md -> _build/generated/ignoring_unmodified_files.md
-rw-r--r-- 1 roach roach 1.9K  3月 13 22:58 index.rst
lrwxrwxrwx 1 roach roach   42  4月 23  2019 installation_and_usage.md -> _build/generated/installation_and_usage.md
lrwxrwxrwx 1 roach roach   27  4月 23  2019 license.md -> _build/generated/license.md
-rw-r--r-- 1 roach roach  773  4月 23  2019 make.bat
-rw-r--r-- 1 roach roach  602  4月 23  2019 Makefile
```

**Comment by deadc0de6** [comment]
These seems like broken links since the target directory `_build` doesn't seem to exist. I guess by removing these the importation will work.

**Comment by deadc0de6** [comment]
Or you can temporarily move  `/home/roach/.vim/plugged/black/docs` out of there, import `~/.vim` and then add it back.

**Comment by roachsinai** [comment]
Yeah, could you tell me what should I do then?

My config file is like this:

```
config:
  dotpath: dotfiles
dotfiles:
  d_vim:
    dst: ~/.vim/
    src: vim
```

**Comment by deadc0de6** [comment]
Well broken symlinks is not dotdrop's job since in the backend it simply uses `cp` to copy files. So you have two choices, either you fix broken symlinks on the directory you try to import or you exclude them temporarily before importing. I'd better go for fixing broken symlinks but it's up to you.

Here's an example on how to import by temporarily excluding it (hacky):

* remove the `d_vim` entry in your config (and all references to it)
* import
```bash
## remove vim in dotdrop dotpath
rm ~/code/Git/dotfiles/dotfiles/vim
## move docs out 
mv ~/.vim/plugged/black/docs /tmp/
## import
dotdrop import ~/.vim --verbose
## move docs back in
mv /tmp/docs ~/.vim/plugged/black/
```

**Comment by roachsinai** [comment]
> Yeah, could you tell me what should I do then?
> 
> My config file is like this:
> 
> ```
> config:
>   dotpath: dotfiles
> dotfiles:
>   d_vim:
>     dst: ~/.vim/
>     src: vim
> ```

Maybe my question is not clear!

Right now, I deleted all the broken symlinks, and `dotdrop import ~/.vim --verbose` is success.

**Comment by roachsinai** [comment]
```
$ readlink -f ~/.vim
~/.vim
$ tree -L 1 ~/.vim
~/.vim
├── after -> ~/.dotfiles/vim/after
├── autoload
├── plugged
├── plugin -> ~/.dotfiles/vim/plugin
├── snippets -> ~/.dotfiles/vim/snippets
├── spell
├── swap
└── vimrc -> ~/.dotfiles/vim/vimrc
```

What's worse, are those directories `autoload plugged spell swap` above (the example in wiki) are same as default files managed by dotdrop, I mean could use `dotdrop update, compare`.

I found that I misunderstand the function of `link_childern`.

**Comment by roachsinai** [comment]
In my mind, if d_vim has attribute: link_children, d_vim can have part of sub-directories or files of ~/.vim, like `after plugin snippets vimrc` in wiki example.

Then what need do is make a symlinks for all files under d_vim when exec `dotdrop install`. And I could create new files in ~/.vim but dotdrop only focus what we had in d_vim (or we can say dotdrop will ignore directories hava link_children attribute, as all sub-directories of them install is a symlink), dotdrop will ignore `autoload plugged spell swap`.

Not sure my explanation is easy-understaing.

**Comment by deadc0de6** [comment]
If you want to reproduce the example in the wiki ([here](https://github.com/deadc0de6/dotdrop/wiki/symlinked-dotfiles#link-children)):

(start from a clean slate, remove entries in config and clean the *dotpath*)

first import the entire directory:
```bash
dotdrop import ~/.vim
```

Then remove any files/directories in your `dotpath` under the `vim` directory that you don't want dotdrop to manage. For example
```bash
rm -rf ~/code/Git/dotfiles/dotfiles/vim/{autoload,plugged,spell,swap}
```

and finally change the `link` attribute to `link_children` in the config, something like this
```yaml
dotfiles:
  d_vim:
    dst: ~/.vim/
    src: vim
    link: link_children
```

Now only the remaining directories will be handle by dotdrop (that is for example `after`, `plugin`, `snippet`, etc) while the rest will be ignored during the installation or comparison.

You can also then play with ignore patterns to make sure those don't show up when comparing for example (see [the doc](https://github.com/deadc0de6/dotdrop/wiki/ignore-pattern)).

Obviously, adding afterward any files/directories as direct children of the `~/.vim` directory won't be seen by dotdrop and you'll have to update it in dotdrop.

I hope this answers your questions.

**Comment by roachsinai** [comment]
> Now only the remaining directories will be handle by dotdrop (that is for example `after`, `plugin`, `snippet`, etc) while the rest will be ignored during the installation or comparison.

I did what exactly you said, but have to add `cmpignore` to ignore `autoload,plugged,spell,swap`.

Atually behavior is:

```
=> compare d_vim: diffing with "/home/roach/.vim"
=> "autoload" does not exist in dotdrop
=> "black" does not exist in dotdrop
=> "pack" does not exist in dotdrop
=> "plugged" does not exist in dotdrop
```

**Comment by deadc0de6** [comment]
yeah that's what I meant with

> You can also then play with ignore patterns to make sure those don't show up when comparing for example (see [the doc](https://github.com/deadc0de6/dotdrop/wiki/ignore-pattern)).

**Comment by roachsinai** [comment]
OK, got it, thanks for all your instructions!
