### ISSUE TITLE
[help] Must I remove entire line to comment it?

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#218]
**What I am trying to achieve**

I have a setting to include a file:

`{%@@ include vim_ + '/ycm-utlisnips.vim' @@%}`

And rightnow I want test some setting, I don't want `ycm-utlisnips.vim` be included when install. Must I removed this line?

**What I have tried so far**

I have use `#` in the start of that line but not works.

**Comment by roachsinai** [comment]
Use `{# ... #}` works.

**Comment by roachsinai** [comment]
But will left `{# include vim_ + '/ycm-utlisnips.vim' #}` in vimrc.

**Comment by deadc0de6** [comment]
Either you remove the line entirely or you comment the line with the commenting char corresponding to the final file (if vimrc then comments is double quote `"`). Using `{# ... #}` will simply not be understood by the templating engine (jinja2) and will stay as if it was any other text (see <https://github.com/deadc0de6/dotdrop/wiki/templating> for the list of delimiters understood in dotdrop).

**Comment by deadc0de6** [comment]
you could potentially use `{#@@ ... @@#}` too as this should be understood by the templating engine.

**Comment by roachsinai** [comment]
Thanks a lot! It works.
