### ISSUE TITLE
AUR package for 0.10 results in a package with the version 0.9.2

### ISSUE THREAD

**Issue by open-dynaMIX** [deadc0de6/dotdrop#22]
Thanks for also providing an AUR package!

The version of dotdrop seems to be right, but the package claims to be 0.9.2:

```
$ dotdrop -v
0.10
```
```
$ pacman -Qs dotdrop               
local/dotdrop 0.9.2-1
    Save your dotfiles once, deploy them everywhere
```
The problem seems to be:

```
$ git tag -l | tail -1 | sed 's/^v//g'
0.9.2
```
```
$ git tag -l
v0.10
v0.6
v0.7
v0.7.1
v0.7.2
v0.8.1
v0.8.2
v0.9
v0.9.1
v0.9.2
```

**Comment by open-dynaMIX** [comment]
Sorry to bother you again. I don't think it's a good idea to remove the pkgver() function. Without it, the version is hardcoded in the PKGBUILD, no matter what version the actual code has. As stated [here](https://wiki.archlinux.org/index.php/VCS_package_guidelines#The_pkgver.28.29_function):

```
It is recommended to have following version format: RELEASE.rREVISION where REVISION is a monotonically increasing number that uniquely identifies the source tree (VCS revisions do this).
```

This could be achieved with:
```
pkgver() {
  cd "$pkgname"
  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g;s/^v//g'
}
```
At this time this results in following version:
```
0.10.r5.gbde20cb
```

Aside from that you should suffix the package name with `-git` unless it fetches a specific release.

You could also just have it checkout the latest tag and increase the `pkgver` variable at each release (or just fetch the release without git and provide a checksum). In that case, the `-git` suffix is not needed.

**Comment by deadc0de6** [comment]
Regarding the `-git` version, you're absolutely right, I'll create two packages, one with `-git` with the latest from git and one without that fetches the latest tag (and thus the latest release).

For the `pkgver` function, I did like it however what is the point of having one if you also need to hardcode the `pkgver` variable at each release as stated in the wiki 
```
To use pkgver(), you still need to declare the pkgver variable with the most recent value
```

Should I just add a *fake* version in the `pkgver` variable then ?

My point is either it's automated (using the function) or it is to be updated each time manually (using the variable) but having both is a bit weird to me. Or did I miss something ?

**Comment by open-dynaMIX** [comment]
I'm writing from my phone, please excuse any mistakes.

I'm not experienced in regard to git packages. The way I understand it is, you just set the `pkgver` variable to an initial value. This value is automatically updated using the `pkgver()` function. So there should not be any need to touch the `pkgver` variable anymore, as it's taken care of automatically.

If I'm right, you could set the variable to the version it has at time of pushing the PKGBUILD and then it gets increased automatically.

Again, thanks for your work on this!

**Comment by open-dynaMIX** [comment]
I'm writing from my phone, please excuse any mistakes.

I'm not experienced in regard to git packages. The way I understand it is, you just set the `pkgver` variable to an initial value. This value is automatically updated using the `pkgver()` function. So there should not be any need to touch the `pkgver` variable anymore, as it's taken care of automatically.

If I'm right, you could set the variable to the version it has at time of pushing the PKGBUILD and then it gets increased automatically.

Again, thanks for your work on this!

**Comment by open-dynaMIX** [comment]
I'm writing from my phone, please excuse any mistakes.

I'm not experienced in regard to git packages. The way I understand it is, you just set the `pkgver` variable to an initial value. This value is automatically updated using the `pkgver()` function. So there should not be any need to touch the `pkgver` variable anymore, as it's taken care of automatically.

If I'm right, you could set the variable to the version it has at time of pushing the PKGBUILD and then it gets increased automatically.

Again, thanks for your work on this!

**Comment by open-dynaMIX** [comment]
I'm writing from my phone, please excuse any mistakes.

I'm not experienced in regard to git packages. The way I understand it is, you just set the `pkgver` variable to an initial value. This value is automatically updated using the `pkgver()` function. So there should not be any need to touch the `pkgver` variable anymore, as it's taken care of automatically.

If I'm right, you could set the variable to the version it has at time of pushing the PKGBUILD and then it gets increased automatically.

Again, thanks for your work on this!

**Comment by open-dynaMIX** [comment]
I'm writing from my phone, please excuse any mistakes.

I'm not experienced in regard to git packages. The way I understand it is, you just set the `pkgver` variable to an initial value. This value is automatically updated using the `pkgver()` function. So there should not be any need to touch the `pkgver` variable anymore, as it's taken care of automatically.

If I'm right, you could set the variable to the version it has at time of pushing the PKGBUILD and then it gets increased automatically.

Again, thanks for your work on this!

**Comment by open-dynaMIX** [comment]
I'm writing from my phone, please excuse any mistakes.

I'm not experienced in regard to git packages. The way I understand it is, you just set the `pkgver` variable to an initial value. This value is automatically updated using the `pkgver()` function. So there should not be any need to touch the `pkgver` variable anymore, as it's taken care of automatically.

If I'm right, you could set the variable to the version it has at time of pushing the PKGBUILD and then it gets increased automatically.

Again, thanks for your work on this!

**Comment by deadc0de6** [comment]
Ok, that makes sense.

I have updated the PKGBUILD and created a new version of dotdrop on AUR ([dotdrop-git](https://aur.archlinux.org/packages/dotdrop-git/)). The stable is based on the latest releases (its version will get updated for each new stable release) and the git version is based on the master branch:
* stable from the latest release (tag): https://aur.archlinux.org/packages/dotdrop/ ([PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dotdrop))
* git version: https://aur.archlinux.org/packages/dotdrop-git/ ([PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dotdrop-git))

If you get to try those, let me know if you find anything I should change/improve in the PKGBUILDs.

Thanks again

**Comment by open-dynaMIX** [comment]
Great, thanks! I'm still not in front of a computer atm. I will take a closer look tomorrow evening (UTC +1).

**Comment by open-dynaMIX** [comment]
I found the time to look at it.

Looks good! The only thing I saw was, that you didn't bump the [pkgrel](https://wiki.archlinux.org/index.php/PKGBUILD#pkgrel) variable after updating the PKGBUILD. This was not sooo important in this case, as the resulting packages do not differ, but I'd say it's good practice anyway.

**Comment by deadc0de6** [comment]
cool thanks :+1:
