### ISSUE TITLE
The second alias in the README for using env vars does not work

### ISSUE THREAD

**Issue by open-dynaMIX** [deadc0de6/dotdrop#23]
Actually there are two issues. Just tell me if I should open them separately.

1. When trying to execute `dotdrop` after `eval`, the shell just hangs. I've tested this with bash and zsh. It seems to be some kind of recursion problem, but I didn't look into it a lot. When calling the alias differently (e.g. `dotdrop2`) it works without an issue. I was able to work around this using the full path (`/usr/bin/dotdrop`). Obviously this is not an issue when using dotdrop as a submodule.

2. `~` is not resolved when using the `--cfg` argument.
```
$ dotdrop --cfg=~/dotfiles/config.yaml compare
[ERR] error: config file does not exist
```

My working alias looks like this now:

``` shell
alias dotdrop='eval $(cat ~/dotfiles/env.defaults ~/dotfiles/.env | grep -v "^#") /usr/bin/dotdrop --cfg=${HOME}/dotfiles/config.yaml'
```

**Comment by deadc0de6** [comment]
Thanks for reporting this.

1. It seems the recursion happens due to the use of `eval`. I was able to make it work with `export` instead.
```
alias dotdrop='export $(grep -v "^#" ~/dotfiles/env.defaults ~/dotfiles/.env) && dotdrop --cfg=${HOME}/dotfiles/config.yaml'
```

2. I updated dotdrop to handle tilde for the config path on v0.10.1 (available on git only currently).

If these work for you, I'll release a new version.

**Comment by open-dynaMIX** [comment]
1. `export` did not work for me. Even if it did, I'd still prefer using `eval` so that those variables are only available to dotdrop and do not pollute my env.

2. `~` now works, thanks a lot!

**Comment by deadc0de6** [comment]
ok thanks, I'll update the readme and make it clear than when using dotdrop from pypi or aur, the absolute path to `dotdrop` should be used in the alias.

**Comment by deadc0de6** [comment]
done, new version 0.10.1 is out.

thanks for your help
