### ISSUE TITLE
[bug] User resolution

### ISSUE THREAD

**Issue by ask1234560** [deadc0de6/dotdrop#230]
Dotdrop version (and git commit if run from source): 1.0.0

**Describe the bug**

Suppose i have 2 users, root and john. Then in john i have dotdrop, in this i have backup for /etc/file. Then if i want to install dotdrop using ```sudo dotdrop install``` the dotfiles are installed for the root user not for john.

**Comment by deadc0de6** [comment]
Why is this a bug?
You might want to take a look at the doc related to [system/user dotfiles management](https://github.com/deadc0de6/dotdrop/wiki/global-config-files).

**Comment by ask1234560** [comment]
Thanks, haven't seen that
