### ISSUE TITLE
[help] way to escape {{@@ @@}}

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#232]
**What I am trying to achieve**

I want set several mappings for Vim, like `nmap <leader>id normal! a{%@@ if exists(env[""] + "/") @@%}`. But as `dotdrop` use jinja2 internal, `{%@@` should be escaped.

**What I have tried so far**

use `{% raw %}` tag according to jinja2 document.

```
{% raw %}
        \ [ "home/", 'a{{@@ home_ @@}}/' ],
        \ [ "exists", 'a{%@@ if exists(env['hman_git_folder'] + "/cpython") @@%} ],
        \ [ "env_variable", 'a{{@@ env[""] @@}}' ],
{% endraw %}
```

what I want to get is

```
        \ [ "home/", 'a{{@@ home_ @@}}/' ],
        \ [ "exists", 'a{%@@ if exists(env['hman_git_folder'] + "/cpython") @@%} ],
        \ [ "env_variable", 'a{{@@ env[""] @@}}' ],
```

literally.

But what I got is:

```
+{% raw %}
+        \ [ "home/", 'a/home/roach/' ],
+        \ [ "exists", 'a ],
+        \ [ "env_variable", 'a' ],
+{% endraw %}
```

---

What I alse tried is change `\ [ "home/", 'a{{@@ home_ @@}}/' ],` to `\ [ "home/", 'a{{ "{{" }}@@ home_ @@{{ "}}" }}/' ],` and I got `+            \ [ "home/", 'a{{ "{{" }}@@ home_ @@{{ "}}" }}/' ],`, failed again.

---

So is there a way to make it? Thanks in advanced!

What I did is according to [Template Designer Documentation — Escaping](https://jinja.palletsprojects.com/en/2.11.x/templates/#escaping)

**Comment by roachsinai** [comment]
Wow, maybe I misunderstood the usage of `raw` tag. But is there a way to escape `{{@@`?

**Comment by roachsinai** [comment]
Maybe add a attribute that not use jinja2 for that file or I have to use action to append these content to .vimrc.

**Comment by deadc0de6** [comment]
I haven't tried it but did you try `{%@@ raw @@%}` instead of `{% raw %}`?

**Comment by roachsinai** [comment]
I didn't! And It worked! Thanks a lot!

**Comment by roachsinai** [comment]
While I didn't catch the relationship between dotdrop templete and jinja2, sorry for that! Thanks again.

**Comment by deadc0de6** [comment]
No problem, happy it worked!
