### ISSUE TITLE
[bug] dotdrop update --show-patch  have different file permissions with origin file

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#234]
Dotdrop version (and git commit if run from source): v1.0.0
Using dotdrop: from AUR

**Describe the bug**

Execute the output of `dotdrop update --show-patch` will change the file permissions.

**Steps to Reproduce**

Like I do a dotdrop update to a file templete used I got something like: `diff -u /tmp/dotdrop-_8g02qvo /home/roach/.config/fcitx5/conf/pinyin.conf | patch /home/roach/code/Git/dotfiles/dotfiles/config/fcitx5/conf/pinyin.conf`

I works very well about file contents. But the file permission of `/home/roach/.config/fcitx5/conf/pinyin.conf` is `600`, the file permission of `/home/roach/code/Git/dotfiles/dotfiles/config/fcitx5/conf/pinyin.conf` will be `644`.

**Expected behavior**

Imported files have same file permission with origin file, if not dotdrop install will list that entry.

**Additional information**

Maybe the reason is git only track file executable permission?

**Comment by deadc0de6** [comment]
Thanks for reporting this. It should be fixed with [this commit](6474a48961ef3be0c572b740f2a48834996871b3).

**Comment by roachsinai** [comment]
Thanks a lot for it! And maybe the link you post should change `issue` to `commit`.

**Comment by deadc0de6** [comment]
done ;-)
