### ISSUE TITLE
dotfiles execution in reverse order

### ISSUE THREAD

**Issue by domrim** [deadc0de6/dotdrop#24]
Is there a reason why the dotfiles are returned in reverse order?
I was configuring my dotfiles in the scheme `XX_f_filename` where XX is a two-digit-number, now the highest value gets executed first, which is a very uncommon behaviour.
I fixed the issue for myself. Wouldn't it be logic to make this beaviour default?
I can submit my change as a pull-request if you want.

**Comment by deadc0de6** [comment]
hm my assumption is that this is due to `yaml.load` and the fact dictionary are unordered in python.
Sure submit a PR, I'll have a look. Thanks !

**Comment by deadc0de6** [comment]
thanks !
I merged your changes.
