### ISSUE TITLE
[help] just make sure does zsh complete not work for have environment-variables situation?

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#247]
**What I am trying to achieve**

I have environment-variables when use dotdrop followed [environment-variables](https://github.com/deadc0de6/dotdrop/wiki/templating#environment-variables).

---

But seems completion not work for this, but work when directly use `/usr/bin/dotdrop`.

**Comment by deadc0de6** [comment]
I would need more info to help

* what completion do you use (`bash`, `zsh` or `fish`)?
* an example of a command where completion doesn't work
* what you exactly mean by *having environment-variables* and how that relates to completion

**Comment by roachsinai** [comment]
First question: I'm using `zsh`

Second and third: `aliased to eval $(grep -v "^#" /home/roach/Nutstore\ Files/我的坚果云/.env) /usr/bin/dotdrop --cfg=/home/roach/code/Git/dotfiles/config.yaml`
	each command like `dotdrop install` all works, but `dotdrop`<kbd>tab</kbd> no completions.

but `/usr/bin/dotdrop`<kbd>tab</kbd> get completions.

**Comment by deadc0de6** [comment]
This is not a problem in dotdrop, this is related to having completion and aliases. You can google it for some help but usually you solve this that way in zsh:
```zsh
alias d=dotdrop
compdef d=dotdrop
```

**Comment by roachsinai** [comment]
Yeah, just make issue to make sure that. Thanks for your reply!
