### ISSUE TITLE
[bug] module 'dotdrop' has no attribute 'main'

### ISSUE THREAD

**Issue by lelgenio** [deadc0de6/dotdrop#260]
Dotdrop version: v1.2 
Using dotdrop: AUR stable or git, happens in both

**Describe the bug**
Running fails due to import error

**Steps to Reproduce**

1. Install dotdrop from AUR (`with yay -S dotdrop`)
2. run dotdrop (`dotdrop --version`)

Restoring the contents of `__init__.py` (before 57f69418a22) seem to fix this

Dotdrop's execution with the debug logs (`--verbose`)
```python
$ dotdrop --verbose
Traceback (most recent call last):
  File "/usr/bin/dotdrop", line 33, in <module>
    sys.exit(load_entry_point('dotdrop==1.2.0', 'console_scripts', 'dotdrop')())
  File "/usr/bin/dotdrop", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.8/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'dotdrop' has no attribute 'main'
```

Running as a module still works fine
```bash
$ python -m dotdrop.dotdrop --version
1.2.0
```

**Comment by deadc0de6** [comment]
I fixed it and released a new version, thanks!
