### ISSUE TITLE
Force action on install doesn't apply for default actions

### ISSUE THREAD

**Issue by kevinconley19** [deadc0de6/dotdrop#261]
1.2.1, Python 3.8.5, 5.8.12-arch1-1

It appears the focre action does always run default actions on an install as specfied by usage documnentation:

-a --force-actions: force the execution of actions even if the dotfiles are not installed

It  only forces actions that are attached to a specfic file not in the "config" sectin of config.yaml.

I noticed this b/c i has a files that required a chmod after install and decided to just put this in the "default_actions" config. Before, everytime i did "dotdrop install -fa" it ran chmod. Now with default actions after one run i see the chmod but then running again right aways only shows

0 dotfile(s) installed.
 
And i see no chomod output.

**Comment by deadc0de6** [comment]
Yes this is a bug. It should be fixed in in the master branch.
