### ISSUE TITLE
[help] link_on_import: link doesn't seem to work.

### ISSUE THREAD

**Issue by josaladino2** [deadc0de6/dotdrop#263]
**What I am trying to achieve**
I would like to have the local ~/.bashrc file be a link to the file managed by dotdrop.
**What I have tried so far**
I followed a previous issue and added a link by default directive which it says has been depreciated.  
It updated  my config file with I assume to be the correct verbiage now but when I import ~.bashrc the file remains a regular file and not a link to the dotdrop repository file.
Is this correct behavior?
I installed this on Friday so I suspect I am using the latest version.
Thanks for your help.

Joe
Joe@bram.net

**Comment by deadc0de6** [comment]
Here's a way to do it:

import the file 
```bash
$ ./dotdrop.sh import ~/.bashrc 
	-> "/home/user/.bashrc" imported
```

edit the `config.yaml` and set the `link` value to `link`
```yaml
dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    link: link
```

install the dotfile what will remove your `~/.bashrc` and replace it with a link to the file stored in dotdrop
```bash
$ ./dotdrop.sh install         
Remove "/home/user/.bashrc" for link creation? [y/N] ? y
	-> linked /home/user/.bashrc to /home/user/dotdrop/dotfiles/bashrc

1 dotfile(s) installed.
$ readlink ~/.bashrc         
/home/user/dotdrop/dotfiles/bashrc
```

You then have several ways to automate the config `link` entry depending if symlinking dotfiles should be your default behavior or a one-time operation

* [link_dotfile_default](https://dotdrop.readthedocs.io/en/latest/config-format/#config-entry)
* [link_on_import](https://dotdrop.readthedocs.io/en/latest/config-format/#config-entry)

**Comment by deadc0de6** [comment]
I have added the above example in the doc directly [here](https://dotdrop.readthedocs.io/en/latest/howto/symlink-dotfiles/#symlink-a-dotfile).

**Comment by josaladino2** [comment]
Hi:
    Not sure why this didn't show up on my git forum list.  Must have
      done something wrong.  Thanks for your reply.
    I know I am missing something.  If I link ~/.bashrc to the
      dotdrop version and I make changes to the ~/.bashrc file, I
      understand that it will also change the dotdrop version as well at
      that same moment.  What I don't get is how the dotdrop version of
      .bashrc gets into the remote repository?  Am I supposed to do
      something else to include ~/.dotfiles as a submodule in my remote
      repository?  Clearing this up would help me see how to update
      local repository from remote repository if there changes I need to
      pull.
    Hope this makes some sense.
    Thanks.
    
    
      --
      ___________________________
      Joe Saladino[joe@bram.net]
      Ph: (208) 971-7570
      
      You never realize Jesus is all you need
      until Jesus is all you have.
      --Timothy Keller (The Prodigal Prophet)
    On 10/4/20 1:06 PM, deadc0de wrote:
    
    
      
      Here's a way to do it:
      import the file
      
        $ ./dotdrop.sh import ~/.bashrc 
	-> "/home/user/.bashrc" imported
      
      edit the config.yaml and set the link
        value to link
      
        dotfiles:
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    link: link
      
      install the dotfile what will remove your ~/.bashrc
        and replace it with a link to the file stored in dotdrop
      
        $ ./dotdrop.sh install         
Remove "/home/user/.bashrc" for link creation? [y/N] ? y
	-> linked /home/user/.bashrc to /home/user/dotdrop/dotfiles/bashrc

1 dotfile(s) installed.
$ readlink ~/.bashrc         
/home/user/dotdrop/dotfiles/bashrc
      
      You then have several ways to automate the config link
        entry depending if symlinking dotfiles should be your default
        behavior or a one-time operation
      
        link_dotfile_default
        link_on_import
      
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
        {
        "@context": "http://schema.org",
        "@type": "EmailMessage",
        "potentialAction": {
        "@type": "ViewAction",
        "target":
"https://github.com/deadc0de6/dotdrop/issues/263#issuecomment-703300972","url":
"https://github.com/deadc0de6/dotdrop/issues/263#issuecomment-703300972",
        "name": "View Issue"
        },
        "description": "View this Issue on GitHub",
        "publisher": {
        "@type": "Organization",
        "name": "GitHub",
        "url": "https://github.com"
        }
        }
        ]

**Comment by deadc0de6** [comment]
The changes in your dotfiles respository (the repository containing dotdrop submodule, your dotfiles and your config file) are sync'ed using git.

That means that any change to a dotfile (or to the config file) needs to be commited and pushed using git and pulled from a different host,

For example ...

on hostA
```bash
## create a repository
$ cd /tmp/
$ mkdir -p mydotfiles.git
$ cd mydotfiles.git
$ git init

## install dotdrop in it
## doc here: https://dotdrop.readthedocs.io/en/latest/installation/#as-a-submodule
$ git submodule add https://github.com/deadc0de6/dotdrop.git
$ pip3 install --user -r dotdrop/requirements.txt
$ ./dotdrop/bootstrap.sh

## edit config set link_on_import to link
$ cat config.yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
  link_on_import: link
dotfiles:
profiles:

## commit your changes
$ git add *
$ git commit -m 'adding dotdrop'
## TODO "git push" if you have a remote
$ ls -1               
dotdrop
dotfiles
config.yaml
dotdrop.sh

## import a file and install symlink
$ ./dotdrop.sh import ~/.bashrc 
        -> "/home/user/.bashrc" imported

1 file(s) imported.
$ ./dotdrop.sh install         
Remove "/home/user/.bashrc" for link creation? [y/N] ? y
        -> linked /home/user/.bashrc to /tmp/mydotfiles.git/dotfiles/bashrc

1 dotfile(s) installed.

## commit your changes
$ git add config.yaml dotfiles/bashrc
$ git commit -m 'adding bashrc'
## TODO "git push" if you have a remote

## here's the state of your repository (excluded the whole dotdrop submodule)
$ tree -I "dotdrop"  
.
├── config.yaml
├── dotdrop.sh
└── dotfiles
    └── bashrc

1 directory, 3 files
```

Now you have a dotfile repository. You then need to get it on the second host to install your dotfiles there.
I'm doing it locally for the example but usually you push that on the main repo (github, gitlab, your own git server, etc).

on hostB 
```
## clone the repository
$ cd /tmp/
$ git clone mydotfiles.git mydotfiles.hostB
$ cd mydotfiles.hostB

## install your dotfiles
$ ./dotdrop.sh install
```

And subsequent changes pushed from one side, you'll have to pull on the other side, this is basic git behavior.
Dotdrop won't manage git operations for you. However you can always integrate that into the `dotdrop.sh` script for example.

I hope this answers your questions and makes it more clear.

**Comment by deadc0de6** [comment]
BTW git is the recommended way of doing this but you could of course use any other means to move your directory to the other side (cp/scp, other version control systems (svn, etc), clouds, syncing solutions (syncthings, dropbox, etc), ...)

**Comment by josaladino2** [comment]
Hi:
    Thanks so much for your reply.
    I am wondering if link_on_import can get set to link_children and
      what impact that would have on an individual file?
    When I bring in directories, do I want all the files in that
      directory to be linked?  Is that a good practice?  What would I
      miss by having just the top level directory linked?
    Thanks so much for taking the time to show me the details below.
    
    
      --
      ___________________________
      Joe Saladino[joe@bram.net]
      Ph: (208) 971-7570
      
      You never realize Jesus is all you need
      until Jesus is all you have.
      --Timothy Keller (The Prodigal Prophet)
    On 10/5/20 1:54 AM, deadc0de wrote:
    
    
      
      The changes in your dotfiles respository (the repository
        containing dotdrop submodule, your dotfiles and your config
        file) are sync'ed using git.
      That means that any change to a dotfile (or to the config file)
        needs to be commited and pushed using git and pulled from a
        different host,
      For example ...
      on hostA
      
        ## create a repository
$ cd /tmp/
$ mkdir -p mydotfiles.git
$ cd mydotfiles.git
$ git init

## install dotdrop in it
## doc here: https://dotdrop.readthedocs.io/en/latest/installation/#as-a-submodule
$ git submodule add https://github.com/deadc0de6/dotdrop.git
$ pip3 install --user -r dotdrop/requirements.txt
$ ./dotdrop/bootstrap.sh

## edit config set link_on_import to link
$ cat config.yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
  link_on_import: link
dotfiles:
profiles:

## commit your changes
$ git add *
$ git commit -m 'adding dotdrop'
## TODO "git push" if you have a remote
$ ls -1               
dotdrop
dotfiles
config.yaml
dotdrop.sh

## import a file and install symlink
$ ./dotdrop.sh import ~/.bashrc 
        -> "/home/user/.bashrc" imported

1 file(s) imported.
$ ./dotdrop.sh install         
Remove "/home/user/.bashrc" for link creation? [y/N] ? y
        -> linked /home/user/.bashrc to /tmp/mydotfiles.git/dotfiles/bashrc

1 dotfile(s) installed.

## commit your changes
$ git add config.yaml dotfiles/bashrc
$ git commit -m 'adding bashrc'
## TODO "git push" if you have a remote

## here's the state of your repository (excluded the whole dotdrop submodule)
$ tree -I "dotdrop"  
.
├── config.yaml
├── dotdrop.sh
└── dotfiles
    └── bashrc

1 directory, 3 files
      
      Now you have a dotfile repository. You then need to get it on
        the second host to install your dotfiles there.
        I'm doing it locally for the example but usually you push that
        on the main repo (github, gitlab, your own git server, etc).
      on hostB
      ## clone the repository
$ cd /tmp/
$ git clone mydotfiles.git mydotfiles.hostB
$ cd mydotfiles.hostB

## install your dotfiles
$ ./dotdrop.sh install

      And subsequent changes pushed from one side, you'll have to
        pull on the other side, this is basic git behavior.
        Dotdrop won't manage git operations for you. However you can
        always integrate that into the dotdrop.sh script
        for example.
      I hope this answers your questions and makes it more clear.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
        {
        "@context": "http://schema.org",
        "@type": "EmailMessage",
        "potentialAction": {
        "@type": "ViewAction",
        "target":
"https://github.com/deadc0de6/dotdrop/issues/263#issuecomment-703466381","url":
"https://github.com/deadc0de6/dotdrop/issues/263#issuecomment-703466381",
        "name": "View Issue"
        },
        "description": "View this Issue on GitHub",
        "publisher": {
        "@type": "Organization",
        "name": "GitHub",
        "url": "https://github.com"
        }
        }
        ]

**Comment by deadc0de6** [comment]
The `link_children` option set on a file that is not a directory will fail on all operations. It is therefore a bad idea to set it in `link_on_import`. I'll add that to the doc, thanks for pointing that out

To understand the advantage on using `link_children` you can have a look at the [example in the doc](https://dotdrop.readthedocs.io/en/latest/howto/symlink-dotfiles/#link-children). `link_children` is useful when you want dotdrop to manage a directory but don't want all files/directories in it to be managed/stored. For all other cases (most of them) you would want `link`.

**Comment by josaladino2** [comment]
Hi:
    As you can tell, I'm a bit new to git.  But I am a quick study
      and won't bug you to death. 
    If you look at my repository:
      https://github.com/josaladino2/userfiles, you will see that I have
      a fonts directory there.  I created that as a submodule within my
      userfiles directory.  Not sure that was the right thing to do but
      that directory is within my home directory so structurally it
      seems like the right thing to do since it has it's own .git setup.
    I tried to do the same thing for dotfiles and when I went to
      github.com to take a look, it could not find the page.
    So my question is, would I set up a remote within my userfiles
      repository like fonts or do I just keep it separate on its own as
      repository #2 in my account?
    What would be the best setup for dotfiles?  Somehow bashrc needs
      to be in my github respository but not show how to get it there.
    Make sense?
    Thanks so much for your help.
    
    
      --
      ___________________________
      Joe Saladino[joe@bram.net]
      Ph: (208) 971-7570
      
      You never realize Jesus is all you need
      until Jesus is all you have.
      --Timothy Keller (The Prodigal Prophet)
    On 10/5/20 1:54 AM, deadc0de wrote:
    
    
      
      The changes in your dotfiles respository (the repository
        containing dotdrop submodule, your dotfiles and your config
        file) are sync'ed using git.
      That means that any change to a dotfile (or to the config file)
        needs to be commited and pushed using git and pulled from a
        different host,
      For example ...
      on hostA
      
        ## create a repository
$ cd /tmp/
$ mkdir -p mydotfiles.git
$ cd mydotfiles.git
$ git init

## install dotdrop in it
## doc here: https://dotdrop.readthedocs.io/en/latest/installation/#as-a-submodule
$ git submodule add https://github.com/deadc0de6/dotdrop.git
$ pip3 install --user -r dotdrop/requirements.txt
$ ./dotdrop/bootstrap.sh

## edit config set link_on_import to link
$ cat config.yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
  link_on_import: link
dotfiles:
profiles:

## commit your changes
$ git add *
$ git commit -m 'adding dotdrop'
## TODO "git push" if you have a remote
$ ls -1               
dotdrop
dotfiles
config.yaml
dotdrop.sh

## import a file and install symlink
$ ./dotdrop.sh import ~/.bashrc 
        -> "/home/user/.bashrc" imported

1 file(s) imported.
$ ./dotdrop.sh install         
Remove "/home/user/.bashrc" for link creation? [y/N] ? y
        -> linked /home/user/.bashrc to /tmp/mydotfiles.git/dotfiles/bashrc

1 dotfile(s) installed.

## commit your changes
$ git add config.yaml dotfiles/bashrc
$ git commit -m 'adding bashrc'
## TODO "git push" if you have a remote

## here's the state of your repository (excluded the whole dotdrop submodule)
$ tree -I "dotdrop"  
.
├── config.yaml
├── dotdrop.sh
└── dotfiles
    └── bashrc

1 directory, 3 files
      
      Now you have a dotfile repository. You then need to get it on
        the second host to install your dotfiles there.
        I'm doing it locally for the example but usually you push that
        on the main repo (github, gitlab, your own git server, etc).
      on hostB
      ## clone the repository
$ cd /tmp/
$ git clone mydotfiles.git mydotfiles.hostB
$ cd mydotfiles.hostB

## install your dotfiles
$ ./dotdrop.sh install

      And subsequent changes pushed from one side, you'll have to
        pull on the other side, this is basic git behavior.
        Dotdrop won't manage git operations for you. However you can
        always integrate that into the dotdrop.sh script
        for example.
      I hope this answers your questions and makes it more clear.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
        {
        "@context": "http://schema.org",
        "@type": "EmailMessage",
        "potentialAction": {
        "@type": "ViewAction",
        "target":
"https://github.com/deadc0de6/dotdrop/issues/263#issuecomment-703466381","url":
"https://github.com/deadc0de6/dotdrop/issues/263#issuecomment-703466381",
        "name": "View Issue"
        },
        "description": "View this Issue on GitHub",
        "publisher": {
        "@type": "Organization",
        "name": "GitHub",
        "url": "https://github.com"
        }
        }
        ]

**Comment by deadc0de6** [comment]
The usual way of doing is described [in the doc](https://dotdrop.readthedocs.io/en/latest/repository-setup/) and is to version the entire *my-dotfiles* directory in its own repository (containing the config file and your entire dotfiles directory).

Regarding git submodule, there are plenty of documentation on it but take a look at this one that gives the basics on how it works: <https://git-scm.com/book/en/v2/Git-Tools-Submodules>.

It seems you have a dotfiles submodule in your userfiles repository (based on the content of the [.gitmodules](https://github.com/josaladino2/userfiles/blob/master/.gitmodules)) however either it doesn't exist (was never created) or I can't see it (private?).

Since this fonts directory should be in your home but is actually simply a clone of an existing directory, I wouldn't store it directly in dotdrop but use dotdrop to install it (using [actions](https://dotdrop.readthedocs.io/en/latest/config-details/#entry-actions)):

* depending on a specific dotfile if any (see [dotfile actions](https://dotdrop.readthedocs.io/en/latest/config-details/#dotfile-actions))
* or simply using a [fake dotfile](https://dotdrop.readthedocs.io/en/latest/config-details/#fake-dotfile-and-actions)

For example let's say you want to install it using a fake dotfile, part of the config would look like this
```yaml
actions:
  install_fonts: '[ ! -d ~/fonts ] && git clone https://github.com/powerline/fonts.git ~/fonts'
dotfiles:
  fake:
    src:
    dst:
    actions:
    - install_fonts
```

**Comment by deadc0de6** [comment]
But tbh I'm not sure I understand what is that userfiles repository and how it related to dotdrop? Is it your *dotpath*? or is your dotfiles submodule your *dotpath*?

**Comment by josaladino2** [comment]
Hi:
    Quick question
    After I did the:
    $ pip3 install --user -r dotdrop/requirements.txt
$ ./dotdrop/bootstrap.sh
    I did git status within the
      ~/dotfiles.git directory and got this results.
    
    
    Changes to be committed:
        (use "git rm --cached <file>..." to unstage)
          new file:   .gitmodules
          new file:   dotdrop
    
    
    
    I am not tracking those files within the
      ~/dotfiles.git directory
    
    
    What i would prefer is to track those
      files and the ~/dotfiles.git/dotfiles/* from within my home git
      remote repository.
    Am I missing something?  Would you
      recommend someting different?
    
    
    
    In the documentation I would put import/update/install/remove
      together (one after the other) with a brief summary before them
      explaining (forgetting about the link which confuses things) 
    
    something like:
    
      
        
          import copies the initial ~/.vimrc to your dotpath and sets
            up the config.yaml
          
        
        update: copies ~/.vimrc
          to your dotpath (after you have made a change to
            ~/.vimrc)
          
        
          install: copies the vimrc dotfile
            from your dotpath/ to ~/.vimrc (if you want
              the new dotfiles/ vimrc to be written over ~/.vimrc)
            
          
        remove: removes dotfiles/vimrc file from dotfiles/ and the
          entries for ~/.vimrc from the config.yaml
      
    
    How about a simple lifecycle like
    dotdrop import ~/.vimrc (to put
      filesystem file into dotdrop dotfiles/
    
    change filesystem ~/.vimrc
    dotdrop update ~/.vimrc (puts changes
      into the dotdrop dotfiles/
    change ~/vimrc on another server (after
      update from the other server)
    dotdrop install dotfiles/vimrc (move
      changed dotfiles/ vimrc to ~/.vimrc
    
    
    I don't know if this is helpful but would
      have helped me quite a bit to see a 70,000 ft fly-by and then to
      get into the details.
    
    
    You clearing up the install and update
      was the key to helping me get my arms around the process.
    
    
    
    Also, I can see now that linking the
      filesystem files with dotfiles directory seems like a bad idea.  I
      think we have more control by using update and install.  Your
      explination was very good and helpful.
    
    
    I look forward to your answer to the
      above question.
    
    
    Thanks.
    
    --
      ___________________________
      Joe Saladino[joe@bram.net]
      Ph: (208) 971-7570
      
      You never realize Jesus is all you need
      until Jesus is all you have.
      --Timothy Keller (The Prodigal Prophet)
    On 10/5/20 1:54 AM, deadc0de wrote:
    
    
      
      The changes in your dotfiles respository (the repository
        containing dotdrop submodule, your dotfiles and your config
        file) are sync'ed using git.
      That means that any change to a dotfile (or to the config file)
        needs to be commited and pushed using git and pulled from a
        different host,
      For example ...
      on hostA
      
        ## create a repository
$ cd /tmp/
$ mkdir -p mydotfiles.git
$ cd mydotfiles.git
$ git init

## install dotdrop in it
## doc here: https://dotdrop.readthedocs.io/en/latest/installation/#as-a-submodule
$ git submodule add https://github.com/deadc0de6/dotdrop.git
$ pip3 install --user -r dotdrop/requirements.txt
$ ./dotdrop/bootstrap.sh

## edit config set link_on_import to link
$ cat config.yaml
config:
  backup: true
  create: true
  dotpath: dotfiles
  link_on_import: link
dotfiles:
profiles:

## commit your changes
$ git add *
$ git commit -m 'adding dotdrop'
## TODO "git push" if you have a remote
$ ls -1               
dotdrop
dotfiles
config.yaml
dotdrop.sh

## import a file and install symlink
$ ./dotdrop.sh import ~/.bashrc 
        -> "/home/user/.bashrc" imported

1 file(s) imported.
$ ./dotdrop.sh install         
Remove "/home/user/.bashrc" for link creation? [y/N] ? y
        -> linked /home/user/.bashrc to /tmp/mydotfiles.git/dotfiles/bashrc

1 dotfile(s) installed.

## commit your changes
$ git add config.yaml dotfiles/bashrc
$ git commit -m 'adding bashrc'
## TODO "git push" if you have a remote

## here's the state of your repository (excluded the whole dotdrop submodule)
$ tree -I "dotdrop"  
.
├── config.yaml
├── dotdrop.sh
└── dotfiles
    └── bashrc

1 directory, 3 files
      
      Now you have a dotfile repository. You then need to get it on
        the second host to install your dotfiles there.
        I'm doing it locally for the example but usually you push that
        on the main repo (github, gitlab, your own git server, etc).
      on hostB
      ## clone the repository
$ cd /tmp/
$ git clone mydotfiles.git mydotfiles.hostB
$ cd mydotfiles.hostB

## install your dotfiles
$ ./dotdrop.sh install

      And subsequent changes pushed from one side, you'll have to
        pull on the other side, this is basic git behavior.
        Dotdrop won't manage git operations for you. However you can
        always integrate that into the dotdrop.sh script
        for example.
      I hope this answers your questions and makes it more clear.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
        {
        "@context": "http://schema.org",
        "@type": "EmailMessage",
        "potentialAction": {
        "@type": "ViewAction",
        "target":
"https://github.com/deadc0de6/dotdrop/issues/263#issuecomment-703466381","url":
"https://github.com/deadc0de6/dotdrop/issues/263#issuecomment-703466381",
        "name": "View Issue"
        },
        "description": "View this Issue on GitHub",
        "publisher": {
        "@type": "Organization",
        "name": "GitHub",
        "url": "https://github.com"
        }
        }
        ]
