### ISSUE TITLE
[help] what is the life-cycle of a file in dotdrop in local machine.

### ISSUE THREAD

**Issue by josaladino2** [deadc0de6/dotdrop#264]
**What I am trying to achieve**
I am wondering if there is a posting of a complete life-cycle of a file as it relates to dotdrop.
importing a file
steps to complete the import to main repository
steps to update repository after an edit of the file
steps to pull changes back to local computer

I know there are a lot of variations to git but it might help the newbie like me (both git and dotdrop) to get my arms around this a bit faster.

Thanks for your help.
Joe
**What I have tried so far**

**Comment by deadc0de6** [comment]
Here's a little walkthrough:

* first on how to setup your repository: <https://dotdrop.readthedocs.io/en/latest/repository-setup/>
* and then an example on how to get started: <https://github.com/deadc0de6/dotdrop/blob/master/README.md#getting-started>

Let me know if anything is unclear
