### ISSUE TITLE
[Feature request] Git integration

### ISSUE THREAD

**Issue by ReekyMarko** [deadc0de6/dotdrop#27]
Right now I have a couple of zsh aliases to speed up using git on my dotdrop repository:
```
alias dotdrop='~/git/dotfiles/dotdrop.sh'
alias dotgit='git -C ~/git/dotfiles'
alias dotsync='dotgit pull; dotgit add -A; dotgit commit; dotgit push; dotdrop install'
```
Might not be the best naming scheme but the idea is that when I edit a dotfile on any of my pc's, I can run dotsync on the originating pc and write a commit message. Then I can just run dotsync again everywhere else and it automagically syncs and installs everything with a grand total of two commands.

I think end users would really benefit from git integration like this. I have no idea how I would start implementing something like this but I'm just putting this on the table for the contributors to consider.

**Comment by deadc0de6** [comment]
I could for sure add these aliases to the readme!

Or we could add those into some bash script that would be generated during dotdrop installation and ask the user to symlink it somewhere in the `$PATH`, what do you think ?

Personally I like the aliases better but it is *less* automated.

**Comment by ReekyMarko** [comment]
Yeah the aliases might be better for customizability by the user and a lot less likely to break things across distros.

I recommend to check the aliases for safety in different situations. I'm a newbie in git so especially the dotgit alias could need a bit of refactoring. Also, if needed, feel free to rename them to better suit your project.

On an unrelated note, thank you very much for this wonderful program! Certainly makes my life a lot easier :+1:

**Comment by deadc0de6** [comment]
Thanks :-) happy if this tool helps 

One downside I see with these aliases is if there are any git conflicts (un-commited changes, merge conflicts, etc). One solution could be to link those with `&&` instead of semi-colon.

I'm guessing you are linking your dotfiles but for people installing them, they would anyway have to go through editing (or re-importing any dotfiles) before calling the aliases.

Anyway I was thinking of creating a wiki page with user provided ideas/helpers, ok for you to add your aliases there ?

**Comment by ReekyMarko** [comment]
Yeah this is exactly why I said I am a newb in git :)

I'm actually installing my dots and haven't had any problems using these yet. Dotdrop just asks to confirm overwriting all of the changed files. And yes I can add these on the wiki. Post a link to where you want me to add these and I can submit a PR with a short article.

**Comment by deadc0de6** [comment]
Awesome, I started a page [here](https://github.com/deadc0de6/dotdrop/wiki/user-tricks) with the basic info.

Thanks for your help!

**Comment by ReekyMarko** [comment]
I cloned your wiki to [here](https://github.com/ReekyMarko/dotdrop-wiki/blob/master/user-tricks.md) and made my changes.

Sorry it took so long, I've been really busy. You can close this issue if you're happy with my changes.

**Comment by deadc0de6** [comment]
No worries, thanks for helping.

I've merged your changes in the wiki.

**Comment by ReekyMarko** [comment]
I just noticed that the dotsync alias should look like this:
`alias dotsync="dotgit pull && dotgit add -A && dotgit commit && dotgit push; dotdrop install"`
For some reason the `dotdrop install` doesn't run if it is separated with `&&`.

**Comment by deadc0de6** [comment]
In bash the idea of using `&&` is that if the command on the left fails (returns a exit status different from `0`), it won't keep executing the rest. `; ` is used to separate different commands.

It is up to you but my understanding is that if one of the command in the whole oneliner fails, I wouldn't want the rest to be executed, for example if `git add -A` fails, you don't want to `git commit` and so on.

Do you know why the `git push` is returning something else than a exit status of `0` ? Usually git is pretty good for returning consistent error code.

**Comment by ReekyMarko** [comment]
Aah now I understand it better. Seems that git push returns !=0 if there is nothing to push. So if I run `dotsync` on a machine I made changes with, everything works just fine, but if I want to sync the changes to another device, it doesn't install them because there is nothing to be pushed and it breaks the chain of &&'s. 

I think the best course of action is to just change the last command to be separated with `;`

**Comment by deadc0de6** [comment]
Ok, I made the change.
