### ISSUE TITLE
[feature] Making --cfg a command option rather than subcommand option

### ISSUE THREAD

**Issue by billop** [deadc0de6/dotdrop#274]
Right now we have to put `--cfg` after the subcommand we want to execute, but I think it should be after the command itself.

So right now it's like this:
```
sudo dotdrop import --cfg=.config/dotdrop/global.yaml /etc/mkinitcpio.conf /etc/pacman.conf /etc/makepkg.conf
sudo dotdrop install --cfg=.config/dotdrop/global.yaml
```

but I think it should be like this:
```
sudo dotdrop --cfg=.config/dotdrop/global.yaml import /etc/mkinitcpio.conf /etc/pacman.conf /etc/makepkg.conf
sudo dotdrop --cfg=.config/dotdrop/global.yaml install
```

Minor tweak (I understand not neccesarily easy to implement) but I think it would be really nice for quality of life purposes.

**Comment by deadc0de6** [comment]
Both work (before and after the subcommand). Your suggestion is to force the user to provide `--cfg` before the subcommand?

**Comment by billop** [comment]
Just checked and realized it can be both ways. In that case it's a bug with the fish autocompletion, but that's a whole separate issue.
