### ISSUE TITLE
[help] Having trouble with config file

### ISSUE THREAD

**Issue by josaladino2** [deadc0de6/dotdrop#276]
**What I am trying to achieve**
I would like to have my config file constructed such that I can have a group of files that will apply to all my machines and some that apply to specific machines.  I set it up like I thought it should be set up and got errors.  The file I am sending you now works but I don't have any common: files that will be applicable to all machines.  What am I missing?

Also, Is there a way to set my profile for dtodrop so I don't have to include the entire FQDN in the config file?  Is there an environment variable I can set?
**What I have tried so far**
I have tried the following:

dotfiles:
  common:
    dotfiles:
      files
  Doc:
    dotfiles:
      files
  dopey:
    dotfiles:
      files

and  this does not work.
[config-copy.txt](https://github.com/deadc0de6/dotdrop/files/5424588/config-copy.txt)

**Comment by deadc0de6** [comment]
You can use the profile include entry (see [the doc here](https://dotdrop.readthedocs.io/en/latest/config-details/#entry-profile-include)). Here's an example of what I do use to set *meta-profiles* that are shared among multiple hosts:
```yaml
profiles:
  meta_zsh:
    dotfiles:
    - f_zprofile
    - f_zshrc
  some_host:
    dotfiles:
    - f_gitconfig
    include:
    - meta_zsh
```

The profile `meta_zsh` is specific to zsh and can be included in any host for example.

Also, if your profile contains all defined dotfiles, you can always use the keyword `ALL` (see [the doc here](https://dotdrop.readthedocs.io/en/latest/config/#all-dotfiles-for-a-profile)).

Regarding FQDN, I'm not sure what you mean, can you elaborate please?

**Comment by josaladino2** [comment]
I would like to test for the machine name “dopey” and not include the domain. Is profile: able to be set somewhere?  I assume that it is retrieved from hostname.  Could that be changed to hostname -s or reset in .zshrc or config.yaml?ill have to take a look at the meta_zsh thing. Does bash have something similar?
Thx
--
____________________________
Joe Saladino [joe@bram.net] 
(From my iPhone)
+1(208) 971-7570

“You never realize Jesus is all you need
until Jesus is all you have.”
--Timothy Keller (The Prodigal Prophet)

**Comment by deadc0de6** [comment]
The profile defaults to the hostname of the host (as returned by [socket.gethostname](https://docs.python.org/3/library/socket.html#socket.gethostname)). As far as I'm aware it ends up to the exact same output as `hostname -s`.

It can also be changed:

* using the command line switch `-p --profile=<profile>`
* by defining the env variable `DOTDROP_PROFILE`

The example with `meta_zsh` is not related to zsh, it's simply an example, the same could be done for bash, for example
```yaml
profiles:
  meta_bash:
    dotfiles:
    - f_bashrc
  some_host:
    dotfiles:
    - f_gitconfig
    include:
    - meta_bash
```
