### ISSUE TITLE
[bug] Removal from a profile without dotfiles key throws KeyError: 'dotfiles'

### ISSUE THREAD

**Issue by scrool** [deadc0de6/dotdrop#280]
Dotdrop version (and git commit if run from source): v1.3.4
Using dotdrop: from pypi

**Describe the bug**

When I try to remove file that has its `dotfiles` entry included from other profile the config entry nor file is not removed and I get traceback with error `KeyError: 'dotfiles'`. 

**Steps to Reproduce**

1. Create a `~/.somefile` and dotdrop config with content:
```yaml
dotfiles:
  f_somfile:
    src: somefile
    dst: ~/.somefile
  f_otherfile:
    src: otherfile
    dst: ~/.otherfile
profiles:
  work_laptop:
    dotfiles:
    - f_otherfile
    - f_somefile
  myhost:
    include:
      - work_laptop
```
2. I would like to remove `~/.somefile` so I run:
```
$ dotdrop remove ~/.somefile
```
3. I anwer yes to removal from everywhere:
```
Remove "f_somefile" from all these profiles: work_laptop,myhost [y/N] ? y
```
4. I get error with a traceback:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "[dotfilepath]/dotdrop/dotdrop/dotdrop.py", line 769, in <module>
    if main():
  File "[dotfilepath]/dotdrop/dotdrop/dotdrop.py", line 751, in main
    cmd_remove(o)
  File "[dotfilepath]/dotdrop/dotdrop/dotdrop.py", line 580, in cmd_remove
    if not o.conf.del_dotfile_from_profile(dotfile, profile):
  File "[dotfilepath]/dotdrop/dotdrop/cfg_aggregator.py", line 149, in del_dotfile_from_profile
    return self.cfgyaml.del_dotfile_from_profile(dotfile.key, profile.key)
  File "[dotfilepath]/dotdrop/dotdrop/cfg_yaml.py", line 362, in del_dotfile_from_profile
    if df_key not in profile[self.key_profile_dotfiles]:
  File "[home]/.local/lib/python3.6/site-packages/ruamel/yaml/comments.py", line 753, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'dotfiles'
```

**Expected behavior**

Do not crash and get:
```
dotfile(s) removed: f_somefile
```

**Additional information**

When I add empty entry to the profile like this:
```yaml
...
  myhost:
    include:
      - work_laptop
    dotfiles: []
```

removal suceeds without an error as expected.

I'm not sure if dotdrop's execution with the debug logs (`--verbose`) would help here. I can provide if you are not able to reproduce this.

**Comment by deadc0de6** [comment]
The first issue I see is that the dotfile key is named `f_somfile` (without an `e`) and the profile is including a dotfile named `f_somefile` (with an `e`).

For your issue it was a bug and it should be fixed with above commit.

**Comment by scrool** [comment]
> The first issue I see is that the dotfile key is named `f_somfile` (without an `e`) and the profile is including a dotfile named `f_somefile` (with an `e`).

Ah, I'm sorry. This was copy-paste error when I tried to generalize my config and dotfile reference. Both should be the same.

**Comment by deadc0de6** [comment]
Version 1.3.5 should be good.
