### ISSUE TITLE
[feature] Robust permissions handling

### ISSUE THREAD

**Issue by billop** [deadc0de6/dotdrop#286]
I've been using an action to chmod some config files in order to set the correct permissions. Basically this: https://github.com/deadc0de6/dotdrop/issues/186#issuecomment-533522554. However, there are several issues involved with this approach:

1. If the target file already has the correct permissions applied by a previous installation's post action, it results in having different permissions from the source file and will get re-installed.
2. If the target file does not yet hvae the correct permissions, the installation will not notice that it has incorrect permissions and will not re-install the file as it should to fix permissions.
3. If the target file is within a directory which itself requires specific permissions (e.g. `.gnupg/gpg.conf`), it gets pretty complicated and I think the only way to manage this right now is to manage the directory itself unless there is a special variable that gives access to the parent dir.

Overall I wish we could do something like this:

```yaml
dotfiles:
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
    chmod: 600
```

where dotdrop is aware of permissions and avoids the previously mentioned issues.

Chezmoi for example has permissions management at its core but I had found it to be unnecessarily complex which is why I have so far really enjoyed using dotdrop.
However with its simplicity I have found permissions to be its weak point, unless I'm missing something.

**Comment by deadc0de6** [comment]
What dotdrop currently does is copy the file and its permissions when importing. And apply the permissions when installing. The permission are thus directly part of the file itself in the `dotpath` and not actually *managed* by dotdrop.

If you want to apply different permissions during installation, one solution as you mentioned is to use actions.

Here's what happens:
```bash
## create a file with permissions
$ touch /tmp/x
$ chmod 600 /tmp/x
$ stat -c '%a' /tmp/x          
600

## import in dotdrop
$ ./dotdrop.sh import /tmp/x       
	-> "/tmp/x" imported

1 file(s) imported.
$ stat -c '%a' dotfiles/tmp/x 
600

## remove original file and install with dotdrop
$ rm /tmp/x
$ ./dotdrop.sh install -f   
	-> copied /home/user/dotdrop/dotfiles/tmp/x to /tmp/x

1 dotfile(s) installed.
$ stat -c '%a' /tmp/x
600
```

What are your use-cases that are not covered by the normal dotdrop behavior described above or the *ad-hoc* solution of changing the rights with `chmod` in an action.
I just want to understand precisely why such a feature should be added to dotdrop and for which use-case.

**Comment by scrool** [comment]
I have run into the similar situation. On the top of what you have run so far I'm tracking all my files in git and sync those files across machine I manage. When you push those files to git:
```
$ git add .
$ git commit -m 'update all'
```
and then clone that repo:
```
$ cd /tmp
$ git clone ~/dotfiles dotfiles
$ cd ./dotfiles
```
you loose those permissions:
```
$ stat -c '%a' dotfiles/tmp/x
664
```
that are crucial for `.ssh/config`.

**Comment by deadc0de6** [comment]
Right, yeah I see the potential mess that could do.

What I would suggest is to implement the `chmod` entry suggested by @billop which will be automatically filed on new file imported. If not present or empty, dotdrop will fall back to the permissions of the file in the *dotpath* (back-compatibility). The user could then be free to change it in the config (add it, change value) if he/she wishes to.

Does that sound like a solution, @scrool @billop any other suggestions on how to add this to dotdrop?

**Comment by scrool** [comment]
I guess it might be not a good idea to always add permissions. I propose following:

Add an option to `dotdrop import` to preserve permissions. In that case it would write permissions in the config file.
o make it more user friendly it could do that automatically even if the option is not set - check current `umask` against file permissions and if they doesn't match (which is the case e.g. for that ssh config file) it would add permissions.

**Comment by deadc0de6** [comment]
Ok:

* add a new cli switch to preserve permission on import (would add the `chmod` entry in the config), no switch provided, no `chmod` added
* on install
  * if no `chmod` entry and `umask` doesn't match file on filesystem, ask the user for what permissions to apply (won't happen if file doesn't exist on the filesystem)
  * if no `chmod` and `umask` match: go on as usual
  * if `chmod`, install and chmod file (discard any existing permissions if a file exists on the filesystem)
* on compare `chmod` entry takes precedence over permissions in *dotpath* if set

A `chmod` entry applied to a directory will be applied to the directory itself (not its children). If one wants more control over directory content (in term of permissions), one would need to import the files independently.

Sounds the above right?

**Comment by scrool** [comment]
Sounds good to me. One more - maybe `update` could do the same as import?

**Comment by deadc0de6** [comment]
Absolutely `update` would behave like `import`.
I'll start working on this and keep you posted when I have something concrete.

**Comment by deadc0de6** [comment]
@billop would the above solution work for you?

**Comment by billop** [comment]
@deadc0de6 that sounds great, definitely what I had in mind.

**Comment by deadc0de6** [comment]
@scrool @billop `chmod` is implemented in the [chmod branch](https://github.com/deadc0de6/dotdrop/tree/chmod). The related documentation is available [here](https://github.com/deadc0de6/dotdrop/blob/chmod/docs/config.md#permissions) and [here](https://github.com/deadc0de6/dotdrop/blob/chmod/docs/config-format.md#dotfiles-entry).

It should work for `import`, `install`, `compare` and `update`. I implemented many tests that hopefully cover all use-cases :sweat_smile:. However I'd be thankful if you could give it a try so that I have another sets of tests to confirm that everything is working as expected.

Thanks a lot for your help!

**Comment by scrool** [comment]
Import works great.

--

Update behaves as documented. But I have some comments to those: let's say I originally imported file with inocorrect permissions. I haven't noticed that until a program that expected that file fails. I fix a permission. Next time I run `update` I'm asked to overwrite a file.

I guess it might be nice to see that difference was found in permissions only. 

File permissions are set as documented. But if I try add that file to git it won't see any update (because only chmod changed). And even later when I try to install that configuration on some other machine from git checkout I will run into the same situation as the beginning of this paragraph - because permissions are not (re)stored.

---

With install of a file that differs in permissions I'm asked:

```
Mode differs (664 and 644 (/home/user/.file), continue [y/N] ?
```

I'm not sure what is the permission of the existing file and what mode will be set. Could it be something like:
```
Set mode 664 of "/home/user/.file" [y/N] ?
```

which would be consistent to other question:
```
Overwrite "/home/user/.otherfile" [y/N] ?
```

---

For installation with chmod it is surprising that the file is considered to be always different so it has to be backed up:
```
$ umask
022
$ install -m 777 /dev/null ~/777
$ stat -c '%a' ~/777
777
$ touch ~/a
$ stat -c '%a' ~/a
644
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg $PWD/config.yaml import ~/777
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg $PWD/config.yaml import ~/a
$ cat config.yaml 
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
dotfiles:
  f_777:
    src: '777'
    dst: ~/777
    chmod: '777'
  f_a:
    src: a
    dst: ~/a
profiles:
  ponyo:
    dotfiles:
    - f_777
    - f_a
$ stat -c '%a' dotfiles/777 
777
$ stat -c '%a' dotfiles/a 
644
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg $PWD/config.yaml install
backup /home/user/777 to /home/user/777.dotdropbak
	-> copied /home/user/dotdrop-chmod/dotfiles/777 to /home/pbabinca/777

1 dotfile(s) installed.
```

But `compare` doesn't see any differences there.

---

I haven't tested directories as I'm don't have an use case for that for now.

**Comment by deadc0de6** [comment]
Thanks for the review!
* fixed the question and followed your recommendation: `Set mode <mode> to "<file>" [y/N] ?`
* fixed the re-installation of file when no mode changed (and add test for this use-case)

I will see how I can fix your request regarding `update`. It makes sense but until now updates didn't change the config at all (it only handled files) so either I integrate config changes in `update` or I find another way. I'll keep you posted.

**Comment by deadc0de6** [comment]
Ok, now `update` will add a `chmod` entry in the dotfile when the permissions are different.

**Comment by billop** [comment]
One thing I've noticed so far is that for `install` given a chmod entry that conflicts with the pre-existing file/directory:

- for a directory it just changes permission
- for a file it copies the file

I think for a file it should just update the permission rather than copying the file.

This serves two purposes:
1. making sure backups always differ by file content, not permission
2. making it clear that all dotdrop install did was update permission (practically speaking)

The second point also applies to directories I think, right now it silently updates permissions but I think it should just mention what it did.

**Comment by deadc0de6** [comment]
@scrool @billop I have the feeling the basic features for chmod are ready [in the chmod branch](https://github.com/deadc0de6/dotdrop/tree/chmod). So unless you have other requests I'm planning to merge that into master soon. Thanks again for your help!

**Comment by scrool** [comment]
I'll try to test your new changes today.

**Comment by scrool** [comment]
This is my initial testing setup:
```yaml
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
dotfiles:
profiles:
```

```
$ umask
022
$ cd ~/dotdrop-chmod/dotdrop 
$ git pull                  
Already up to date.
```

1. Initial import
```
$ touch ~/a   
$ stat -c '%a' ~/a
644
$ install -m 777 /dev/null ~/777
$ stat -c '%a' ~/777
777
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg ~/dotdrop-chmod/config.yaml import ~/a
	-> "/home/user/a" imported

1 file(s) imported.
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg ~/dotdrop-chmod/config.yaml import ~/777
	-> "/home/user/777" imported

1 file(s) imported.
$ DOTDROP_AUTOUPDATE=no ~/dotdrop.sh --cfg ~/dotdrop-chmod/config.yaml install       
	-> install /home/user/dotdrop-chmod/dotfiles/a to /home/user/a
	-> install /home/user/dotdrop-chmod/dotfiles/777 to /home/user/777

2 dotfile(s) installed.
$ stat -c '%a' ~/777       
777
$ stat -c '%a' ~/a
644
```

:+1: 

2. Restore permissions:
```
$ chmod 0222 ~/777 
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg ~/dotdrop-chmod/config.yaml install
Overwrite "/home/user/777" [y/N] ? y
backup /home/user/777 to /home/user/777.dotdropbak
	-> install /home/user/dotdrop-chmod/dotfiles/777 to /home/user/777

1 dotfile(s) installed.
```

I understand `dotdrop` is not able to read the file so it is fine that won't compare it and just overwrite. There is no obvious message about chmod though. I guess that's fine?

3. If file in dotfiles is unreadable it cannot be easily updated:
```
$ chmod 0222 ~/dotdrop-chmod/dotfiles/777
$ stat -c '%a' ~/dotdrop-chmod/dotfiles                                                                  
755
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg ~/dotdrop-chmod/config.yaml update ~/777
Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/workspace/dotdrop/dotdrop/dotdrop.py", line 840, in <module>
    if main():
  File "/home/user/workspace/dotdrop/dotdrop/dotdrop.py", line 805, in main
    ret = cmd_update(o)
  File "/home/user/workspace/dotdrop/dotdrop/dotdrop.py", line 463, in cmd_update
    if _dotfile_update(o, path, key=iskey):
  File "/home/user/workspace/dotdrop/dotdrop/dotdrop.py", line 85, in _dotfile_update
    return updater.update_path(path)
  File "/home/user/workspace/dotdrop/dotdrop/updater.py", line 71, in update_path
    if not self._update(path, dotfile):
  File "/home/user/workspace/dotdrop/dotdrop/updater.py", line 114, in _update
    ret = self._handle_file(new_path, dtpath)
  File "/home/user/workspace/dotdrop/dotdrop/updater.py", line 213, in _handle_file
    if compare and filecmp.cmp(path, dtpath, shallow=False) and \
  File "/usr/lib64/python3.7/filecmp.py", line 62, in cmp
    outcome = _do_cmp(f1, f2)
  File "/usr/lib64/python3.7/filecmp.py", line 75, in _do_cmp
    with open(f1, 'rb') as fp1, open(f2, 'rb') as fp2:
PermissionError: [Errno 13] Permission denied: '/home/user/dotdrop-chmod/dotfiles/777'
```

I understand why this is happening - file is unreadable. It might nice to fail better but I can't think of an use case where I'd normally run into this.

4. File with non-standard, but readable permissions:
```
$ install -m 654 /dev/null ~/654
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg=/home/user/dotdrop-chmod/config.yaml import ~/654
	-> "/home/user/654" imported

1 file(s) imported.
$  cat ~/dotdrop-chmod/config.yaml
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
dotfiles:
  f_a:
    src: a
    dst: ~/a
  f_777:
    src: '777'
    dst: ~/777
    chmod: '777'
  f_654:
    src: '654'
    dst: ~/654
    chmod: '654'
profiles:
  ponyo:
    dotfiles:
    - f_a
    - f_777
    - f_654
$ chmod 0666 ~/dotdrop-chmod/dotfiles/654
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg=/home/user/dotdrop-chmod/config.yaml update ~/654
Overwrite "/home/user/dotdrop-chmod/dotfiles/654" with "/home/user/654"? [y/N] ? y
	-> "/home/user/dotdrop-chmod/dotfiles/654" updated

1 file(s) updated.
```

:+1: 

5. Restore wrong permisions:
```
$ chmod 0666 ~/a ~/654 ~/777
$ cat ~/dotdrop-chmod/config.yaml                                                                                 
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
dotfiles:
  f_a:
    src: a
    dst: ~/a
  f_777:
    src: '777'
    dst: ~/777
    chmod: '777'
  f_654:
    src: '654'
    dst: ~/654
    chmod: '654'
profiles:
  ponyo:
    dotfiles:
    - f_a
    - f_777
    - f_654
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg ~/dotdrop-chmod/config.yaml install
Overwrite "/home/user/a" [y/N] ? y
backup /home/user/a to /home/user/a.dotdropbak
	-> install /home/user/dotdrop-chmod/dotfiles/a to /home/user/a
Overwrite "/home/user/777" [y/N] ? y
backup /home/user/777 to /home/user/777.dotdropbak
	-> install /home/user/dotdrop-chmod/dotfiles/777 to /home/user/777
Overwrite "/home/user/654" [y/N] ? y
backup /home/user/654 to /home/user/654.dotdropbak
	-> install /home/user/dotdrop-chmod/dotfiles/654 to /home/user/654
	-> chmod /home/user/654 to 654

3 dotfile(s) installed.
```
I'm not sure why I don't see chmod for `777` which had incorrect permissions as well and has `chmod` directive.

6. `chmod` is set on update:
```
$ chmod 0666 ~/a
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg=/home/user/dotdrop-chmod/config.yaml update ~/a  
Overwrite "/home/user/dotdrop-chmod/dotfiles/a" with "/home/user/a"? [y/N] ? y
	-> "/home/user/dotdrop-chmod/dotfiles/a" updated

1 file(s) updated.
$ cat ~/dotdrop-chmod/config.yaml                                                                               
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
dotfiles:
  f_a:
    src: a
    dst: ~/a
    chmod: '666'
  f_777:
    src: '777'
    dst: ~/777
    chmod: '777'
  f_654:
    src: '654'
    dst: ~/654
    chmod: '654'
profiles:
  ponyo:
    dotfiles:
    - f_a
    - f_777
    - f_654
```

:+1: 

In overall I don't see big issue in any of those tests but if you feel that needs to be explained or fix it I'd be glad. :smile:

**Comment by scrool** [comment]
Only now I remembered to test `compare`. 
```
$ chmod 0666 ~/a ~/654 ~/777                                                                                    
$ cat ~/dotdrop-chmod/config.yaml             
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
dotfiles:
  f_a:
    src: a
    dst: ~/a
  f_777:
    src: '777'
    dst: ~/777
    chmod: '777'
  f_654:
    src: '654'
    dst: ~/654
    chmod: '654'
profiles:
  ponyo:
    dotfiles:
    - f_a
    - f_777
    - f_654
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg ~/dotdrop-chmod/config.yaml compare
	-> create directory /tmp/dotdrop-07n55x5m/home/user
=> compare f_777: diffing with "/home/user/777"
modes differ (777 vs 666)
	-> chmod /tmp/dotdrop-07n55x5m/home/user/654 to 654
=> compare f_654: diffing with "/home/user/654"
modes differ (654 vs 666)

3 dotfile(s) compared.
ponyo:~ $ 
```

It correctly detects permissions that differ from `chmod` version. :+1: 

It looks strange that it prints creation of directory and chmod even though I wanted to do only compare. And it does not do so for file that is supposed to have mode 777.

---

One more thing about comare - I'm not sure what is its primary idea - to list files which would be updated on `install` or which needs to be updated with `update`?

File `~/a` does not have `chmod` attribute so on install its mode is not updated:
```
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg ~/dotdrop-chmod/config.yaml install f_a

0 dotfile(s) installed.
```

on the other hand update:
```
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg=/home/user/dotdrop-chmod/config.yaml update ~/a

1 file(s) updated.
```
updated chmod on the file:
```
$ stat -c '%a' ~/dotdrop-chmod/dotfiles/a
666
```
but didn't add entry to a config:
```
$ cat ~/dotdrop-chmod/config.yaml
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
dotfiles:
  f_a:
    src: a
    dst: ~/a
  f_777:
    src: '777'
    dst: ~/777
    chmod: '777'
  f_654:
    src: '654'
    dst: ~/654
    chmod: '654'
profiles:
  ponyo:
    dotfiles:
    - f_a
    - f_777
    - f_654
```

I'm not sure how wrong is that though.

---

And now one more operation:
```
$ DOTDROP_AUTOUPDATE=no ~/workspace/dotdrop/dotdrop.sh --cfg ~/dotdrop-chmod/config.yaml files     
Dotfile(s) for profile "ponyo":
f_a
	-> dst: /home/user/a
	-> src: /home/user/dotdrop-chmod/dotfiles/a
	-> link: nolink
	-> chmod: None
f_777
	-> dst: /home/user/777
	-> src: /home/user/dotdrop-chmod/dotfiles/777
	-> link: nolink
	-> chmod: 511
f_654
	-> dst: /home/user/654
	-> src: /home/user/dotdrop-chmod/dotfiles/654
	-> link: nolink
	-> chmod: 428

```
Those chmods should be probably printed as octal values. And I guess if there is no `chmod` it should be listed there.

**Comment by deadc0de6** [comment]
@scrool thanks very much for the review, much appreciated!

* (2) I fixed this and the chmod message will now be displayed
* (3) this is a very unusual use-case and probably won't happen much so I'd rather keep the entire traceback
* (5) this is fixed
* `compare`
  * the extra *create directory* has been fixed
  * `compare` is used to primarily for `install` but could as well be used for `update` 
  * the chmod is not added since the file on its destination (`~/a`) is the same as the one in the *dotpath* (`~/dotdrop-chmod/dotfiles/a`). A `chmod` entry is only added if the two files' permissions differ
* `files` the chmod value are now printed in octal

**Comment by scrool** [comment]
I _think_ you might have missed my last comment in (now numbered) 7th:

> And it does not do so for file that is supposed to have mode 777.

At the beginning of seventh test I make permissions mismatch with anything set in a config file (and I _hope_ also different from what I get with standard umask).

But file 777 does not seem to get its change of permission printed.

**Comment by deadc0de6** [comment]
Thanks that is now fixed!

**Comment by deadc0de6** [comment]
The chmod branch was merged into master. Feel free to open a new issue if anything is not working as expected.
This will be part of the next release.

Thanks again both for your help and patience!

**Comment by deadc0de6** [comment]
New version is out: [v1.4.0](https://github.com/deadc0de6/dotdrop/releases/tag/v1.4.0)
