### ISSUE TITLE
[help] python-magic not resolving

### ISSUE THREAD

**Issue by daniel-white** [deadc0de6/dotdrop#290]
**What I am trying to achieve**
I have an existing install on Mac. Last week when I ran my dotdrop install, some of the pip packages weren't working so I thought I'd force a reinstall. Right now its synching  and can't find python-magic.

```
Submodule path 'dotdrop': checked out 'e9bbafa51f5783aaafb8d13a677a409de799115e'
Submodule path 'dotdrop': checked out '55a14b0762ac6772a642ffb5028824fcaf940146'
[ERR] missing python module python-magic 
```

**What I have tried so far**
Removed my cache then `pip3 install -r dotdrop/requirements.txt --user`

**Comment by deadc0de6** [comment]
What you tried should have fixed it. 

Through 55a14b0762ac6772a642ffb5028824fcaf940146 I am making sure the magic module has the function `from_file` (to avoid issues like https://github.com/deadc0de6/dotdrop/issues/289), maybe that's what is failing.

Can you try the following and make sure `from_file` is in the lists of attributes?
```bash
$ python3 -c 'import magic; print(hasattr(magic, "from_file"))'
```

Also a `pip3 freeze | grep -i magic` to make sure `python-magic` is installed.

**Comment by daniel-white** [comment]
No dice:

```
❯ python3 -c 'import magic; print(hasattr(magic, "from_file"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/daniel/Library/Python/3.9/lib/python/site-packages/magic.py", line 201, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
```

```
❯ pip3 freeze | grep -i magic
python-magic==0.4.18
```

then I ran `pip3 install libmagic` which installed it into my library pip cache.

Then I got this:

```
❯ dfu
Submodule path 'dotdrop': checked out 'e9bbafa51f5783aaafb8d13a677a409de799115e'
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 54 (delta 41), reused 41 (delta 28), pack-reused 0
Unpacking objects: 100% (54/54), 6.25 KiB | 156.00 KiB/s, done.
From https://github.com/deadc0de6/dotdrop
   a6ba5d9..36be202  chmod      -> origin/chmod
   55a14b0..263d7f7  master     -> origin/master
Submodule path 'dotdrop': checked out '263d7f744f4a7b0d02dc81c360d64c3b5d30af24'
[ERR] missing python module python-magic 
```

`dfu` is my shorthand to update

**Comment by deadc0de6** [comment]
Can you try `brew install libmagic`?

**Comment by deadc0de6** [comment]
Could it be related to this?

* <http://www.brambraakman.com/blog/comments/installing_libmagic_in_mac_os_x_for_python-magic/>
* <https://stackoverflow.com/questions/59432711/why-is-module-python-magic-not-available>

The brew libmagic: <https://formulae.brew.sh/formula/libmagic>

**Comment by romariolopezc** [comment]
Mine solved with `brew install libmagic`

**Comment by deadc0de6** [comment]
@romariolopezc awesome, I'll add this to the doc

**Comment by daniel-white** [comment]
@deadc0de6 yep that worked for me too

**Comment by deadc0de6** [comment]
cool, new dependencies listed [in the doc](https://dotdrop.readthedocs.io/en/latest/installation/#dependencies).

**Comment by deadc0de6** [comment]
Also dotdrop will fallback to using `file` in case the module is not found but will warn you. 

For anyone coming back here, the solution on Mac is
```bash
$ pip install --user python-magic
$ brew install libmagic
```

**Comment by tbentley-mdsol** [comment]
I've tried the steps listed by deadc0de6 for the Mac and it no longer works.
I still get the resolution error.

**Comment by deadc0de6** [comment]
@tbentley-mdsol can you provide me with more info on your system, what was the error message, what you've tried and what were the outputs?

**Comment by tbentley-mdsol** [comment]
I'm running on a MacOS Sonoma 14.5, Apple M2 Max chip.
Python 2.7.18
python-magic 0.4.15
libmagic 5.45; installed with homebrew and located in /opt/homebrew/Cellar/libmagic
Used mkvirtualenv to create virtual environment for python development.
pip 20.3.4

I have tried
```
$ pip install --user python-magic
$ brew install libmagic
export DYLD_LIBRARY_PATH=/opt/homebrew/Cellar/libmagic/5.45/lib:/opt/homebrew/Cellar/libmagic/5.45
export LD_LIBRARY_PATH=/opt/homebrew/Cellar/libmagic/5.45/lib:/opt/homebrew/Cellar/libmagic/5.45:$LD_LIBRARY_PATH
```
I've tried running the unit tests via tox (2.2.1) and paver (1.2.4).

Regardless of what I tried I get the error below are a similar variation that complains of the import:
```
======================================================================
ERROR: Failure: ImportError (failed to find libmagic.  Check your installation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/aUser/repos/omaha-server/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/aUser/repos/omaha-server/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/aUser/repos/omaha-server/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/aUser/repos/omaha-server/omaha_server/feedback/tests/test_utils.py", line 5, in <module>
    from feedback.utils import get_file_extension
  File "/Users/aUser/repos/omaha-server/omaha_server/feedback/utils.py", line 2, in <module>
    import magic
  File "/Users/aUser/repos/omaha-server/.tox/py27/lib/python2.7/site-packages/magic.py", line 181, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

======================================================================
ERROR: Failure: ImportError (failed to find libmagic.  Check your installation)
----------------------------------------------------------------------
```

**Comment by tbentley-mdsol** [comment]
I just realized this was a ticket for dotdrop and not libmagic.  I'll leave my previous comment.

**Comment by deadc0de6** [comment]
@tbentley-mdsol This is dotdrop but I'm not sure how the above applies to dotdrop tbh. Moreover it seems you're using python 2.7 which is not supported. Can you try with a more recent version of python that is supported by dotdrop?

**Comment by tbentley-mdsol** [comment]
> @tbentley-mdsol This is dotdrop but I'm not sure how the above applies to dotdrop tbh. Moreover it seems you're using python 2.7 which is not supported. Can you try with a more recent version of python that is supported by dotdrop?

Please ignore my posts since they apply to a different library.   You should be able to close this ticket again since my issue is unrelated to dotdrop, as I said in my post just before your last post.  Thanks.
