### ISSUE TITLE
[feature] Import Ignores and Named Pipes

### ISSUE THREAD

**Issue by vikigenius** [deadc0de6/dotdrop#294]
I would like to have a feature equivalent to .gitignore for importing.

My use case is specifically that some of my config directories have some service directories in them that have named pipes, fifos etc. and importing them actually throws an shutil error. I don't want to copy these files anyway.
So it would be very useful to have a directory wide .gitignore like file where I can specify ignore patterns, and when importing those patterns should be ignored.

For example, say I have the following directory structure:

```
sv
  .gitignore
  spotifyd
    config
    supervise
      ok # This is a named pipe, should be ignored.
  picom
    config
    supervise
      ok # This is a named pipe, should be ignored.
```

I would like to import the sv directory and ignore the supervise subdirectory from being imported.
For example: with .gitignore in the sv directory I want to exclude every directory called supervise
```
# ignore the supervise directory
supervise/
```

Because without this feature dotdrop import will fail with the following error message:

```
Traceback (most recent call last):
  File "/home/void/.local/bin/dotdrop", line 8, in <module>
    sys.exit(main())
  File "/home/void/.local/pipx/venvs/dotdrop/lib/python3.9/site-packages/dotdrop/__init__.py", line 11, in main
    if dotdrop.dotdrop.main():
  File "/home/void/.local/pipx/venvs/dotdrop/lib/python3.9/site-packages/dotdrop/dotdrop.py", line 737, in main
    ret = cmd_importer(o)
  File "/home/void/.local/pipx/venvs/dotdrop/lib/python3.9/site-packages/dotdrop/dotdrop.py", line 452, in cmd_importer
    shutil.copytree(dst, srcf)
  File "/usr/lib/python3.9/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib/python3.9/shutil.py", line 510, in _copytree
    raise Error(errors)
shutil.Error: [('/home/void/.config/sv/spotifyd/supervise/ok', '/home/void/dotfiles/dotfiles/config/sv/spotifyd/supervise/ok',
'`/home/void/.config/sv/spotifyd/supervise/ok` is a named pipe'), ('/home/void/.config/sv/picom/supervise/ok', 
'/home/void/dotfiles/dotfiles/config/sv/picom/supervise/ok', '`/home/void/.config/sv/picom/supervise/ok` is a named pipe')] 
```

**Comment by deadc0de6** [comment]
Would something similar to `instignore`, `cmpignore` and `upignore` during import work for you (see [ignore-patterns](https://dotdrop.readthedocs.io/en/latest/config/#ignore-patterns))?

I will also clean a bit the error raised when the file is a named pipe (and warn the user while still continuing importing).

**Comment by deadc0de6** [comment]
Above commit should fix the issue with named pipes. It will still print an error message saying the file couldn't be imported but the rest will be successfully imported.
```bash
[ERR] importing "/tmp/testdir/with_named_pipe/fifo" failed: `/tmp/testdir/with_named_pipe/fifo` is a named pipe
```

**Comment by vikigenius** [comment]
Hmm, @deadc0de6 something similar to instignore etc. does sound simpler. But wouldn't that be pointless since by the time you have the entry in the config file, you have already imported it anyway? I was thinking an approach similar to .gitignore (using a top level file in the directory for exclusion)  was more appropriate or maybe even a command line option for ignoring patterns in dotdrop import.

**Comment by deadc0de6** [comment]
I would implement both (cli and config entry) in the same idea as `cmpignore` for example. That means a command line switch (`-i --ignore=<pattern>`) as well as a **global** entry in the config that would define what is always ignored when importing.

For example to ignore a *supervise* directory you could either specify the pattern in the command line:
```bash
dotdrop import -i '*/supervise' ~/somedir
```

or by having it in the config file
```yaml
config:
  impignore:
  - '*/supervise'
...
```

Sounds good to you?

**Comment by vikigenius** [comment]
@deadc0de6  That sounds great. Although let us make sure that using the command line option doesn't really add it to the global section so that the cli option can stay as a one time option.

**Comment by deadc0de6** [comment]
I have the feature implemented in the [impignore branch](https://github.com/deadc0de6/dotdrop/tree/impignore). Can you give a try and let me know if that matches your expectations?

**Comment by vikigenius** [comment]
@deadc0de6 It seems to work well. Thanks.

**Comment by deadc0de6** [comment]
This has been merged into master and will part of the next release.
