### ISSUE TITLE
[feature] bundle some syntax highlighting

### ISSUE THREAD

**Issue by lelgenio** [deadc0de6/dotdrop#305]
I like colorful stuff!
Since dotdrop uses different delimiters from default jinja, maybe we should include some highlighting for popular text editors.

I made some naive highlighters for kakoune:
```bash
hook global WinCreate .* %{
    require-module python
    add-highlighter window/dotdrop regions

    add-highlighter window/dotdrop/expression region '\{\{@[@]' '[@]@\}\}' group
    add-highlighter window/dotdrop/statement  region  '\{%@[@]' '[@]@%\}' group
    add-highlighter window/dotdrop/comment    region  '\{#@[@]' '[@]@#\}' fill comment

    add-highlighter window/dotdrop/expression/ fill variable
    add-highlighter window/dotdrop/statement/  fill variable

    add-highlighter window/dotdrop/expression/ ref python
    add-highlighter window/dotdrop/statement/  ref python

    add-highlighter window/dotdrop/expression/ regex '\{\{@[@]|[@]@\}\}' 0:block
    add-highlighter window/dotdrop/statement/  regex  '\{%@[@]|[@]@%\}' 0:block
    add-highlighter window/dotdrop/statement/  regex 'endfor|endif' 0:keyword
}
```
![image](https://user-images.githubusercontent.com/31388299/113093520-722c7380-91c6-11eb-9d87-5ab40136c407.png)

maybe it would be easy to create this for other editors using existing jiinja highlighters.

**Comment by deadc0de6** [comment]
oh very cool! Thanks for sharing!

If it's ok with you, I'll add an highlight directory with this.

**Comment by lelgenio** [comment]
Sure! just know this is not the most correct of sollutions. If you want to ship this i could improve it later.

**Comment by deadc0de6** [comment]
I have added this [here](https://github.com/deadc0de6/dotdrop/tree/master/highlighters). Feel free to make a PR if you want to change stuff.

I also references it [in the doc](https://dotdrop.readthedocs.io/en/latest/installation/#highlighters).

Thanks again for your contribution!
