### ISSUE TITLE
[bug] snap warnings

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#308]
snap version dotdrop 1.5.3 
every dotdrop command is prepended with 

```
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
/etc/magic, 0: Warning: using regular magic file `/usr/share/misc/magic'
```

regards

**Comment by deadc0de6** [comment]
Apparently this only appears when using dotdrop on snap. Can you confirm it doesn't happen when using from the git repository?

Did it happened with the last update?

TBH I'm far from a snap expert and don't really know who is actually dropping those lines.

**Comment by deadc0de6** [comment]
It seems that by defining the following environment variable, the warnings go away:
```bash
export MAGIC=$SNAP/usr/share/file/magic.mgc
```

However I'm not sure why...

**Comment by deadc0de6** [comment]
I have documented that here: <https://dotdrop.readthedocs.io/en/latest/installation/#snap-package>
