### ISSUE TITLE
[help] sudo dotdrop install system-wide configuration files

### ISSUE THREAD

**Issue by Syusyuly** [deadc0de6/dotdrop#311]
**What I am trying to achieve**
When using dotdrop to manage system-wide configuration files, dotdrop install requires administrator privileges. I would like to know which of the following three is the best solution.

**What I have tried so far**

 1.
```
sudo pip3 install dotdrop
sudo dotdrop instlal
```
It is known that `sudo pip3 install` has certain security risks

2.
```
pip3 install dotdrop --user
sudo <dotdrop_path> install
```

dotdrop is essentially a simple Python script that cannot be used standalone without relying on the Python environment

It will generate the following error message
```
Traceback (most recent call last):
  File "/home/shiro/.local/bin/dotdrop", line 5, in <module>
    from dotdrop import main
ModuleNotFoundError: No module named 'dotdrop
```

3.
```
git clone https://github.com/deadc0de6/dotdrop.git
...
build dotdrop.sh
...
sudo <dotdrop.sh_path> install
```

This works, but I prefer to use an standalone executable rather than a shell script.

Would you consider packaging dotdrop with individual executables for each of the major distributions? I believe this would be more attractive than snap or dotdrop.sh. It is well known that snap does not work with WSL, and dotdrop.sh is built with a dependency on Python, for which there may not be enough space on some systems.

**Comment by deadc0de6** [comment]
To answer your initial question, I would recommend to use/install dotdrop in a virtualenv for managing system dotfiles:

* in a virtualenv, see [this doc](https://dotdrop.readthedocs.io/en/latest/installation/#pypi-package-in-a-virtualenv)
* as a submodule in a virtualenv, see [this doc](https://dotdrop.readthedocs.io/en/latest/installation/#as-a-submodule-in-a-virtualenv)

Both solutions avoid to mess with your systems' libraries (thanks to virtualenv).

I'm not a Windows user but what is not working with dotdrop in WSL?

**Comment by Syusyuly** [comment]
But when I run sudo, the virtualenv environment variables, aliases, functions, etc aren't being carried over. Could you please tell me more about it?

**Comment by deadc0de6** [comment]
Sure:
```bash
## create virtualenv for dotdrop
$ cd /tmp/
$ virtualenv -p python3 env
$ source env/bin/activate
$ pip install dotdrop

## create repository
$ mkdir dotfiles
$ wget https://raw.githubusercontent.com/deadc0de6/dotdrop/master/config.yaml

## import files as sudo
$ sudo /tmp/env/bin/dotdrop import /etc/resolv.conf
```

Another way to do it, which is cleaner IMHO, is to use dotdrop as a submodule. You would then simply use `sudo` and a different config files for the system dotfiles (see [this doc](https://dotdrop.readthedocs.io/en/latest/howto/system-config-files/)).

**Comment by deadc0de6** [comment]
I'm closing this hoping you got your issue solved. Feel free to re-open if you have other questions.
