### ISSUE TITLE
[help] submodules as dotfiles

### ISSUE THREAD

**Issue by japalvia** [deadc0de6/dotdrop#313]
**What I am trying to achieve**
I am evaluating if I can switch from plain git repo to dotdrop for managing my configs. These include also plugins for vim and tmux. I deploy my setup on several environments where I cannot rely on distro package managers (software not in repo or no permissions to install). Hence, I pull the plugins from github during bootstrapping. 

Example: [tmux plugin manager](https://github.com/tmux-plugins/tpm) is cloned to path `~/.tmux/plugins/tpm/` and managed as git submodule in my existing setup. Is there any recommended way to integrate managing tpm installation into dotdrop? Or should I keep it outside `config.yaml` and simply handle it as before (git submodule)?

**What I have tried so far**
I've read through the documentation and found nothing for my use case.

**Comment by deadc0de6** [comment]
Well first of all, dotdrop is to be used on top of a plain git repo, so you could of course use dotdrop as a submodule next to your current solution (with other tools/plugins as submodules). Dotdrop provides different solution to *deploy* a tool using [actions](https://dotdrop.readthedocs.io/en/latest/config-details/#entry-actions). 

You could for example bind the installation of `tmux` config file with an action that would install tpm before installing the config file. See the example of installation of vim-plug [here](https://dotdrop.readthedocs.io/en/latest/config-details/#dotfile-actions). You could even bind the action to a [specific profile](https://dotdrop.readthedocs.io/en/latest/config-details/#profile-actions) or [using fake dotfiles](https://dotdrop.readthedocs.io/en/latest/config-details/#fake-dotfile-and-actions) depending on your use-case.

In the end you could either keep those tools/plugins as submodules (where updating submodules could even be bound to some actions) or even pull them dynamically on dotfiles installation/updates (like in the vim-plug example). Both solutions are doable with dotdrop.

I hope this answers your question but If you need help or want more examples on how to do that, just ask, I'd be happy to help.

**Comment by japalvia** [comment]
Thanks for the explanation, I can see the problem from the right perspective now. I think I will go with dotfile actions for the sake of simplicity.
