### ISSUE TITLE
Python3: command not found! / Set default python command

### ISSUE THREAD

**Issue by Lilja** [deadc0de6/dotdrop#320]
Dotdrop version (and git commit if run from source): v1.7.0
Using dotdrop: as a submodule

**Describe the bug**

`python3` not found. But my `python` executable is `3.8.0`

**Steps to Reproduce**
Have a python executable but not a python3 one.

**Expected behavior**
N/A

**Additional information**

<details>

<summary>Shell commands</summary>

Erik Lilja@DESKTOP MINGW64 ~/dotfiles (master)
$ git submodule add https://github.com/deadc0de6/dotdrop.git
Cloning into 'C:/Users/Erik Lilja/dotfiles/dotdrop'...
Enter passphrase for key '/c/Users/Erik Lilja/.ssh/id_rsa':
remote: Enumerating objects: 7248, done.
remote: Counting objects: 100% (539/539), done.
remote: Compressing objects: 100% (368/368), done.
remote: Total 7248 (delta 334), reused 339 (delta 165), pack-reused 6709
Receiving objects: 100% (7248/7248), 1.53 MiB | 3.84 MiB/s, done.
Resolving deltas: 100% (5225/5225), done.
warning: LF will be replaced by CRLF in .gitmodules.
The file will have its original line endings in your working directory

Erik Lilja@DESKTOP MINGW64 ~/dotfiles (master)
$ pip install -r dotdrop/requirements.txt --user
Requirement already satisfied: Jinja2 in c:\users\erik lilja\appdata\local\programs\python\python38\lib\site-packages (from -r dotdrop/requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: docopt in c:\users\erik lilja\appdata\local\programs\python\python38\lib\site-packages (from -r dotdrop/requirements.txt (line 2)) (0.6.2)
Requirement already satisfied: ruamel.yaml in c:\users\erik lilja\appdata\local\programs\python\python38\lib\site-packages (from -r dotdrop/requirements.txt (line 3)) (0.17.16)
Requirement already satisfied: python-magic in c:\users\erik lilja\appdata\local\programs\python\python38\lib\site-packages (from -r dotdrop/requirements.txt (line 4)) (0.4.24)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\erik lilja\appdata\local\programs\python\python38\lib\site-packages (from Jinja2->-r dotdrop/requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2 in c:\users\erik lilja\appdata\local\programs\python\python38\lib\site-packages (from ruamel.yaml->-r dotdrop/requirements.txt (line 3)) (0.2.6)

Erik Lilja@DESKTOP MINGW64 ~/dotfiles (master)
$ ./dotdrop/bootstrap.sh

Erik Lilja@DESKTOP MINGW64 ~/dotfiles (master)
$ ./dotdrop.sh
fatal: Unable to fetch in submodule path 'dotdrop'
./dotdrop.sh: line 32: python3: command not found

Erik Lilja@DESKTOP MINGW64 ~/dotfiles (master)
$ ./dotdrop.sh --version
Enter passphrase for key '/c/Users/Erik Lilja/.ssh/id_rsa':
./dotdrop.sh: line 32: python3: command not found

Erik Lilja@DESKTOP MINGW64 ~/dotfiles (master)

</details>

**Comment by Lilja** [comment]
Your([1](https://github.com/deadc0de6/dotdrop/issues/268), [2](https://github.com/deadc0de6/dotdrop/issues/283)) favorite windows tester is back! I tested to use this as a submodule since I got segmentation faults when I installed dotdrop again with pip. Would you like an issue with that as well maybe?

**Comment by deadc0de6** [comment]
You can solve this like that:
```bash
sudo ln -s `which python` /usr/bin/python3
```

It will create a `python3` symlink pointing to `python` in `/usr/bin`.

**Comment by deadc0de6** [comment]
You got a segmentation fault when using pip? I'm not sure how that can happen but if pip is segfaulting then you should submit your issue to [pip](https://github.com/pypa/pip).

**Comment by deadc0de6** [comment]
Unless the issue is not while installing dotdrop with pip but when using dotdrop. In that case, of course you can create a new issue or put it in this very issue if you want.

**Comment by Lilja** [comment]
Hmm. Let's see here:

I copied python executable to `python3`, so now `python3` works. However, there seems to be some weird issue, even only using the shell script:

<details>

<summary>Logs</summary>

Erik Lilja@DESKTOP MINGW64 ~/dotfiles (master)
$ ./dotdrop.sh
Enter passphrase for key '/c/Users/Erik Lilja/.ssh/id_rsa':
./dotdrop.sh: line 32:  3181 Segmentation fault      PYTHONPATH=dotdrop python3 -m dotdrop.dotdrop "${args[@]}"

Erik Lilja@DESKTOP MINGW64 ~/dotfiles (master)
$ python3
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit
Use exit() or Ctrl-Z plus Return to exit
>>> exit()

</details>

**Comment by deadc0de6** [comment]
Indeed, it looks like python3 segfaults when running dotdrop. Do you have other issues when using python on your host?
Not sure how to help without more info. Are you able to get a core dump or some logs on what makes python crash?

**Comment by Lilja** [comment]
Not sure about core dumps, but I can offer you prints inside the dotdrop-code.

![image](https://user-images.githubusercontent.com/6134511/135163386-e549a4a7-5529-4e7e-8a72-ec1f3d8c2314.png)

```
Erik Lilja@DESKTOPMINGW64 ~/dotfiles (master)
$ PYTHONPATH=dotdrop python -m dotdrop.dotdrop --version
importing sys
main defined
dotdrop.py main
dotdrop.py main dep met
util for dep in deps
util import magic
util magic
Segmentation fault
```

**Comment by Lilja** [comment]
As a side note, I'm running git bash/git for windows. Don't know if `python-magic` supports this...

**Comment by deadc0de6** [comment]
Nice, those prints are helpful! It looks like `python-magic` is the culprit.

Can you try the following to see if magic segfaults too?
```bash
$ python3
>>> import magic
>>> magic.from_file("somefile.whatever")
```

If it does maybe try to revert `python-magic` to an older version, like for example `0.4.18`
```bash
$ pip install 'python-magic==0.4.18'
```

**Comment by deadc0de6** [comment]
found some issues on [python-magic](https://github.com/ahupp/python-magic/issues) that may be related:

* https://github.com/ahupp/python-magic/issues/248
* https://github.com/ahupp/python-magic/issues/225

**Comment by deadc0de6** [comment]
Maybe try installing `python-magic-bin` in addition to `python-magic`:
```bash
$ pip install python-magic-bin
```

**Comment by Lilja** [comment]
You are right, it looks like they needed that binary file. I pip installed it works to get the version!

```
Erik Lilja@DESKTOP MINGW64 ~/dotfiles (master)
$ PYTHONPATH=dotdrop python -m dotdrop.dotdrop --version
importing sys
main defined
dotdrop.py main
dotdrop.py main dep met
util for dep in deps
util import magic
util magic
util assert
util hasattr
util docopt
util jinja
util ruamel
dotdrop.py main opts
1.7.0
```

For potential future readers, install the above dependency and you should be able to run things!

**Comment by deadc0de6** [comment]
Happy it worked. I will add this to the documentation

**Comment by deadc0de6** [comment]
I also adapted the `dotdrop.sh` script so that it fallbacks to `python` if `python3` doesn't exist.
