### ISSUE TITLE
[feature] Config setting to always record file permissions

### ISSUE THREAD

**Issue by imchairmanm** [deadc0de6/dotdrop#324]
Hello,

According to [the docs](https://dotdrop.readthedocs.io/en/latest/config/#permissions), `dotdrop` only records permission values if you explicitly pass in the `-m`/`--preserve-mode` flags, or if the file's permissions differ from the current `umask` value.

It'd be nice if I could set a config option to tell `dotdrop` that I would always like to preserve the permissions of files I am importing.  Currently, I can just alias the `dotdrop` command to include the flag, but it'd be great if I didn't have to.  I switch between systems fairly regularly and I would rather not have to try to puzzle out what the `umask` value was set to on whatever machine I imported from in order to ensure I have permissions set correctly when applying the files to a new host.  It would be great to ensure that all of the information required is recorded right there next to the other info.

Thanks!

**Comment by deadc0de6** [comment]
@imchairmanm this is fixed in `v1.7.2`

**Comment by imchairmanm** [comment]
Wow, excellent! Thanks for the heads up :+1:
