### ISSUE TITLE
[feature] Provide option to clear 'cache' before installation

### ISSUE THREAD

**Issue by anihm136** [deadc0de6/dotdrop#330]
I'd like a flag for the `dotdrop install` command that clears the current installation from `workdir` before installing a new version of the dotfiles

To set the context, this is the issue I faced - I did a large update of my dotfiles on one machine, then pulled in the changes on another and installed them. It appeared that some files which I had deleted were being installed on the second system. I finally figured that the issue was that the old templated dotfiles were installed to `workdir` and it was being linked from there. Deleting the folder from `workdir` and running install again worked as expected

**Comment by deadc0de6** [comment]
I've integrated the clearing of the `workdir` in the [clear_workdir branch](https://github.com/deadc0de6/dotdrop/tree/clear_workdir). You have now two ways to clear the `workdir` directory:
* through the command line switch `-W --workdir-clear` when calling `install`
* through the config entry `clear_workdir`

Can you test it and let me know if that matches your expectations?

**Comment by anihm136** [comment]
Okay just tried it out, looks like it's working as I expected. Thanks!

**Comment by deadc0de6** [comment]
I've added a new config option `compare_workdir` in the [compare-workdir branch](https://github.com/deadc0de6/dotdrop/tree/compare-workdir). By setting it to `true`, it will notify on files found in the `workdir` not tracked by dotdrop.

I'd be thankful if you could give it a try and let me know if that's what you need.

**Comment by anihm136** [comment]
Looks good, got a chance to try it out over the last couple of days. The listing of missing files is very helpful. Thanks again!
