### ISSUE TITLE
[bug] `dotdrop compare` diff output should go to stdout, not stderr

### ISSUE THREAD

**Issue by jwodder** [deadc0de6/dotdrop#331]
Dotdrop version (and git commit if run from source): v1.7.3
Using dotdrop: from PyPI

(I'm not sure whether this counts as a bug or a feature request, but I'm filing it as a bug because dotdrop is breaking standard practice.)  Currently, `dotdrop compare` redirects the diff output to standard error, which should only be used for error messages, instead of to standard output, which is where normal program output belongs.  This makes it difficult to pipe the output into a pager like `less`.

**Comment by deadc0de6** [comment]
This has been fixed in the master branch and will be part of the next release

**Comment by jwodder** [comment]
Great, thanks!
