### ISSUE TITLE
[help]

### ISSUE THREAD

**Issue by gsiawGH** [deadc0de6/dotdrop#332]
i like this tool so far.

when you use "dotdrop compare", is it possible to make a configuration setting, to use a different diff tool  ( https://github.com/sharkdp/bat )? 

also, from "dotdrop files" i can get a list of all the files that have been imported, but i dont see a quick way to search for all the files that have modifications . it looks like i have to do a "dotdrop compare" on each file, to understand if there are differences. but it would be nice to see an equivalent of "git status" that shows all files that have been modified. 

 Thanks!

**Comment by gsiawGH** [comment]
Great. `dotdrop compare -L ` does work. However the config change is not taking any effect.

**Comment by deadc0de6** [comment]
well it seems `bat --diff` is to be used on a git repository (comparing current file with the committed file) but not between files. Indeed
```bash
$ echo 'something' > /tmp/a
$ echo 'else' > /tmp/b
$ bat -P --diff /tmp/a /tmp/b
```
The above produces no output.
