### ISSUE TITLE
[bug] Can't seem to ignore vim folders

### ISSUE THREAD

**Issue by mdentremont** [deadc0de6/dotdrop#337]
Dotdrop version (and git commit if run from source): v1.8.2
Using dotdrop: as a submodule, inside WSL 
```
pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
python3 --version
Python 3.8.10
```

**Describe the bug**

I'm trying to ignore "~/.vim/doc", but the ignore parameters don't seem to work.

Here is my ~/.vim folder:
![image](https://user-images.githubusercontent.com/1106324/144883743-dbe14197-ab8d-4ba4-805d-9b5fbd00f8be.png)

Here is my ~/Dotfiles/vim folder:
![image](https://user-images.githubusercontent.com/1106324/144883808-8f212834-744d-465d-a3f9-93dbb7d6992c.png)

Here are my relevant configs:
![image](https://user-images.githubusercontent.com/1106324/144883897-348e531a-21d1-4acd-b9f8-e04dc89f1c2e.png)
![image](https://user-images.githubusercontent.com/1106324/144883924-023d0eec-6cf4-4eca-b7be-3c8846ef2fde.png)

When I run update, `~/.vim/doc` gets added to my Dotfiles, and compare gives me:
![image](https://user-images.githubusercontent.com/1106324/144884063-3185d214-4cf5-4b26-befd-2cdac8e2b5bc.png)

Notes:
- `~/.vim/bundle` is always ignored, even if I don't explicitly have ignores for it (it isn't empty)
- This is inside of the WSL partition, using WSL's python. Ignore is working for other folders

**Comment by deadc0de6** [comment]
Using following pattern should work:
```yaml
    cmpignore:
      - '*/doc'
    upignore:
      - '*/doc'
    instignore:
      - '*/doc'
 ```

Can you try and if that still doesn't work provide me with the debug logs with `--verbose`?
