### ISSUE TITLE
[bug] AUR dotdrop error but dotdrop-git works

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#339]
Dotdrop version (and git commit if run from source): 1.8.2
Using dotdrop: from AUR

**Describe the bug**

After install it by `yay -S dotdrop`，then when run dotdrop install got error below:

```
Traceback (most recent call last):
  File "/usr/bin/dotdrop", line 33, in <module>
    sys.exit(load_entry_point('dotdrop==1.8.2', 'console_scripts', 'dotdrop')())
  File "/usr/bin/dotdrop", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for dotdrop
```

Then try install dotdrop-git which works well.

**Comment by deadc0de6** [comment]
Can you try to install following package and let me know if that works:
```bash
sudo pacman -S python-importlib-metadata
```

**Comment by roachsinai** [comment]
> ```shell
> python-importlib-metadata
> ```

I've already installed `python-importlib-metadata 4.8.1-3`. But reinstall dotdrop still get above error.

**Comment by deadc0de6** [comment]
ok, what version of python are you using?
```bash
python3 --version
```

**Comment by roachsinai** [comment]
> ok, what version of python are you using?
> 
> ```shell
> python3 --version
> ```

3.10.1.

**Comment by deadc0de6** [comment]
I'm sorry but I'm unable to reproduce, can you maybe try to install the package `importlib-metadata` with pip

**Comment by roachsinai** [comment]
@deadc0de6 My fault. I think the reason is I reinstall dotdrop but it just install the package built when python version is 3.9.

Rebuild the package and works well now.

Sorry for bother!

**Comment by deadc0de6** [comment]
@roachsinai no worries, happy it works ;-)
