### ISSUE TITLE
[bug] Config parsing crashes with profile variables and multiple config import

### ISSUE THREAD

**Issue by davla** [deadc0de6/dotdrop#340]
Dotdrop version (and git commit if run from source): v1.8.2
Using dotdrop: from pypi

---

Hi, I'm back!

Dotdrop crashes while parsing config files, regardless of the actual command. It specifically hits the `unable to merge` execution branch in `CfgYml._merge_dict`.

This only happens in a very specific scenario:
- A config file is imported more than once in the `import_configs` tree. For example
  ```
  top-level.yml --[import]--> mid-level.yml --[import]--> bottom-level.yml
  top-level.yml --[import]--> bottom-level.yml
  ```
  `bottom-level.yml` here is imported twice, once directly by `top-level.yml` and once indirectly via `mid-level.yml`
- A profile in the config file that is imported twice (e.g. `bottom-level.yml`) has profile variables

---

I've already investigated a bit and found out that if we prevent the config files from _actually_ being imported twice, then the problem doesn't occur any longer. I have a commit ready for a pull request, which silently ignores any import for the same config file after the first. I also can't foresee any other problem: in fact, variables in sub-config files override the ones in the super-config file, so in the end the values come from the leaf of the import tree, no matter which super-config file is importing it.

Still,  I'm not sure it's the right approach. My doubt is that the scenario is quite _questionable_. Should multiple indirect imports of the same config file be allowed in the first place? Can this practice backfire in ways I couldn't think of? It wouldn't take me much effort to change the commit to report an error when the same sub-config is imported twice, rather than silently ignoring the import.

**Comment by deadc0de6** [comment]
Hello @davla, sorry for the very late reply. I started debugging this but got carried away by life.
I agree that the same config file shouldn't be imported twice. We could add a new rule in [CONTRIBUTING.md](https://github.com/deadc0de6/dotdrop/blob/master/CONTRIBUTING.md#rules).

To be honest I'd rather have dotdrop fail (and report an error) than silently discarding it.
How stable is your PR, do you need help?

**Comment by davla** [comment]
The PR is fairly stable, and it's been made as you can see

**Comment by davla** [comment]
#341 has been merged, we can close this.
