### ISSUE TITLE
[help] Please update the docs as now we can install dotdrop with Homebrew 🥳

### ISSUE THREAD

**Issue by curoky** [deadc0de6/dotdrop#345]
**What I am trying to achieve**

Install dotdrop with Homebrew, it looks like

```
brew install dotdrop
```

**What I have tried so far**

I create a PR(https://github.com/Homebrew/homebrew-core/pull/101255) on https://github.com/Homebrew/homebrew-core and it has been merged into the master.

So the only thing left is to update docs and README. 😼

**Comment by deadc0de6** [comment]
Wow that's very nice!! Thanks a lot for this :+1:

**Comment by deadc0de6** [comment]
https://dotdrop.readthedocs.io/en/latest/installation/#homebrew-package

**Comment by deadc0de6** [comment]
BTW I'm wondering if we should/can put the dependencies listed here: https://dotdrop.readthedocs.io/en/latest/installation/#dependencies

* [coreutils](https://formulae.brew.sh/formula/coreutils)
* [libmagic](https://formulae.brew.sh/formula/libmagic)

**Comment by curoky** [comment]
Of course, we can!

It seems that `coreutils` is only required when use the entry point script `dotdrop.sh`, so I just added `libmagic`.

Homebrew bundles dotdrop via pip venv, so it doesn't need `dotdrop.sh` ?

**Comment by deadc0de6** [comment]
Awesome, thanks again!
Absolutely, `libmagic` is enough, no need for `coreutils` or `dotdrop.sh` (which is only needed when using dotdrop as a submodule).

**Comment by curoky** [comment]
Done, https://github.com/Homebrew/homebrew-core/pull/102043 already merged.

Very useful software, glad to have the opportunity to make some trivial contributions. 😊
