### ISSUE TITLE
[feature] search config.toml for config file

### ISSUE THREAD

**Issue by Weathercold** [deadc0de6/dotdrop#356]
Currently, to use a toml config file, I need to either specify it on the command line or create a `config.yaml` that imports `config.toml`.
Please add `config.toml` to the search path so that it can be used as the default config file.

**Comment by deadc0de6** [comment]
Sure I'll add this to the next release. You could also potentially use the environment variable `DOTDROP_CONFIG` btw.

**Comment by Weathercold** [comment]
Thank you. I tested and it works.
