### ISSUE TITLE
[bug] TypeError: Dotfile.__init__() got an unexpected keyword argument 'impignore'

### ISSUE THREAD

**Issue by rino0601** [deadc0de6/dotdrop#358]
Dotdrop version (and git commit if run from source): v1.10.3
Using dotdrop: homebrew

**Describe the bug**
![Cursor_및_Config_file_-_dotdrop](https://user-images.githubusercontent.com/1422445/185289610-c2ec9777-b19a-41aa-892f-3af24a852f79.png)

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/1422445/185289976-0793301e-e6ea-43ce-99b8-110e099b0470.png">

**Steps to Reproduce**

1. Create a dotfile with content `impignore`
2. `dotdrop compare`

**Expected behavior**

I checked the contents of dotdrop/dotfile.py, and it seems that only that part of the document needs to be deleted.

**Additional information**

The relevant part of the config file
```yaml
dotfiles:
  d_config:
    src: config
    dst: ~/.config
    chmod: '700'
    instignore: [ 'jgit' ]
    impignore: [ 'jgit' ]  # err!
    cmpignore: [ 'jgit' ]
    upignore: [ 'jgit' ]
```

Dotdrop's execution with the debug logs (`--verbose`)

```bash
➜  dotfiles git:(main) ✗ dotdrop compare                   
Traceback (most recent call last):
  File "/opt/homebrew/bin/dotdrop", line 33, in <module>
    sys.exit(load_entry_point('dotdrop==1.10.3', 'console_scripts', 'dotdrop')())
  File "/opt/homebrew/Cellar/dotdrop/1.10.3/libexec/lib/python3.10/site-packages/dotdrop/__init__.py", line 13, in main
    if dotdrop.dotdrop.main():
  File "/opt/homebrew/Cellar/dotdrop/1.10.3/libexec/lib/python3.10/site-packages/dotdrop/dotdrop.py", line 872, in main
    opts = Options()
  File "/opt/homebrew/Cellar/dotdrop/1.10.3/libexec/lib/python3.10/site-packages/dotdrop/options.py", line 171, in __init__
    self._read_config()
  File "/opt/homebrew/Cellar/dotdrop/1.10.3/libexec/lib/python3.10/site-packages/dotdrop/options.py", line 256, in _read_config
    self.conf = Cfg(self.confpath, self.profile, debug=self.debug,
  File "/opt/homebrew/Cellar/dotdrop/1.10.3/libexec/lib/python3.10/site-packages/dotdrop/cfg_aggregator.py", line 44, in __init__
    self._load()
  File "/opt/homebrew/Cellar/dotdrop/1.10.3/libexec/lib/python3.10/site-packages/dotdrop/cfg_aggregator.py", line 260, in _load
    self.dotfiles = Dotfile.parse_dict(self.cfgyaml.dotfiles)
  File "/opt/homebrew/Cellar/dotdrop/1.10.3/libexec/lib/python3.10/site-packages/dotdrop/dictparser.py", line 39, in parse_dict
    return [cls.parse(k, v) for k, v in items.items()]
  File "/opt/homebrew/Cellar/dotdrop/1.10.3/libexec/lib/python3.10/site-packages/dotdrop/dictparser.py", line 39, in <listcomp>
    return [cls.parse(k, v) for k, v in items.items()]
  File "/opt/homebrew/Cellar/dotdrop/1.10.3/libexec/lib/python3.10/site-packages/dotdrop/dictparser.py", line 32, in parse
    return cls(key=key, **newv)
TypeError: Dotfile.__init__() got an unexpected keyword argument 'impignore'
```
(The verbose option is omitted because it is too verbose. But it will be enough.)

**Comment by deadc0de6** [comment]
`impignore` is a config block entry and not a dotfiles entry:

* you find `impignore` in [the config block](https://dotdrop.readthedocs.io/en/latest/config-config/#config-block)
* but not in [the dotfiles block](https://dotdrop.readthedocs.io/en/latest/config-dotfiles/)

The point is that if the dotfile entry is already there, then it makes little sense to have an ignore pattern on import. Maybe you were looking for `upignore`?

**Comment by deadc0de6** [comment]
@rino0601 I have cleaned the error so that it's less verbose. It will be available in the next release.

**Comment by rino0601** [comment]
@deadc0de6 
Sorry for the late reply.
And thanks for the great tool.

I'm new to this tool, and I found this while trying to learn something. (After reading only "getting started" and skipping the rest)

If I had followed all the "usage" documentation, I would have known that import and update exist separately, so I would not have tried to import the imported one again, so I would not have noticed this awkwardness.

I thought the documentation was awkward, so I tried to write a PR. The content to be written was small, but I had to understand the repo structure to write mkdocs , so my reply was delayed because I was wasting time here.

In doing so, I came to understand the code and functions of the project, and as my understanding improved, the documentation did not look awkward at all. It makes sense.

In the end, it was because I did not read the documents in order, and it was difficult to explain to people who did not see the explanation, so I decided that it was not something to fix by fixing the document.

My misunderstanding has been cleared up, so I guess I'll just have to close it. Sorry to bother you!

And once again thank you for this project.

**Comment by deadc0de6** [comment]
@rino0601 no problem, happy to help!

Could you provide me with more information on why you didn't find your way in the doc at the beginning so that I can improve it?
* what did you find awkward?
* what was missing?
* how do you think the doc can be improved for newcomers?
* any other suggestions on how to improve the doc?

Thanks for your help!

**Comment by rino0601** [comment]
![Config_file_-_dotdrop](https://user-images.githubusercontent.com/1422445/186045975-662368c8-c329-4f1d-858b-7b7e0392295e.png)
