### ISSUE TITLE
[bug] `{VERSION}` placeholder is not substituted

### ISSUE THREAD

**Issue by Drarig29** [deadc0de6/dotdrop#361]
Dotdrop version (and git commit if run from source): 1.10.3
Using dotdrop: as a submodule

**Describe the bug**

Nothing too important, but when I run a command, the output shows this:

```
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v{VERSION}
                               |_|
```

**Steps to Reproduce**

1. Run any command

**Expected behavior**

The `{VERSION}` placeholder should be substituted with `1.10.3` or `v1.10.3`.

Dotdrop's execution with the debug logs (`--verbose`)
```bash
[DEBUG][dotdrop.options.__init__] #################################################
[DEBUG][dotdrop.options.__init__] #################### DOTDROP ####################
[DEBUG][dotdrop.options.__init__] #################################################
[DEBUG][dotdrop.options.__init__] version: 1.10.3
[DEBUG][dotdrop.options.__init__] command: /home/corentin/.dotfiles/dotdrop/dotdrop/dotdrop.py install --verbose
[DEBUG][dotdrop.options.__init__] config file: config.yaml
[DEBUG][dotdrop.cfg_yaml._dbg] [.dotfiles/config.yaml] START of config parsing
```

**Any additional information that would help reproduce the bug.**

I installed dotdrop as a submodule 2 years ago, so maybe something didn't get updated? It was updated via a automatic git pull today, and I don't remember if the issue was already there before today.

**Comment by deadc0de6** [comment]
thanks a lot, missed this one when refactoring in f-string.

**Comment by Drarig29** [comment]
no problem, your project is really useful 😉
