### ISSUE TITLE
pre actions are always executed

### ISSUE THREAD

**Issue by deadc0de6** [deadc0de6/dotdrop#39]
*pre* actions seem to be always executed no matter if the dotfile is installed or not

**Comment by deadc0de6** [comment]
Well when the *pre* actions are executed, it is not yet known if the dotfile will be installed (is different from local one, exists, ...). Two solutions to this:

* consider *pre* actions to be always executed.
* evaluate if the dotfile is to be installed (diffing, check existence, ...) ... or, in other words, simulate the installation (by completing the way `dry` is handled in `installer.py`.

This could be executed only for dotfile having some *pre* actions.

**Comment by ziirish** [comment]
By design we could suppose pre-actions will always be executed since with the current implementation there is no way to know if the file will be installed.

The workaround is to put some logic within the pre-action script like in the *vim-plug* example I documented.

**Comment by deadc0de6** [comment]
documented in the [readme](https://github.com/deadc0de6/dotdrop#use-actions)
