### ISSUE TITLE
Misleading/outdated documentation

### ISSUE THREAD

**Issue by Krapaince** [deadc0de6/dotdrop#391]
Hello there,

I'd like to point out a misleading point or outdated in the documentation. In the [profile actions section](https://dotdrop.readthedocs.io/en/latest/config/config-profiles/#profile-actions-entry), the profile entry is described as if you can add action.

However based on #375, the profile entry seems to be only a list of actions that will be executed upon profile installation.

Am I just miss understanding the documentation?

**Comment by deadc0de6** [comment]
Actions are defined in their own block, namely the [action entry](https://dotdrop.readthedocs.io/en/latest/config/config-actions).

These can then be added to a profile as a list as described [here](https://dotdrop.readthedocs.io/en/latest/config/config-profiles/#profiles-entry).

[In this test](https://github.com/deadc0de6/dotdrop/blob/master/tests-ng/profile-actions.sh#L44) you can see an example on how it is done.

Let me know if it's still unclear.

**Comment by Krapaince** [comment]
Alright seems like I read the documentation to fast.
I wanted to add an action `x` with different behavior based on profiles. So that I just have to add this action `x` on one dotfile entry included in each profile.
But it doesn't work that way. I just [created one action per profile](https://github.com/Krapaince/dotfiles_linux/commit/d1a881a7c3e5e95e334c98bf195afac074991470).

Thanks for the support.

**Comment by deadc0de6** [comment]
Sure  no problem.
