### ISSUE TITLE
[bug] `application/javascript` files treated as binary file

### ISSUE THREAD

**Issue by acourtneybrown** [deadc0de6/dotdrop#396]
Dotdrop version (and git commit if run from source): v1.13.0
Using dotdrop: from Homebrew

**Describe the bug**

The [`_handle_file`](https://github.com/deadc0de6/dotdrop/blob/master/dotdrop/templategen.py#L203) method in `templategen.py` treats files with mime-type `application/javascript` as a binary file, thus only copying it directly vs. running the file through the templating engine.  I'm uncertain if this recent bug is due to a change in `dotdrop` or the underlying `magic` library, as my setup had previously worked with version of `dotdrop` prior to `1.13.0_1` (from Homebrew), but now I see the same incorrect behavior with `1.13.0` & `1.12.13`

**Steps to Reproduce**

1. Create a dotfile with media-type `application/javascript` which also has template directives & has the `template` property either `true` or inherited `true`.
2. Run `dotdrop install` on the file
3. Notice that the resulting file still contains the template directives

**Expected behavior**

The file should be run through the templating engine & the template directives should not appear in the resulting output file.

**Additional information**

From [`acourtneybrown/dotfiles`](https://github.com/acourtneybrown/dotfiles/blob/main/config.yaml#L116-L118):
```yaml
  f_finicky.js:
    src: finicky.js
    dst: ~/.finicky.js
```
which uses `finicky.js` (from the same repo) containing [`template directives`](https://github.com/acourtneybrown/dotfiles/blob/main/dotfiles/finicky.js#L67-L88) like:

```javascript
    {%@@ if personal @@%}
    {
      match: [
        finicky.matchHostnames([
          "govzw.com",

          /nytimes.com/,
          /wsj.com/,
        ]),
        /^https:\/\/github.com\/{{@@ github_account @@}}\/.*$/,
      ],
      browser: "Safari"
    },
    {
      match: ({ opener }) => {
        // finicky.log(opener.bundleId);
        return opener.bundleId
          && (opener.bundleId === "com.agilebits.onepassword7" || opener.bundleId === "com.1password.1password")
      },
      browser: "Safari"
    },
    {%@@ endif @@%}
```

Dotdrop's execution with the debug logs (`--verbose`)
```bash
$ dotdrop install --verbose f_finicky.js
...
```

contains output showing the misidentification of the `application/javascript` file as **not** text:

```
[DEBUG][dotdrop.templategen._handle_file] using "magic" for filetype identification
[DEBUG][dotdrop.templategen._handle_file] filetype "/Users/adambrown/.dotfiles/dotfiles/finicky.js": application/javascript
[DEBUG][dotdrop.templategen._handle_file] is text "/Users/adambrown/.dotfiles/dotfiles/finicky.js": False
```

**Comment by deadc0de6** [comment]
Thanks for reporting this. 
Dotdrop will handle files as text as long as their mime type contains `text`, `json` or `empty`.

I tried running the `finicky.js` file through `file` and `python-magic` with different outputs depending on OS/versions. Most of time `text/plain` is returned but I also got `application/javascript`. 

Even though `application/javascript` is obsolete (and thus shouldn't happen), I will add an exception for the following mime types so that those files will get handle as text:
* `ecmascript`
* `javascript`

**Comment by deadc0de6** [comment]
The above commit should fix it for you. Could you test dotdrop from the master branch and let me know if that does it for you?

**Comment by acourtneybrown** [comment]
Yeah, the change above ensures that `dotdrop` processes the Javascript file through the template engine.  Thanks for the quick help.

**Comment by deadc0de6** [comment]
@acourtneybrown awesome!

Thanks for your help. I'll release a new version on pypi ASAP and will ping you when done.

**Comment by deadc0de6** [comment]
@acourtneybrown new version 1.13.2 [is available on pypi](https://pypi.org/project/dotdrop/).
