### ISSUE TITLE
provide the ability to use long keys

### ISSUE THREAD

**Issue by deadc0de6** [deadc0de6/dotdrop#40]
provide users with the ability to use long keys (mirroring the abs path to the dotfile, instead of the shorten version).

* entry in the config file
* ability to rename existing short keys 

see #38

**Comment by deadc0de6** [comment]
the key `longkey` in the config allows now to control the behavior of the key creation (see [import](https://github.com/deadc0de6/dotdrop#import-dotfiles)). Default is to use short keys and thus longkey is false.

The script [scripts/short-to-long-key.py](https://github.com/deadc0de6/dotdrop/blob/master/scripts/short-to-long-key.py) allows to update the config file to change from short keys to long keys.

**Comment by deadc0de6** [comment]
@ziirish FYI, thanks for the suggestion

**Comment by ziirish** [comment]
Thanks for the quick answer and implementation!
