### ISSUE TITLE
Allow not dropping `.` prefix when importing

### ISSUE THREAD

**Issue by stephenh** [deadc0de6/dotdrop#41]
I have an existing homedir with files like `.vimrc` and I'd like to run `dotdrop import .vimrc` to populate the `config.yml` file. (I'm technically running `git ls-files | xargs dotdrop import` to mass import my existing repo.)

Since I have an existing homedir, I want the import to be somewhat no-op, e.g. I don't need it to actually copy the `.vimrc` file over, I just need the `config.yml` entry made.

This works really well, except right now `import` wants to rename the file `vimrc`, so my existing homedir working copy ends up with both `.vimrc` (which I've had checked in for awhile) and also the new `vimrc`.

I made a hacky change to `dotdrop.py` which changes `src = src.lstrip('.' + os.sep)` to just `src = src.lstrip(os.sep)` and I get the "preserve dots on import" behavior that I want.

It seems like this would be a nice/easy feature to support, especially for people coming from existing-with-dot-prefix setups.

**Comment by stephenh** [comment]
(FWIW, I also found changing the `config.dotpath` to just `.` made `import` match my existing homedir's setup; you've got `dotpath` already documented, which is great, but might be nice to have a "migrating your existing homedir" section that mentions the `config.dotpath` config + my proposed "preserve dots" import, assuming you're okay with that.)

**Comment by stephenh** [comment]
Ack...as a usability FYI, I was fairly proud of my `git ls-files` approach, however I made the mistake of:

* My existing /home/stephen directory was a git working copy (which I wanted to move away from)
* I made a /home/stephen/.homedir (like a dotfiles) clone of my existing repo, as I wanted to use that as a bootstrap
* I ran `git ls-files | xargs ./dotdrop.sh import` from *within* the `.homedir`

What happened is that `ls-files` outputs paths without a prefix, e.g. just `file.txt` or `dir/file.txt`...normally `dotdrop` fails, e.g. if I run it from `/home/stephen`, because it probably sets the CWD to `.homedir`.

However, because my `.homedir` was pre-populated, it looked up `file.txt` just fine, and I ended up with a config.yaml that looked like:

```
  f_file:
    dst: file.txt
    src: file.txt
```

However, this is wrong, as now when doing `compare`, both are relative paths and are resolved to exactly the same file, within the `.homedir`.

I need to have `dst: ~/file.txt`, which is typically caught when manually invoking `import` from the "not-.homedir" home directory, as it enforces `~/file.txt` format.

Anyway, not sure if you want to do anything here to prevent future-mes from similarily shooting themselves in the foot.

**Comment by deadc0de6** [comment]
I could add an option (in the config or as a CLI switch) that allows to preserve the dots in the *dotpath* directory, that's not a problem.

Regarding the batch import of an existing dotfiles directory. In your case if you import files from you *homedir*, the `dst` of each dotfile (what tells where the dotfile is to be installed) will be wrong as it will point to the *homedir* itself and not to the expected destination of the file, thus creating some kind of loop (the issue you identified). One suggestion which is far from perfect would be to batch edit your dotfile (assuming they all are stored with a relative path to `~`) like this `sed 's#dst: \(.*\)$#dst: ~/\1#g' config.yaml`. However some kind of manual check might be needed.

Just to correctly understand the problem here. You have an existing *homedir* with all your dotfiles (flat? with hierarchy?) and want to *transform* somehow that to dotdrop? Are the dotfiles in *homedir* symlinks?

**Comment by stephenh** [comment]
>  batch edit your dotfile

Yep, this was my ugly-but-worked recovery method. :-)

>  You have an existing homedir with all your dotfiles

Yeah, for awhile I'd taken the super-naive approach of just making my home directory itself a git working copy. E.g. I would `git clone ssh://.../~/homedir.git/` into a temp directory, and then move that `.git` into `/home/stephen/.git` (or something like that), and "promote" my home directory to a full-fledged working copy.

This was nice because then I could just `git add ...`, `git diff ...`, etc., without any symlinks, etc.

The biggest downside was that I had `~/.gitignore` with a `*` entry, as obviously there are a ton of files in my home directory which are not checked in. Eventually this `*` entry messed with enough tools (e.g. watchman and ripgrep) that I figured, bah, time to try something better, and here I am. :-)

Thanks for the quick fix on the preserving dots feature!

**Comment by stephenh** [comment]
Per other comment, tested this out (on just one file) and AFAICT it works great. Thanks!
