### ISSUE TITLE
The repo has chezmoi and yadm as topics but doesn't seem to use those projects

### ISSUE THREAD

**Issue by dslatkin** [deadc0de6/dotdrop#417]
Does dotdrop use [chezmoi](https://www.chezmoi.io/)? I noticed this repo has the "chezmoi" topic when browsing chezmoi-related repos but I can't [find anything](https://github.com/search?q=repo:deadc0de6/dotdrop%20chezmoi&type=code) referencing chezmoi. I'm guessing it's unintended but it does introduces noise when browsing chezmoi-based dotfiles so it would be nice if it could be removed if it doesn't actually use chezmoi.

(edit) I see YADM as a topic as well. I'm not sure you intended it to be perceived this way but it feels kind of spammy and in bad faith using topics in this manner. If people want to switch dotfile managers, they won't browse repos listed under the name of their current dotfile manager to do so.

**Describe the bug**

The repo has `chezmoi` and `yadm` as topics.

**Comment by deadc0de6** [comment]
thanks for pointing that out, I removed the tag.
