### ISSUE TITLE
Running `dotdrop compare` after import is confused by Windows line endings

### ISSUE THREAD

**Issue by stephenh** [deadc0de6/dotdrop#42]
I have some historical files in my homedir that are from my Windows days (don't judge me :-)) and they still have line-feed + carriage-return line endings.

For reason, after `dotdrop import` and then a `dotdrop compare` with zero changes, all of my files that had LF+CR line endings are shown as dirty, with the diff including the entire "all lines with LF deleted" + "all lines with LF+CR added".

**Comment by stephenh** [comment]
It also seems to get confused by unicode characters, e.g.:

```
diffing "f_wiki.vim" VS ".vim/syntax/wiki.vim"
5c5
< "                      Mathias Panzenb�ck <grosser.meister.morti@gmx.at>
---
> "                      Mathias Panzenb�ck <grosser.meister.morti@gmx.at>
```

If I run just `diff`, there is no output:

```
diff .vim/syntax/wiki.vim .homedir/.vim/syntax/wiki.vim
```

**Comment by stephenh** [comment]
Well, I dos2unix'd all my files; I'm still getting the unicode oddness, doing a little debugging, I can tell the "except UnicodeDecodeError" path is being triggered for the four files that I'm still having trouble with. Maybe they are just invalid, e.g. missing that first marker byte.

**Comment by deadc0de6** [comment]
For the CRLF issue, this is due to the fact that the file is correctly imported (with the CRLF) but when it gets transformed by jinja2 (dotdrop does that even if the file is not using any jinja2 delimiters), the CRLF are somehow stripped what results in the difference. I guess dos2unix'ing them is a good way to solve this issue.

Regarding the unicode issue, I can't reproduce the issue. Could you run dotdrop with `--verbose` and provide me with an `hexdump` of a file (or part of it) so I can reproduce it?

**Comment by ziirish** [comment]
I already encountered the encoding issue, I guess I can reproduce it easily and try to get it fixed.

**Comment by deadc0de6** [comment]
I'm unable to reproduce the issue using some non-unicode chars:
```bash
$ python -c 'print "\xad\xde\x04\x08AAAA%n"' > /tmp/xxx
$ ./dotdrop.sh import /tmp/xxx    
	-> "/tmp/xxx" imported
1 file(s) imported.
$ ./dotdrop.sh compare
```

Comparison doesn't show any change.

Could you also provide along with the original file dump, the temporary file generated when calling `compare` (dotdrop shows the directory where the temporary dotfiles are generated `temporary files available under ...`). Thanks.

**Comment by deadc0de6** [comment]
interesting, thanks @ziirish 

The difference between my example and yours is that mine is detected as binary (as `file -b` doesn't return *text*) while yours does return *text*.

The dotfile is correctly imported in the *dotpath* however when handled by jinja2 (through the temporary directory), the weird chars get replaced with chars like `����` what is actually the source of the comparison fail.

**Comment by deadc0de6** [comment]
this is due to how dotdrop handles non-unicode: `data.decode('utf-8', 'replace')` ... I'll check that

**Comment by deadc0de6** [comment]
actually jinja2 doesn't support non-unicode chars.

http://jinja.pocoo.org/docs/2.10/api/
```
It is not possible to use Jinja2 to process non-Unicode data. The reason for this is that Jinja2
uses Unicode already on the language level. For example Jinja2 treats the non-breaking
space as valid whitespace inside expressions which requires knowledge of the encoding
or operating on an Unicode string.
```

My workaround to this was to replace non-unicode chars to still be able to process the file through jinja2 but the resulting file obviously will be different from the original one.

Two solutions to this:
* we expect all dotfiles to be unicode (and thus adding unicode dotfiles in dotdrop results in a `compare` returning a difference while there's none)
* we bypass jinja2 for these files but won't be able to template them
* add some options in the config file that allows to bypass the comparison of specific files when calling `compare`

My personal opinion is that I'd rather change some weird chars in my dotfiles and still be able to use jinja2 than completely removing jinja2 for some files.

Any opinion ?

**Comment by deadc0de6** [comment]
I have reported this in this page in the wiki for reference: https://github.com/deadc0de6/dotdrop/wiki/special-chars

**Comment by ziirish** [comment]
I was actually working on a *converter" with a new *recode* option in order to force recode any imported files into utf-8 if you set the *recode* option to *true* (which is *false* by default).

This way, you still end-up with differences between what has been imported and your actual source, but you won't have that issue anymore once you install your dotfiles again.

**Comment by deadc0de6** [comment]
sounds good, keep me posted :+1:

**Comment by stephenh** [comment]
Here's one of the files that is causing problems for me, from `base64 misc/patches/trac-wiki-backend-patch.txt > patch.base64.txt`:

[patch.base64.txt](https://github.com/deadc0de6/dotdrop/files/2077660/patch.base64.txt)

I'm a little confused by the "jinja is not able to process non-unicode chars"; wouldn't the offending char in Jonas's last name be a unicode char? ...oh, vim says this is encoded with latin1.

Oh sure, if I `:set fileencoding=utf-8` and save the file, and now it all works as expected.

Maybe for newbies like myself, add the hint of "check what `:set fileencoding?`" says in vim to the special-chars page?

**Comment by deadc0de6** [comment]
@stephenh do the solutions reported [here](https://github.com/deadc0de6/dotdrop/wiki/special-chars) work for you?

**Comment by stephenh** [comment]
Yep, looks good!

Maybe just a few more hints, e.g. add a paragraph under "Detect coding" that is:

For example, if you have a non-unicode file like:

```
$ file -b .vimrc
ISO-8859 text, with escape sequences
```

You will likely get false/corrupted output from `dotdrop compare`.

Instead you want output that looks like:

```
$ file -b .vimrc
UTF-8 Unicode text, with escape sequences
```

To change an existing file's encoding, you can use `recode UTF-8 <filename>` (see [recode](https://linux.die.net/man/1/recode) or in vim `:set fileencoding=utf-8`.

**Comment by deadc0de6** [comment]
done, thanks for your help!
