### ISSUE TITLE
add option for preserving dots

### ISSUE THREAD

**Issue by deadc0de6** [deadc0de6/dotdrop#43]
add an option for preserving dots when importing files containing dots in the *dotpath*.

see #41

**Comment by deadc0de6** [comment]
implemented in 15391d9cad32f725f048883665c2613a9c30a66b.

The [config file option keepdot](https://github.com/deadc0de6/dotdrop#config) when set to true will preserve the leading dot on hidden file.

@stephenh FYI, let me know if you test it

**Comment by stephenh** [comment]
Yep, just tested it, and works great. Thanks!
