### ISSUE TITLE
[bug] Can't install on Termux (Android) due to bug in dependency

### ISSUE THREAD

**Issue by ErrrorMaxx** [deadc0de6/dotdrop#434]
**Describe the bug**

Dotdrop uses `ruamel.yaml.clib` somewhere in its dependencies which suffers from bug: https://sourceforge.net/p/ruamel-yaml-clib/tickets/22/

Because of this bug `dotdrop` cannot be installed on Termux, FreeBSD and some others

**Steps to Reproduce**

1. Setup Termux on your Android phone
2. Run `pip install dotdrop`

**Expected behavior**

Dotdrop can be installed

**Comment by deadc0de6** [comment]
Thanks for reporting this and sorry you're having issues with dotdrop. Pretty cool to know you're trying dotdrop on android! The reported bug on ruamel is opened for a year. Does that mean that any packages depending on ruamel would not work on termux?
An alternative would be to switch back to PyYAML but unfortunately it doesn't support comments among other things.

I see three ways to solve this but none are optimal:

* find an alternative to ruamel with a similar set of features
* selectively provide dotdrop with PyYAML on specific platform with all the issues that may arise from switching back
* if toml is an alternative you could use dotdrop without yaml support. Not sure exactly how to provide selective dependencies based on the platform but that could be doable

**Comment by deadc0de6** [comment]
It seems the alternatives to ruamel are [yamlcore](https://pypi.org/project/yamlcore/) on top of PyYAML or [strictyaml](https://hitchdev.com/strictyaml/).

I think I can also provide a new version of dotdrop with only toml support on termux if having your configs as toml is an option for you.

**Comment by deadc0de6** [comment]
@ErrrorMaxx it seems brew takes a different approach to the ruamel bug with
```
    # Work around ruamel.yaml.clib not building on Xcode 15.3, remove after a new release
    # has resolved: https://sourceforge.net/p/ruamel-yaml-clib/tickets/32/
    ENV.append_to_cflags "-Wno-incompatible-function-pointer-types" if DevelopmentTools.clang_build_version >= 1500
```

from [dotdrop formula](https://github.com/Homebrew/homebrew-core/blob/366c2149a08cea0555e91af586476b8e399b4dce/Formula/d/dotdrop.rb#L93) if that's of any help.
