### ISSUE TITLE
[bug] dotdrop ignores some files

### ISSUE THREAD

**Issue by JaydenFish** [deadc0de6/dotdrop#439]
When dotdrop execute `update`, Sometime there is a a warn:
```
[WARN] /home/jdyu/.emacs.d/quelpa/melpa/html-stable/build-status.json update failed, do manually: [Errno 2] No such file or directory: '/home/jdyu/.emacs.d/quelpa/melpa/html-stable/build-status.json'
```
`dotdrop/updater.py` line 308 and 334, `return False` should be `continue`. Or when this warn occurs, it ignores some files.

**Comment by deadc0de6** [comment]
Thanks for reporting this.
Can you give me more context on this issue as to why this is happening? Are you removing/changing file in the dotpath manually before running `update`?

**Comment by JaydenFish** [comment]
![图片](https://github.com/user-attachments/assets/7e738be2-f5f2-48bb-836a-06f0f558c42d)

**Comment by deadc0de6** [comment]
Can you give it a try with the modifications in branch [fix-for-439](https://github.com/deadc0de6/dotdrop/tree/fix-for-439)? [Here](https://dotdrop.readthedocs.io/en/latest/howto/test-latest-dotdrop/) is the doc on how to do that.
Thanks!

**Comment by JaydenFish** [comment]
it's fixed!

> Can you give it a try with the modifications in branch [fix-for-439](https://github.com/deadc0de6/dotdrop/tree/fix-for-439)? [Here](https://dotdrop.readthedocs.io/en/latest/howto/test-latest-dotdrop/) is the doc on how to do that. Thanks!

**Comment by deadc0de6** [comment]
Awesome, I will clean that and release a new version. Thanks for your help!
