### ISSUE TITLE
When de-linking a file, first remove the symlink

### ISSUE THREAD

**Issue by stephenh** [deadc0de6/dotdrop#45]
I started out with a file, e.g. `.Xresources` as a symlink, and later wanted to template-ize it, so I can have per-machine DPIs.

I removed the "link: true" from the config.yml, added my template syntax to `.homedir/.Xresources`, and run `dotdrop install`.

I was correctly prompted to overwrite the previous symlink:

```
Overwrite "/home/stephen/.Xresources" [y/N] ? y
        -> copied "/home/stephen/.homedir/./.Xresources" to "/home/stephen/.Xresources"
```

However, it looks like `dotdrop` did not first remove the symlink, as the post-template files where written to `~/.Xresources`, which still being symlinked, means it also overwrote the `~/.homedir/.Xresources` file as well.

I re-made my template changes to `~/.homedir/.Xresources`, and then manually deleted the `~/.Xresources` file, and then everything works as expected.

**Comment by deadc0de6** [comment]
I'm not sure it can be assumed that all destinations of dotfiles (which are a symlinks) is to be deleted. Most of the time the symlink is intended and thus shouldn't be blindly removed.

This is special case, you moved from a *link: true* to *link: false*. I will document that in the readme such that it is more clear.

Thanks for reporting this.

**Comment by stephenh** [comment]
> I'm not sure it can be assumed that all destinations of dotfiles (which are symlinks) is to be deleted

Hm...true, what about only if the symlink points to the src file we're copying from? That would seem like a good indication that we should delete first.

**Comment by deadc0de6** [comment]
Absolutely, that make sense. I might even throw an error as there's something weird going on when that happens.

**Comment by deadc0de6** [comment]
Is fixed in latest version.
Thanks again!

**Comment by stephenh** [comment]
Great, I verified it works as expect. Thanks!
