### ISSUE TITLE
[bug] Temporary file not cleaned up after running tests

### ISSUE THREAD

**Issue by shyun3** [deadc0de6/dotdrop#451]
Dotdrop commit: [b53f939](https://github.com/deadc0de6/dotdrop/commit/b53f9396eceafc12b77709d3afb60c244db10bae)

**Describe the bug**

Running the tests creates a file named `.dotdrop.test` in the home directory.

**Steps to Reproduce**

1. Make sure `.dotdrop.test` doesn't already exist in the home directory
2. Run `tests.sh`
3. Check that `.dotdrop.test` now exists in the home directory

**Expected behavior**

Running the tests should not affect the home directory or if it does, it should clean up after itself.

**Additional information**

`.dotdrop.test` contains a single word: `modified`

#447 describes a similar kind of problem.

**Comment by deadc0de6** [comment]
good catched, thanks, it should be fixed by #453
