### ISSUE TITLE
Docs list gencfg command, but isn't in latest stable release

### ISSUE THREAD

**Issue by izosozi** [deadc0de6/dotdrop#455]
Dotdrop version: v1.14.2
Using dotdrop: from homebrew

**Describe the bug**

The [getting started documentation](https://dotdrop.readthedocs.io/en/latest/getting-started/) instructs new users to run `dotdrop gencfg > config.yaml` but it appears that `gencfg` hasn't been added yet as of the latest stable release.

**Steps to Reproduce**

1. Install dotdrop with homebrew
2. Run `dotdrop gencfg > config.yaml`

**Expected behavior**

A default config file is created in the current directory.

**Actual behavior**

The dotdrop usage guide is shown and an empty config.yaml file appears in the directory.

Thank you!

**Comment by deadc0de6** [comment]
Hello, thanks for reporting this. I just released version [1.15.0](https://github.com/deadc0de6/dotdrop/releases/tag/v1.15.0) which includes the new command `gencfg` along with other features and fixes. The homebrew PR should be merged soon (https://github.com/Homebrew/homebrew-core/pull/201342).
