### ISSUE TITLE
support comparing gpg transformed files

### ISSUE THREAD

**Issue by scampi** [deadc0de6/dotdrop#46]
I don't know the rationale for not comparing transformed files, but would it be possible to support it when the only transformation is something like gpg ?

https://github.com/deadc0de6/dotdrop/blob/0328efedee4fa5ac867458db763a0d27977b9de9/dotdrop/dotdrop.py#L173

**Comment by deadc0de6** [comment]
There was no real rationale, mostly laziness ;-)
I have added the ability to compare transformed dotfiles in the new release.

If you happen to test this, let me know.
Thanks

**Comment by scampi** [comment]
works nicely thanks!
