### ISSUE TITLE
Support uninstall

### ISSUE THREAD

**Issue by yxliang01** [deadc0de6/dotdrop#47]
Currently, dotdrop works very well! However, I think it would be better if `uninstall` is supported.

Thanks!

**Comment by deadc0de6** [comment]
Thanks!
You mean like a method to delete the installed dotfile and remove it from the config file? Do you have a specific use-case for this for example?

**Comment by yxliang01** [comment]
Hi! I meant that just delete the installed dotfiles but not removing any entry from the config file. This would be useful when there are multiple version of the same rc file (e.g. `vimrc`). It makes sense to create different profile for each version. However, when the link method is used, simply `dotdrop install` will have error saying that `File already exists`. Then, when we want to switch different version of the same rc file, we have to manually delete those linked files. If `uninstall` option is added, we can then just do `dotdrop uninstall && dotdrop install -p SOME_PROFILE`.

**Comment by deadc0de6** [comment]
make sense, ok I'll look into it and will let you know

**Comment by yxliang01** [comment]
Great! Thanks! :D

**Comment by yxliang01** [comment]
@deadc0de6 Could you post your `dotdrop` version? I'm using `v.0.17.0` installed using `pip`. In the situation described previously, `dotdrop` just throws error: `FileExistsError: [Errno 17] File exists: 'SOME-PATH' -> 'SOME-PATH'` without any prompt. If such prompt exists, indeed my use-case is no longer valid.

**Comment by deadc0de6** [comment]
Ok so I found two bugs that were causing this issue. 

First the path used to derive the dotfile's destination was relative (when used with dotdrop from pypi, thus without the `dotdrop.sh` helper script) which resulted in broken symlinks. The second bug was indeed related to file existence test, `os.path.exists` executed on a broken symlink actually returns `False`. Therefore throwing a `FileExistsError` error.

I fixed both issues in the new version and pushed it on pypi.
This should fix your issue.

**Comment by yxliang01** [comment]
@deadc0de6 This is confirmed fixed. Thanks a lot! I couldn't think of a use-case for uninstallation for now. If you think this is not a valid feature, you may close this issue.

**Comment by deadc0de6** [comment]
Cool :-)

I won't implement the `uninstall` unless there's specific needs/use-cases for it. Happy to re-open if you find any though.

Thanks for reporting this!

**Comment by roachsinai** [comment]
Hi, maybe I need it now.

For example, I have a file named `konsole.css` which was used to custom `Konsole` tab bar. I have imported it to `dotfiles`.

And for now I make a new copy named `konsole_extern.css`, so I wanna make a new directory named `konsole` and move this to `css` files into it.

So if there is a `uninstall` operation, I could use `uninstall` to remove `konsole.css` and the use `import` to import the entire `konsole` directory.

**Comment by deadc0de6** [comment]
I see, so the idea would be that `uninstall` removes the file(s) in the *dotpath* and also remove the related entries in the `config.yaml` file?

**Comment by roachsinai** [comment]
Yes, exactly.

**Comment by deadc0de6** [comment]
Alright, I'll work on that and let you know when I have something.

**Comment by dsully** [comment]
+1 to this.

**Comment by deadc0de6** [comment]
Little update, I'm not forgetting you but the config management is being refactored internally and I'll implement the whole `uninstall` feature once that is done as it is tightly dependent on that feature. Thanks for your patience!

**Comment by roachsinai** [comment]
It's fine. @deadc0de6 thanks for your work!

**Comment by deadc0de6** [comment]
I have a first attempt at `remove` in the [parsing-refactoring](https://github.com/deadc0de6/dotdrop/tree/parsing-refactoring) branch. It removes the dotfile in the `dotpath` and also removes entries in the config file. As for `update`, arguments can be the destination path (like `~/.vimrc`) or the dotfile key with the `-k` switch.
If you give it a go, let me know.

**Comment by roachsinai** [comment]
Yeah, `remove` worked. But there will be some side effect:

```
/tmp/e7qZjC_config.yaml                                             config.yaml                                                        
       8   link_dotfile_default: nolink                                    8   link_dotfile_default: nolink                            
       9   link_on_import: nolink                                          9   link_on_import: nolink                                  
      10   longkey: false                                                 10   longkey: false                                          
      11   showdiff: false                                                11   showdiff: false                                         
      12   workdir: ~/.config/dotdrop                                     12   workdir: ~/.config/dotdrop                              
      13 variables:                                                                                                                    
      14   vim_: vimrc.d                                                                                                               
      15 dynvariables:                                                                                                                 
      16   zsh_files: "cd {{@@ _dotdrop_dotpath @@}}; find zshrc.d/                                                                    
 -type f | xargs"                                                                                                                      
      17 dotfiles:                                                        13 dotfiles:                                                 
      18   d_scripts:                                                     14   d_scripts:                                              
      19     dst: ~/Documents/scripts                                     15     dst: ~/Documents/scripts                              
      20     src: Documents/scripts                                       16     src: Documents/scripts                                
      21   f_cargo_config:                                                17   f_cargo_config:                                         
---                                                                 ---                                                                
```

`remove` will rearrange my `dynvariables` and `variables` as bleow:

```
     102   f_zshrc:                                                       95   f_zshrc:                                                
     103     dst: ~/.zshrc                                                96     dst: ~/.zshrc                                         
     104     src: zshrc                                                   97     src: zshrc                                            
                                                                          98 dynvariables:                                             
                                                                          99   zsh_files: cd {{@@ _dotdrop_dotpath @@}}; find zshrc.d/ 
                                                                    -type f | xargs                                                    
     105 profiles:                                                       100 profiles:                                                 
```

```
  160   hwinu:                                                        152   hwinu:                                                  
     161     dotfiles:                                                   153     dotfiles:                                             
     162     - f_vimrc                                                   154     - f_vimrc                                             
     163     - f_gitconfig                                                                                                             
     164     - f_zshrc                                                   155     - f_zshrc                                             
     165     - f_dircolors                                               156     - f_dircolors                                         
     166     - f_git-diff-wrapper.sh                                     157     - f_git-diff-wrapper.sh                               
     167     - f_ycm_extra_conf.py                                       158     - f_ycm_extra_conf.py                                 
                                                                         159 variables:                                                
                                                                         160   vim_: vimrc.d                                           
```

So sorry I failed to upload the screenshot.

**Comment by deadc0de6** [comment]
Indeed it's not so easy to see ;-) 
By *rearrange* you mean they are not in the same order anymore? Did you spot any other side effects?

**Comment by roachsinai** [comment]
Yeah, what I post is `diff` of `config.yaml`. I split it to  3 splits. In each split left side is the origin text, right side is the current text. I first split there is a blank area in right side means the corresponding lines was deleted. And these removed lines are inserted into the second and third splits where is a blank area on left side.

**Comment by roachsinai** [comment]
I haven't found another side effects.

**Comment by deadc0de6** [comment]
I fixed the reordering of keys in the yaml file in 274a613b998f96fc8f383c2d5224c355976681f9. Entries shouldn't be rearranged anymore.
`remove` will be part of dotdrop's next version as soon as I merge the current refactoring branch into master. Thanks for taking the time to testing it :+1:

**Comment by roachsinai** [comment]
Yeah, it should be part of dotdrop's next version as yaml 5.1 not in archlinux repo but in testing for now :smile: .  (I got an error saying no `sort_key`, found on Internet the yaml 5.1 needed.)

**Comment by roachsinai** [comment]
What's more seems Archlinux's `makepkg` command not support directory name with `hyphen` like `parsing-refactoring`.

```
pkgver() {
  cd "${pkgname}"
  git checkout parsing-refactoring
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}
```

If I write `PKGBUILD` as above, the `makepkg` will output that `pkgver not support hyphen, blank chars`. So I have to go to dotdrop source code checkout a new brach without hyphen then update `PKGBUILD` to make it.

**Comment by deadc0de6** [comment]
Thanks for pointing that out. I made sure to use `sort_keys` only when yaml is greater or equal to 5.1.
For users with an older version I'll try to find a workaround to avoid at least the main blocks of the config not to be ordered.

As soon as the branch is stable, I'll merge it to master and update the package on aur, use from source until then thanks.

**Comment by deadc0de6** [comment]
I migrated dotdrop yaml library from [PyYAML](https://pyyaml.org) to [ruamel.yaml](https://pypi.org/project/ruamel.yaml/). Order is now preserved when dotfiles are removed (and config file altered).

This will all be part of the next release.

**Comment by deadc0de6** [comment]
`remove` is now available in the master branch. Feel free to ping me if you need anything or you have issues using the new feature. 
Thanks for the suggestion!
