### ISSUE TITLE
Updating a directory copies destination to wrong path

### ISSUE THREAD

**Issue by maxchaos** [deadc0de6/dotdrop#48]
Hi there.
I have been using dotdrop for quite some time now and I really love it.

Since last month's commit, I have started tracking whole directories and noticed that using dotdrop to update a directory whose source's and destination's base-names are different will result in a new copy inside the dotfiles directory.

For example, let's say that I track the directory `~/foo.d` which is stored in `~/.dotfiles/bar.d` (according to my `config.yaml`). Running:
`dotdrop.sh update ~/foo.d` 
will copy that directory to `~/.dotfiles/foo.d` instead of `~/.dotfiles/bar.d`.
The reason for this seems to be the current implementation of `update` which actually executes:
`['cp', '-R', '-L', '/home/maxchaos/foo.d', '/home/maxchaos/.dotfiles/foo.d/..']`

I guess an easy fix to this issue would be passing the option `-T` to `cp` like that:
`['cp', '-R', '-L', '-T', '/home/maxchaos/foo.d', '/home/maxchaos/.dotfiles/bar.d']`

Any ideas?
Thanks in advance.

**Comment by deadc0de6** [comment]
Thanks for reporting this and sorry for the late reply.

I changed the way `update` works for directories to something like `cp -R -L /home/user/bar.d/* /tmp/dotfiles/dotfiles/foo.d` in branch `updatedir` (92a244636c8595856b437f640ae22e2886a4e6ec).

Can you test it and let me know if that works for you?

**Comment by maxchaos** [comment]
You are very much welcome.

Yes, this seems to do the trick for most cases.

The only issue that I can think of is when, at some point, both directories contain a configuration file or subdirectory (e.g., `/home/user/bar.d/cfg` and `/home/user/.dotfiles/foo.d/cfg`) and the former gets deleted by the user because it is no longer necessary. Running `dotdrop update` does not delete the latter (i.e., `/home/user/.dotfiles/foo.d/cfg`) as one would normally expect.
Should deletions get also handled automatically or is it better to simply warn the user and let them take care of them?

**Comment by deadc0de6** [comment]
You're absolutely right.
I changed it (3a9fd6bbba2e5b342ee378de7cc3a6d9a217855a) and used your suggestion (adding `-T` to `cp`), thanks for that :+1:. I've updated the branch (and fixed the `Log` -> `LOG`).

Can you give it another try please?

**Comment by maxchaos** [comment]
No, unfortunately this does not behave as wanted (I hadn't think of file deletions at the time I suggested adding `-T` to `cp`... sorry for the trouble). This is indeed an issue as what we want to do seems to exceed `cp`'s capabilities (`rsync` is more suitable for the task, but is not installed by default on most distributions).

**Comment by deadc0de6** [comment]
I have completely rework the way `update` works. It now handles all cases (new file, new directory, removed file, removed directory and file content changes). It might be a bit slower (due to the additional operations and comparisons) but will properly allow to update files and entire directories.

It is in branch [reworkupdate](https://github.com/deadc0de6/dotdrop/tree/reworkupdate).
If you have some time, check it out, should work as a `rsync`.

**Comment by deadc0de6** [comment]
FYI this has been merged in master in the latest version

**Comment by maxchaos** [comment]
Awesome work!
I have tested the new implementation for different cases and found a couple of bugs (e.g., unexpanded  tildes in paths, subdirectories not getting merged), which I took the liberty to fix.
Do you want me to send you a PR?

**Comment by deadc0de6** [comment]
Sure, Thanks!

**Comment by deadc0de6** [comment]
merged your PR, thanks again for your help :+1:
