### ISSUE TITLE
Switch/mirror to gitlab

### ISSUE THREAD

**Issue by r4nd0m6uy** [deadc0de6/dotdrop#52]
I wanted to update my submodule but didn't find the project in gitlab. Is it planned to switch/mirror?

:kissing:

**Comment by deadc0de6** [comment]
Sure I'll do it over the week-end and will let you know

**Comment by deadc0de6** [comment]
I've mirrored it in gitlab, there you go: https://gitlab.com/deadc0de6/dotdrop

**Comment by r4nd0m6uy** [comment]
Thank eeeyouuuuu :+1: !
