### ISSUE TITLE
Possible to make Windows compatible (Git bash)?

### ISSUE THREAD

**Issue by comfortablynick** [deadc0de6/dotdrop#55]
I regularly use bash on Windows 7, as well as Linux and Mac. I was installing your script and it started to look like no consideration was given to the possibility of using it on Windows. 

First, it looks for "python3" which was easy enough to fix by a "python3.exe" symlink to "python.exe". The next thing I ran into is this when I tried `$ ./dotdrop.sh compare`
```python
Traceback (most recent call last):  
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main  
    "__main__", mod_spec)  
  File "C:\Python37\lib\runpy.py", line 85, in _run_code  
    exec(code, run_globals)  
  File "C:\Users\nick\dotfiles\dotdrop\dotdrop\dotdrop.py", line 26, in <module>  
    HOSTNAME = os.uname()[1]  
AttributeError: module 'os' has no attribute 'uname'
```

Python recommends using `socket.gethostname()` instead of `os.uname()` (unix-only). After I made this change to `dotdrop.py`, everything seemed to go smoothly.

I don't know if that's all that will be needed, but I thought I'd raise the issue and see if anyone else has used this with bash on Windows.

Thanks!
Nick

**Comment by deadc0de6** [comment]
Thanks for reporting this. 
I'm sorry but I don't use Windows.
I patched the way dotdrop gets the hostname. I will however keep the python3 as many Linux distributions still have python2 per default.

**Comment by comfortablynick** [comment]
Thank you! I know the python3 is necessary, I just didn't know if there were a way to allow the script to work with Windows as well. 

Not a huge deal; as I said, symlinking the python.exe so that the script could find python3.exe worked fine.

**Comment by deadc0de6** [comment]
Cool, feel free to let me know if you encounter other issues.

**Comment by yamlCase** [comment]
@comfortablynick Hi Nick, I'm about to embark on dotdrop for my windows user profile.  Do you have any discoveries you've made since this issue that I should look out for?  I plan on using WSL2 if that matters, so it should be using the Ubuntu's python3.

**Comment by comfortablynick** [comment]
@yamlCase You should be just fine using WSL2. Since I've moved away from Git Bash and started using WSL2, just about everything works as expected, including dotdrop.

I manage my python installs with [asdf](https://github.com/asdf-vm/asdf), but it should work fine with Ubuntu's system python3.
