### ISSUE TITLE
Ignoring files in the configuration file

### ISSUE THREAD

**Issue by DonRichie** [deadc0de6/dotdrop#57]
Hello,

i have a few use cases where folders I imported in dotdrop contain temporary files. Those temporary files show up, every time I use "dotdrop compare"

I would be happy to have a configuration option to specify some files and folders to exclude in the diff output. Basically exactly what the switch "-i --ignore=<name>" does but with more comfort. 
Yes, I could make an alias specifying the ignore switch. But it would be a lot better in my opinion to keep everything a the same place: the config.yaml.

A little example: I use persist ssh session to log into ssh faster. This leads to socket files inside a specified directory. They show up like this:
```
~> dotdrop compare
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.19.2
                               |_|

diffing "d_sockets" VS "~/.ssh/sockets"
only in right: "user@server"
only in right: "user@server"
only in right: "user@server"
only in right: "user@server"
...
```

Thanks and Regards

Richard

**Comment by deadc0de6** [comment]
Thanks for reporting this.
Sure I could add an option in the `dotfile` entry in the config file which would work like `-i --ignore`. Still for ssh the temporary files are probably different depending on which host(s) you connect to and thus it might be helpful to have some wildcards. I was already thinking of improving the `-i --ignore` so I'll add the config option as well.

**Comment by deadc0de6** [comment]
I have implemented the ability to ignore patterns when using compare. Either using the `-i --ignore` (see [compare dotfiles](https://github.com/deadc0de6/dotdrop/tree/cmpignore#compare-dotfiles)) or directly in each dotfile with the `cmpignore` entry (see [config](https://github.com/deadc0de6/dotdrop/tree/cmpignore#config)). It understands Unix shell-style wildcards.

Let me know if that is solving your issue. You should be able to add a pattern like the following to ignore socket file for example:
```yaml
...
  d_ssh:
    dst: ~/.ssh
    src: ssh
    cmpignore:
      - "*@*"
...
```

It is currently only available in the `cmpignore` branch.

**Comment by deadc0de6** [comment]
This was merged into master and is now available in the latest version of dotdrop.

**Comment by DonRichie** [comment]
Hi, 

sounds like it is exactly what I wanted. Thank you very much for the fast reply.

I will test it as soon as possible. I am currently having some trouble updating the dotdrop git repository to the latest commit.

The line "git submodule update --init --recursive" in dotdrop.sh deteaches head of the submodule and checks out an older commit.
> ~/dotfiles> git submodule update --init --recursive
> Submodule path 'dotdrop': checked out '5c61a243045d4a47f463382325632ef26826b0f0'

Which is weird since I told git to follow the master branch in my ".gitmodules" file:
>  [submodule "dotdrop"]
> 	path = dotdrop
> 	url = https://github.com/deadc0de6/dotdrop.git
> 	branch = master

But don't feel obliged to solve that for me. This is most likely a lack of understanding on my side.

**Comment by deadc0de6** [comment]
Cool, happy it helps!

I'm using this in my `dotdrop.sh` if that's of any help:
```bash
git submodule update --init --recursive
git submodule update --remote dotdrop
```

with no specific option in the `.gitmodules`:
```
[submodule "dotdrop"]
	path = dotdrop
	url = https://github.com/deadc0de6/dotdrop.git
```

**Comment by DonRichie** [comment]
I uninstalled and then reinstalled the submodule. This worked. I am sticking to the latest commit now.

git seems to have no "git submodule rm" command so I needed to follow some instructions to manually remove it.

The new feature works fine! Thanks again.
