### ISSUE TITLE
Dotdrop does not work with macOS provided readlink

### ISSUE THREAD

**Issue by rmellema** [deadc0de6/dotdrop#6]
GNU's readlink has the `-f` flag, but this option is not supported by every implementation, like the macOS implementation of readlink. Currently dotdrop uses `readlink -f` to get the directory where `dotdrop.sh` lives, meaning that the script does not start on macOS. It would be nice if dotdrop would not depend on this behaviour, so it also works on systems that do not have GNU readlink, but the BSD variants.

**Comment by deadc0de6** [comment]
I guess I could replace it with `realpath`. Do you happen to have `realpath` on MacOS ? If you do, does it have the same behavior as `readlink -f` ?

```
$ mkdir /tmp/y; cd /tmp/y
$ touch a; ln -s a b; ln -s b c
$ readlink -f c
/tmp/y/a
$ realpath c
/tmp/y/a
```

**Comment by rmellema** [comment]
`realpath` is also not included by default, but can be installed via Homebrew, and unlike `readlink` actually has the same name (`readlink` gets named `greadlink` to not conflict with the macOS provided `readlink`). So the easiest option is then probably to replace `readlink -f` with `realpath` and say that on macOS it depends on `coreutils` from homebrew. That should solve the issue.

**Comment by deadc0de6** [comment]
Should be fixed by 8ba9ce0e971712bc804892ff15b886664cc5e02d, works for you ?

**Comment by rmellema** [comment]
Yeah, this works fine 😄 
Thanks for fixing this!

**Comment by Zornell** [comment]
shouldn't the fix be `rl="readlink -f $0"` instead of  `rl="readlink -f"` ?
Since the operand is missing readlink always fails and realpath is used. IMHO it would be nice not needing to install realpath if readlink is available.

**Comment by deadc0de6** [comment]
you're right, my bad. @Zornell does https://github.com/deadc0de6/dotdrop/commit/ec64a6f645c543037669166527f2a265fe2cc80f fix it for you ?

**Comment by Zornell** [comment]
yes, that works for me. Thanks for the quick fix!

**Comment by uisge-beatha** [comment]
Sorry to comment on this so long after closure, but I'm getting the same error on macOS 10.14.1 while following the setup instructions. Please let me know if there's any additional information I can provide.

**Comment by deadc0de6** [comment]
Could you be more specific, what error do you get?
Did you install realpath through homebrew (part of coreutils)?

**Comment by uisge-beatha** [comment]
That was the error. I was following the instructions further up. I'm not all that keen on homebrew and found a standalone version of realpath. https://github.com/harto/realpath-osx. 

Thanks & sorry to have bothered you.

**Comment by deadc0de6** [comment]
No problem, feel free to open an issue if you're still having issues.
