### ISSUE TITLE
Wildcard hostname?

### ISSUE THREAD

**Issue by FunctionalHacker** [deadc0de6/dotdrop#61]
In addition to my physical machines, I have a lot of VM's which I have to periodically work on. It would be nice to have a wildcard hostname entry in the configuration, so that if I'm trying to install on a machine that doesn't have a known hostname, it would install only my most basic dotfiles like vimrc and zshrc. Is this possible right now?

**Comment by deadc0de6** [comment]
Well currently what you could do is provide the profile you want to use with the `--profile` switch when executing dotdrop. In your case that profile would contain those most basic dotfiles that could be applied to multiple hosts/VMs.

Having a *default* profile in the config would mean that in case the hostname of the host doesn't match any profile in the config, that default profile would be executing. There's currently no such option but I could create one.

**Comment by deadc0de6** [comment]
BTW you could also define/export the env variable `DOTDROP_PROFILE` to let dotdrop know which profile to use.
