### ISSUE TITLE
Is there a way to use sudo when there is a etc file install?

### ISSUE THREAD

**Issue by roachsinai** [deadc0de6/dotdrop#62]
I use `dotdrop`  manage not only self dotfiles, also want to manage some files located at `etc` dir like pacman hook file.

So, is ther a way to let `config.yaml` use `sudo` when install those files?

**Comment by deadc0de6** [comment]
Dotdrop doesn't allow to handle file rights and permissions (at least not directly). Every operations (`mkdir`, `cp`, `mv`, file creation) are executed with the rights of the user calling dotdrop. The rights of the stored dotfile are mirrored on the deployed dotfile (`chmod` like).

However dotdrop allows to handle different config files with different dotfiles. So my suggestion would be to create a different config file (and *dotpath*) for the *global* dotfiles. This config file would be used through the `-c --cfg` switch by sudo or the root user directly to install **only** the *global* dotfiles.

That way you would be able to clearly separate the *local* and *global* dotfiles without any bad surprise.

**Comment by roachsinai** [comment]
Ok, got it.

**Comment by deadc0de6** [comment]
I made a wiki page to document all that: <https://github.com/deadc0de6/dotdrop/wiki/global-config-files>.
