### ISSUE TITLE
vimrc jinja2 not processed?

### ISSUE THREAD

**Issue by madchap** [deadc0de6/dotdrop#66]
Hey,

I have got a weird issue, trying to put some simple jinja into my vimrc (at https://github.com/madchap/dotfiles/blob/master/dotfiles/vimrc).

Nothing gets processed.

Any idea?

Thanks :)

**Comment by deadc0de6** [comment]
Thanks for reporting this!

I'm unable to reproduce. I was able to use your vimrc file and get a valid result (the lines get added) when part of the profile matches and when it doesn't (the lines don't get added).

Do none of the three jinja2 directives get processed or some do? I'm guessing you're trying with the profile `mbp2012`. 

Can you provide me with some more logs (running `install` with `-V`) as well as the profile you are using and the resulting file. Thanks!

**Comment by madchap** [comment]
Hey, nevermind. I need to sleep and quit thinking my brain still functions at 2am... the if is wrong :-)

I knew I was using a bug-free software, and nevertheless ;-)

See ya!

**Comment by deadc0de6** [comment]
So it seems it was an issue with the post action ... wasn't it printed when not using `-V` ?

**Comment by madchap** [comment]
Not even man... you know how braindead I can be :-) I had `if` instead of  `if not` basically...

**Comment by deadc0de6** [comment]
oh ok ;-) well at least now it works :+1:

**Comment by deadc0de6** [comment]
oh ok ;-) well at least now it works :+1:
