### ISSUE TITLE
[feature request] check for file existence

### ISSUE THREAD

**Issue by madchap** [deadc0de6/dotdrop#67]
Hi :)

I was wanting to check for a file existence, in order to source a profile in my zshrc, such as:

```
{%@@ if_exists[$(which kubectl)] @@%}                                                                                                                                                   
source <(kubectl completion zsh)
{%@@ endif @@%}                                                                                                                                                   
```

As I understand, jinja2 templating does not have this capability.

Anyways, just a shot in the dark ;-)

Thanks for the tool! Loving it!

**Comment by deadc0de6** [comment]
Well I see two ways of doing this:

* doing the test in your zshrc (having the lines for all your profiles, bypasses dotdrop in some way)
```bash
hash kubectl 2>/dev/null && source <(kubectl completion zsh)
```

* using dotdrop interpreted variables

in your config.yaml
```yaml
dynvariables:
  dyn1: hash kubectl 2>/dev/null && echo yes
```

in zshrc in your dotpath:
```
{%@@ if dyn1 == "yes" @@%}
source <(kubectl completion zsh)
{%@@ endif @@%}
```

**Comment by deadc0de6** [comment]
I just added a new feature to dotdrop with more available methods from within the templates (see the [doc](https://github.com/deadc0de6/dotdrop#available-methods)).

It won't solve your issue directly but might be useful for the future:
```
{%@@ if exists('/dev/null') @@%}
it does exist
{%@@ endif @@%}
```

If you need some functions, let me know, I'll implement them.

**Comment by madchap** [comment]
That's definitely good enough. Thanks :)
