### ISSUE TITLE
Feature: Ignoring certain files when importing/updating a directory

### ISSUE THREAD

**Issue by justcosmic** [deadc0de6/dotdrop#79]
Hey,

I'm a happy user of your program. I've recently seen the `cmpignore` option which is really handy but I'm wondering if it could be taken a step further.

As far as I understand `cmpignore` only affects `diff` output but what I want to do is ignoring certain files when importing/updating a dir. I currently have a `.vim` directory imported like so:

```yaml
d_vim:
  dst: ~/.vim
  src: vim
```

However, in my `.vim` directory I have a plenty of temporary files that I don't want to import/update (like `.vim/.netrwhist` or `.vim/viminfo`). The only solution I can see so far is importing/updating each file/dir in `.vim` separately. (Correct me if I'm mistaken).

Of course, it could be achieved by using some external software, e.g. adding all the files to a git repository and mantaining a `.gitignore` file. Anyway, I believe it would be a nice feature to have in dotdrop.

Let me know what you think about, thanks!

**Comment by deadc0de6** [comment]
Would the work from @Iambecomeroot on his PR #77 solve your issue? He is more oriented on linking those files though, do you have a different use-case?
I don't know how far he is from implementing it though.

**Comment by justcosmic** [comment]
I see, it seems to be what I want to achieve except, as you said, he uses symlinks for those dotfiles. I was thinking about a more generic implementation where you can blacklist certain files/directories for a given dotfile - similar to `.gitignore` but dotfile-specific. Whenever those temporary files are added to the dotdrop during importing/updating a dotfile directory, they are also ready to be installed next time I call `dotdrop install` which is a bit of a nuisance. I saw `cmpignore` and this came to my mind soon after that.

Anyway, I've just realized that not using symlinks (I just let dotdrop copy files during `dotdrop install`) leads to such issues. If I need to edit my `~/.vim/vimrc`, I run `dotdrop update` to make sure it's in sync with the rest of my dotfiles. If I used symlinks instead, I wouldn't have to rely on updating. So I think I should setup those symlinks once so that they point to wherever my dotdrop dotfiles are.

Sorry, I was confused by how dotdrop works (this is my first when I try to manage my dotfiles across multiple machines) and now I feel my feature idea is rather unnecessary. `link_children` seems much more reasonable and if I switch to using symlinks, it will be everything I need.

**Comment by deadc0de6** [comment]
To be honest, I still think the idea of an `ignore` feature for `import`, `update` and `install` is a good feature. And it would solve that specific issue for people not using symlinks.

I'll see what I can do and give it a bit more thoughts on how I can implement that.

**Comment by deadc0de6** [comment]
@justcosmic I have implemented ignore patterns for `update`. That should allow you to handle your `~/.vim` more properly. You can either provide the ignore pattern on the command line (with `-i --ignore`) or directly in the config file through the `upignore` key:

For example:
```yaml
dotfiles:
  d_vim
    dst: ~/.vim
    src: vim
    upignore:
    - "*/undo-dir"
    - "*/plugged"
```

for more see <https://github.com/deadc0de6/dotdrop#update-dotfiles>.

The idea would be to import for example your `~/.vim`, then remove in the `dotpath` the files/directories you don't want to manage and add their respective ignore patterns in the config file.

Please let me know if you get the chance to test it. I implemented some tests but might have missed some corner cases, some testing help is always welcome ;-)

**Comment by justcosmic** [comment]
Great news! I've updated my `config.yaml` for a couple of my dotfile directories and everything works fine. I'll keep it for now until `link_children` is fully implemented.

Thanks for feedback!

**Comment by Iambecomeroot** [comment]
I see you guys have been talking about my PR. I didn't forget. I just started a new job recently and have been pretty busy. I'll try to take a look at it again this weekend.

**Comment by deadc0de6** [comment]
@Iambecomeroot sounds awesome, no stress. I think your feature will be quite useful for some people :-) Congrats for the new job!

**Comment by deadc0de6** [comment]
@justcosmic I'm closing this as I guess the requested feature has been implemented. 
Thanks for the suggestion!

**Comment by deadc0de6** [comment]
@justcosmic FYI the PR on `link_children` has been merged and is available in the master branch.
