### ISSUE TITLE
Allow disabling link option

### ISSUE THREAD

**Issue by mchwalisz** [deadc0de6/dotdrop#80]
This is connected to #49 , if I enable `link_by_default: true` I cannot import any file as not link.

I'm assuming use case where I would like to usually import something as link. Sometimes, i.e. when I know the config file will become a template, it would be better to import without link.

I don't see an option to actually do it right now without editing `config.yaml` manually.

**Comment by deadc0de6** [comment]
I can solve this two ways:

* changing the behavior of `-l --link` to invert whatever the default is set to
* adding a new option `-L --nolink` to allow to  *not link* when `link_by_default: true`

I do have a preference for the second one as the first one is not very elegant ... user will have to know what defaults she/he is using. What do you think?

**Comment by mchwalisz** [comment]
Totally agree with both ideas and also think `--no-link` (with additional dash) is much more clear and explicit.

**Comment by deadc0de6** [comment]
Ok, I'll implement the `-L --no-link`, will keep you posted.

**Comment by deadc0de6** [comment]
I had to implement the first solution (invert the value of `link_by_default`) as there's no way of knowing if the user has provided the flag.

```
  -l --inv-link           Invert the value of "link_by_default" when importing.
```

The new version is available in the master branch.
