### ISSUE TITLE
Try automatic updates with templates

### ISSUE THREAD

**Issue by dbacc** [deadc0de6/dotdrop#82]
I understand that updating files which include templates cannot _always_ be done automatically correct and in a reliable way.
However I'd like to see an  option to at least try this in certain occasions (maybe with a warning that this may lead to unwanted behavior)
Most of the times for me a simple
`diff -u tmpfile localfile | patch dotfile`
just works. However its a bit cumbersome having to type
`dotdrop install -t`
first and typing all the paths.

**Comment by deadc0de6** [comment]
Interesting approach. Of course I could potentially add a cli switch that *tries* to patch the dotfile using your one-liner.

Or even let the user choose when the template is detected.

**Comment by deadc0de6** [comment]
I made a quick (very) dirty fix in order to generate a one liner (and the temporary generated template) for more easily updating templates. The user still has to run the command and do the checking on his own but at least the temporary templated file is generated and so is the one-liner.

The idea is to provide `-P --show-patch` with the `update` command to have the temporary template generated and the one-liner printed. It shows something like that:
```bash
[WARN] /tmp/tmp.jq0QGaogTK/dotfiles/abc uses template 
[WARN] try patching with: diff -u /tmp/dotdrop-zks1lk8p /tmp/tmp.4Xtkfdvckj/abc | patch /tmp/tmp.jq0QGaogTK/dotfiles/abc
```

I must admit I haven't extensively tested it so I'd be thankful if you could give it a try. It is in the `template-patching` branch.

**Comment by dbacc** [comment]
Thanks for the quick reaction. I tried a few times, and it seems to work :) That already helps a lot.

**Comment by deadc0de6** [comment]
This has been merged into the master branch.
Thanks for the suggestion!

**Comment by roachsinai** [comment]
So, this function not including in current release -- `0.24.1`?

**Comment by deadc0de6** [comment]
@roachsinai it is currently only available on the master branch (git). I will release a pypi version soon with all the recent changes, before end of week. Works for you?

**Comment by deadc0de6** [comment]
@roachsinai version 0.25.0 has been published on pypi! See the changelog: <https://github.com/deadc0de6/dotdrop/releases/tag/v0.25.0>

**Comment by roachsinai** [comment]
@deadc0de6 I updated by change `PKGBUIKD`. And sames working in DEBUD mode?

```
➜  ~ which dpup
dpup: aliased to dotdrop update
➜  ~ dpup .zshrc
[DEBUG][dotdrop.options.__init__] config file: /home/roach/code/Git/dotfiles/config.yaml
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.25.0
                               |_|

[WARN] /home/roach/code/Git/dotfiles/dotfiles/zshrc uses template, update manually 
```

**Comment by roachsinai** [comment]
Glad to see that automatic updates with templates worked.

```
➜  ~ dotdrop update --show-patch ~/.zshrc
[DEBUG][dotdrop.options.__init__] config file: /home/roach/code/Git/dotfiles/config.yaml
     _       _      _
  __| | ___ | |_ __| |_ __ ___  _ __                                                                                                              
 / _` |/ _ \| __/ _` | '__/ _ \| '_ |                                                                                                             
 \__,_|\___/ \__\__,_|_|  \___/| .__/  v0.25.0                                                                                                    
                               |_|                                                                                                                

[WARN] /home/roach/code/Git/dotfiles/dotfiles/zshrc uses template, update manually 
[WARN] try patching with: "diff -u /tmp/dotdrop-yd973r9r /home/roach/.zshrc | patch /home/roach/code/Git/dotfiles/dotfiles/zshrc" 
```

**Comment by deadc0de6** [comment]
@roachsinai Thanks! I removed the extra debug info and release a new version on aur.
