### ISSUE TITLE
json dotfile template

### ISSUE THREAD

**Issue by mchwalisz** [deadc0de6/dotdrop#87]
There seems to be a problem with `json` template dotfiles.

Minimal example:

```
{"a": "{{@@ header() @@}}"}
```
while installing it, the header is not expanded. `dotdrop install` copies the file without change. It is enough to make source file not a valid json to "fix" the problem.

For example:
````
{"a": "{{@@ header() @@}}",}
````
Produces:
```
{"a": "This dotfile is managed using dotdrop",}
```
Notice `,` at just before end of json (making it not valid one).

**Comment by deadc0de6** [comment]
Thanks for reporting this!
This should be fixed in the master branch.
Let me know if you're having other issues.

**Comment by mchwalisz** [comment]
that helped. Thanks!
