### ISSUE TITLE
Removing files after importing

### ISSUE THREAD

**Issue by japorized** [deadc0de6/dotdrop#9]
Hi there, thanks for making dotdrop! Absolutely love the idea behind it.

How does dotdrop go about removing files after importing, say you may have accidentally imported something that's in a directory that you only come to realize later on. Will it work if I just remove the files from the dotfiles directory and from the config file?

**Comment by deadc0de6** [comment]
Thanks :blush:

Yes it will work. Dotdrop is entirely relying on the config file (`config.yaml`), so removing the lines (in the  `dotfiles` entry and their references in `profiles` entry) will stop dotdrop *using* them. Removing them from the dotfiles directory will help keep your repo clean ;-).

**Comment by japorized** [comment]
I see. That's great! Thanks (and for the quick reply)!

**Comment by deadc0de6** [comment]
I'm adding some repositories as examples in the readme, would you be ok if I add yours as a reference ?

**Comment by japorized** [comment]
Sure thing :)

**Comment by deadc0de6** [comment]
thanks !
