### ISSUE TITLE
docker or snap dotdrop?

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#92]
What do you think about docker or snap dotdrop version?
IMHO Dotdrop biggest weakness lies within deploying and updating process, 
this way it could be simplify to one command install and automatic background updates.
for reference
https://docs.snapcraft.io/python-apps/6741
regards

**Comment by mchwalisz** [comment]
I don't think docker will be best idea. The volume mounting there will be very hard to sort out.

Snap is probably much better, here the confinement needs also to be checked.

The third option is to prepare packages for different distributions.

**Comment by deadc0de6** [comment]
It makes little sense to have dotdrop in a docker IMHO.

It is recommended to install dotdrop as a submodule of your dotfiles repository and it gets updated automatically when using the `dotdrop.sh` script (see [As a submodule](https://github.com/deadc0de6/dotdrop/wiki/installation#as-a-submodule)).

Dotdrop is also available on [pypi](https://pypi.org/project/dotdrop/) and on [aur](https://aur.archlinux.org/packages/?K=dotdrop).

I have no experience with snap but would be happy to add it there. Anyone ready to provide a snapcraft config to publish dotdrop?

**Comment by deadc0de6** [comment]
Dotdrop is now also available as a [snap package](https://snapcraft.io/dotdrop)!
Thanks again to @mchwalisz for his help :+1:

**Comment by niksfirefly** [comment]
great!!
any chance for raspberry pi armv7l snap?

**Comment by mchwalisz** [comment]
Shouldn't be too hard as it was easy snap. Maybe open new issue, as here it is hard to find.
