### ISSUE TITLE
raspberry pi armv7l snap?

### ISSUE THREAD

**Issue by niksfirefly** [deadc0de6/dotdrop#96]
any chance for raspberry pi armv7l snap?
regards

**Comment by deadc0de6** [comment]
I'd like to but it seems snapcraft cross-compilation for python is not supported:

* <https://forum.snapcraft.io/t/cross-compile-support-for-python-plugin/1286/3>
* <https://bugs.launchpad.net/snapcraft/+bug/1808454>

Again I'm no expert on snap. Maybe @mchwalisz knows more?

An alternative would be to use the pypi package on a raspberry
```bash
sudo pip3 install dotdrop
```

**Comment by mchwalisz** [comment]
Indeed cross-compilation doesn't seem to work. I also get errors. Link pointers are helpful.

On the other hand it looks like native compilation should work. I'm trying to build on my odriod, for now without success. If I'm successful, how should I share the snap?

**Comment by deadc0de6** [comment]
I will try over the week-end on a raspberry pi directly, will keep you updated of the progress.

**Comment by mchwalisz** [comment]
I failed for now. I have Odroid C1 which comes with old Ubuntu and kernel, which in turn probably creates problems with snapcraft.

**Comment by deadc0de6** [comment]
@niksfirefly I haven't been able to do it yet. 
In the meantime you can always use the pypi version on a raspi with
```bash
sudo apt install python3 python3-pip
pip3 install --user dotdrop
~/.local/bin/dotdrop --help
```

**Comment by deadc0de6** [comment]
I'm gonna close this for now since it seems snapcraft is a pain on arm.
As mentioned above dotdrop can easily be installed using pypi on arm platform.
