### ISSUE TITLE
[features request] add bash-completion for basic command

### ISSUE THREAD

**Issue by mygithubthrowaway** [deadc0de6/dotdrop#97]
Hi,
very nice project, i love it.

Features request as title, thanks!

**Comment by mchwalisz** [comment]
As dotdrop depends on [docopt](https://github.com/docopt/docopt) it is related to docopt/docopt#21.

**Comment by deadc0de6** [comment]
I have added the scripts in [completion](https://github.com/deadc0de6/dotdrop/tree/master/completion) for `bash` and `zsh`.

You need to use a different file if you use dotdrop through `dotdrop.sh` or through the `dotdrop` python script directly (pypi, etc).

**Comment by deadc0de6** [comment]
@mchwalisz thanks for the pointer, didn't know about that tool, very helpful!

**Comment by mygithubthrowaway** [comment]
wonderful!! thanks man
